SELECT * FROM ALL_ALL_TABLES WHERE TABLE_NAME LIKE '%AGREG%';


-- PEGAR A DATA DO CREDITO (CARGA)
-- VER SE NO MESMO DIA DA CARGA O CLIENTE CLIGA POR CAUSA DO SVA.
SELECT * FROM DWH.BI_DIM_ASSINANTE_SVA;  --- SOMENTE SVA ATIVA NO MOMENTO DA RECARGA
SELECT * FROM DWH.BI_DIM_PARCEIRO_SERVICO_SVA;
SELECT * FROM DWH.BI_STG_AGG_RCT_REPORT_VAS;

SELECT * FROM DWH.BI_FP_ASSINANTE_CONSUMO ;

SELECT * FROM DWH.BI_FP_NF_RECARGA;
SELECT * FROM DWH.BI_DIM_TIPO_RECARGA;
SELECT * FROM DWH.BI_DIM_PROJECAO_RECARGA_BI;
SELECT * FROM DWH.BI_DIM_MODALIDADE_RECARGA;

SELECT COUNT(DISTINCT(NUM_NTC))  
SELECT * FROM DWH.BI_AGG_RELACAO_CONSUMO_RECARGA RC ---tabela de consumo de dados, sms, voz





SELECT * FROM ALL_TABLES WHERE TABLE_NAME LIKE '%RECARGA%' AND OWNER LIKE '%DWH%'
