WITH

CALL_ID_CMV AS

(SELECT 'Claro Móvel' AS NM_MARCA,
       'CMV' AS NM_SUB_MARCA,
       FT.SK_ATENDIMENTO_URA AS CALL_ID,
       FT.DT_INICIO_LIGACAO,
       FT.NR_HORA_INICIO_LIGACAO,
       FT.DT_FIM_LIGACAO,
       FT.NR_HORA_FIM_LIGACAO,
       FT.NR_DURACAO_ATENDIMENTO,
       UN.DSC_UN_NEGOCIO AS REGIONAL,
       FT.NR_URA AS NUM_DNIS,
       AR.COD_AREA AS NR_DDD,
       FT.CD_NUMERO_TELEFONE AS NUM_NTC,
       FT.CD_NUMERO_TELEFONE_ANI AS NUM_NTC_ANI,
       FT.CD_NAVEGACAO_CLIENTE_URA,
       PLA.DSC_PLATAFORMA AS COD_PLATAFORMA,
       APL.NM_AGRUPAMENTO_PLATAFORMA_BI AS NM_AGRUPAMENTO_PLATAFORMA,
       APL.NM_ATENDIMENTO_PLATAFORMA_BI AS NM_PLATAFORMA,
       CASE
         WHEN FT.FN_LIGACAO_IDENTIFICADA = 1 THEN
          'Sim'
         ELSE
          'Não'
       END AS FG_LIG_IDENTIFICADA,
       STS.COD_SUB_STS_ATU STATUS_CLIENTE,
       CASE
         WHEN FT.FN_CORPORATIVO = 1 THEN
          'Sim'
         ELSE
          'Não'
       END AS FN_CORPORATIVO,
       TDU.COD_TIPO_DESCONEXAO,
       TDU.DSC_TIPO_DESCONEXAO AS TIPO_DESCONEXAO,
       CASE
         WHEN VA.NM_VISAO_ANALISE_BI = 'Contact Rate Direcionado ao Humano' THEN
          'Direcionado Humano'
         ELSE
          'Retido URA'
       END FC_DIRECIONADO_RETIDO,
       FT.CD_ATENDIMENTO_SCRIPT AS NR_SCRIPTPOINT,
       ATS.NM_ATENDIMENTO_SCRIPT_BI AS DS_SCRIPTPOINT,
       ATM.NM_TIPO_MOTIVO_BI AS NM_MOTIVO_URA,
       STM.NM_SUB_TIPO_MOTIVO_BI AS NM_SUB_MOTIVO_URA,
       ATL.NM_TIPO_LIGACAO_BI AS NM_EXPURGO_URA,
       CCC.DSC_CICLO AS DT_VENCIMENTO_FATURA,
       FA.NM_ATENDIMENTO_FAIXA_AGING_BI AS NM_TEMPO_BASE,
       FE.NM_ATENDIMENTO_FAIXA_ETARIA_BI AS NM_FAIXA_ETARIA,
       ATC.NM_AGRUPAMENTO_TIPO_CLIENTE AS NM_TP_CLIENTE,
       PP.DSC_PLANO_PRECO_BI AS TP_PLANO_CLIENTE,
       CASE
         WHEN FT.FN_DIA_UTIL = 1 THEN
          'Útil'
         ELSE
          'Não Útil'
       END AS FN_DIA_UTIL,
       FT.CD_RAT_PROD_PRI,
       FT.CD_RAT_PROD_SEC,
       FT.CD_RAT_MOT_PRI,
       FT.QT_LIGACAO_REAL,
       FT.QT_RAT_PROD_PRI,
       FT.QT_RAT_PROD_SEC,
       FT.QT_RAT_PROD_RES,
       FT.QT_RAT_PROD_FINAL,
       FT.QT_RAT_MOT_PRI,
       FT.QT_RAT_MOT_SEC,
       FT.QT_RAT_MOT_RES,
       FT.QT_RAT_MOT_FINAL
  FROM INTMKT.FT_ATENDIMENTO_URA@BASECLARO FT
  LEFT JOIN DWH.BI_DIM_UN_NEGOCIO@BASECLARO UN
    ON UN.DW_UN_NEGOCIO = FT.SK_REGIONAL
  LEFT JOIN DWH.BI_DIM_AREA@BASECLARO AR
    ON AR.DW_AREA = FT.SK_AREA
  LEFT JOIN DWH.BI_DIM_PLATAFORMA@BASECLARO PLA
    ON PLA.COD_PLATAFORMA = FT.SK_PLATAFORMA
  LEFT JOIN INTMKT.DS_ATENDIMENTO_PLATAFORMA@BASECLARO APL
    ON APL.SK_ATENDIMENTO_PLATAFORMA = FT.SK_ATENDIMENTO_PLATAFORMA
  LEFT JOIN DWH.BI_DIM_STATUS@BASECLARO STS
    ON STS.STS_DW = FT.SK_STATUS
  LEFT JOIN DWH.BI_DIM_TIPO_CLIENTE@BASECLARO TC
    ON TC.DW_TIPO_CLIENTE = FT.SK_TIPO_CLIENTE
  LEFT JOIN DWH.BI_DIM_FAIXA_HORA@BASECLARO FXH
    ON FXH.DW_FAIXA_HORA = FT.SK_FAIXA_HORA
  LEFT JOIN DWH.BI_DIM_MENU_URA@BASECLARO MNU
    ON MNU.DW_MENU_URA = FT.SK_MENU_URA
  LEFT JOIN DWH.BI_DIM_AUTOMACAO_URA@BASECLARO ARA
    ON ARA.DW_AUTOMACAO_URA = FT.SK_AUTOMACAO_URA
  LEFT JOIN DWH.BI_DIM_NAVEGACAO_URA@BASECLARO NVU
    ON NVU.DW_NAVEGACAO_URA = FT.SK_NAVEGACAO_URA
  LEFT JOIN DWH.BI_DIM_TIPO_DESCONEXAO_URA@BASECLARO TDU
    ON TDU.DW_TIPO_DESCONEXAO = FT.SK_TIPO_DESCONEXAO
  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_MOTIVO@BASECLARO ATM
    ON ATM.SK_ATENDIMENTO_TIPO_MOTIVO = FT.SK_ATENDIMENTO_TIPO_MOTIVO
  LEFT JOIN INTMKT.DS_ATENDIMENTO_SCRIPT@BASECLARO ATS
    ON ATS.SK_ATENDIMENTO_SCRIPT = FT.SK_ATENDIMENTO_SCRIPT
  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_LIGACAO@BASECLARO ATL
    ON ATL.SK_ATENDIMENTO_TIPO_LIGACAO = FT.SK_ATENDIMENTO_TIPO_LIGACAO
  LEFT JOIN DWH.BI_DIM_CICLO@BASECLARO CCC
    ON CCC.DW_CICLO = FT.SK_NUMERO_CICLO
  LEFT JOIN DWH.BI_DIM_PLANO_PRECO@BASECLARO PP
    ON PP.DW_PLANO = FT.SK_PLANO
  LEFT JOIN INTMKT.DS_ATENDIMENTO_SUB_TIPO_MOTIVO@BASECLARO STM
    ON STM.SK_ATENDIMENTO_SUB_TIPO_MOTIVO =
       FT.SK_ATENDIMENTO_SUB_TIPO_MOTIVO
  LEFT JOIN INTMKT.DS_VISAO_ANALISE@BASECLARO VA
    ON VA.SK_VISAO_ANALISE = FT.SK_VISAO_ANALISE
  LEFT JOIN INTMKT.DS_ATENDIMENTO_FAIXA_AGING@BASECLARO FA
    ON FA.SK_ATENDIMENTO_FAIXA_AGING = FT.SK_ATENDIMENTO_FAIXA_AGING
  LEFT JOIN INTMKT.DS_ATENDIMENTO_FAIXA_ETARIA@BASECLARO FE
    ON FE.SK_ATENDIMENTO_FAIXA_ETARIA = FT.SK_ATENDIMENTO_FAIXA_ETARIA
  LEFT JOIN INTMKT.DS_AGRUPAMENTO_TIPO_CLIENTE@BASECLARO ATC
   ON ATC.SK_AGRUPAMENTO_TIPO_CLIENTE = FT.SK_AGRUPAMENTO_TIPO_CLIENTE
  LEFT JOIN INTMKT.DS_CALENDARIO@BASECLARO CAL
    ON CAL.SK_CALENDARIO = FT.SK_DATA
  LEFT JOIN INTMKT.DS_FLAG@BASECLARO FL
    ON FL.SK_FLAG = FT.SK_FC_ASSINANTE_ZB
  WHERE FT.SK_DATA >= 20191101 AND FT.SK_DATA < 20191201),

MOTIVOS_PS8 AS
  
(SELECT /*PARALLEL (8) */
        T.NUM_NTC,
        MC.DSC_METODO_CONTATO AS METODO_CONTATO,
        M.DSC_MOTIVO_ATEND_NIVEL_1,
        M.DSC_MOTIVO_ATEND_NIVEL_2,
        M.DSC_MOTIVO_ATEND_NIVEL_3,
        M.DSC_MOTIVO_ATEND_NIVEL_4,
        M.DSC_MOTIVO_ATEND_NIVEL_5,
        COUNT (*) AS QTDE_PROTOC
FROM BI_FP_ASSINANTE_ATEND_FECHADO@BASECLARO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO@BASECLARO M
ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO@BASECLARO MC
ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND M.DSC_MOTIVO_ATEND_NIVEL_1 IN ('Informação','Solicitação','Reclamação','Reclamação 1º Nível')
AND M.DSC_MOTIVO_ATEND_NIVEL_2 IN ('Banda Larga Conta','Claro Cartão','Claro Controle','Claro Empresa-Pequena e Média','Claro Conta','Claro Empresa-Grande','Banda Larga PME','Não Cliente','Banda Larga GE','Claro Flex')
AND M.DSC_MOTIVO_ATEND_NIVEL_3 IN ('Planos e Tarifas','Anormalidade Temporária','Comparativo de Planos (Auto)','Características','Contestação')
AND M.DSC_MOTIVO_ATEND_NIVEL_4 IN ('Planos','Plano Claro Total','Troca de Plano','Troca de Plug-In','Características','Plano Pronto  Linha Econômica','Planos Não Comercializados','Telemetria / IOT','Pacote Família Controle','Desmembramento','Correção','Novo Plano AACEE','Telemetria PME','Plano Claro Total Invididual','Plano Pronto Claro Direto','Sob Medida EmpresaTelemetria P','Controle Fácil','Planos e Pacotes')
AND M.DSC_MOTIVO_ATEND_NIVEL_5 IN ('Migração indevida','Desistiu da troca de Plano','Promo Claro Combo','DownGrade','UpGrade - Troca Manual','Upgrade','Cadastro Controle Fácil','Oferta errada')
GROUP BY 
        T.NUM_NTC,
        MC.DSC_METODO_CONTATO,
        M.DSC_MOTIVO_ATEND_NIVEL_1,
        M.DSC_MOTIVO_ATEND_NIVEL_2,
        M.DSC_MOTIVO_ATEND_NIVEL_3,
        M.DSC_MOTIVO_ATEND_NIVEL_4,
        M.DSC_MOTIVO_ATEND_NIVEL_5),

PROMOCAO_CMV AS

(SELECT 
      A.NUM_NTC,
      A.DAT_ATIVACAO_LINHA_ASS,
      A.DAT_EFETIVACAO_PROMOCAO,
      B.DSC_CANAL_PROMOCAO_PRE
FROM BI_FP_ASS_PROMOCAO_PRE@BASECLARO A
LEFT JOIN BI_DIM_CANAL_PROMOCAO_PRE@BASECLARO B 
ON A.DW_CANAL_PROMOCAO_PRE = B.DW_CANAL_PROMOCAO_PRE
GROUP BY
      A.NUM_NTC,
      A.DAT_ATIVACAO_LINHA_ASS,
      A.DAT_EFETIVACAO_PROMOCAO,
      B.DSC_CANAL_PROMOCAO_PRE)

SELECT 
      A.METODO_CONTATO,
      A.DSC_MOTIVO_ATEND_NIVEL_1,
      A.DSC_MOTIVO_ATEND_NIVEL_2,
      A.DSC_MOTIVO_ATEND_NIVEL_3,
      A.DSC_MOTIVO_ATEND_NIVEL_4,
      A.DSC_MOTIVO_ATEND_NIVEL_5,
      B.CALL_ID,
      C.DAT_ATIVACAO_LINHA_ASS,
      C.DAT_EFETIVACAO_PROMOCAO,
      C.DSC_CANAL_PROMOCAO_PRE
      ,COUNT(*)
FROM MOTIVOS_PS8 A 
LEFT JOIN CALL_ID_CMV B ON A.NUM_NTC = B.NUM_NTC
LEFT JOIN PROMOCAO_CMV C ON A.NUM_NTC = C.NUM_NTC
GROUP BY
      A.METODO_CONTATO,
      A.DSC_MOTIVO_ATEND_NIVEL_1,
      A.DSC_MOTIVO_ATEND_NIVEL_2,
      A.DSC_MOTIVO_ATEND_NIVEL_3,
      A.DSC_MOTIVO_ATEND_NIVEL_4,
      A.DSC_MOTIVO_ATEND_NIVEL_5,
      B.CALL_ID,
      C.DAT_ATIVACAO_LINHA_ASS,
      C.DAT_EFETIVACAO_PROMOCAO,
      C.DSC_CANAL_PROMOCAO_PRE


