WITH 
TMP_SQD_AA_WTSAPP_01 AS

(SELECT /*+parallel (32)*/
        A.DAT_REFERENCIA,
        A.COD_PLATAFORMA,
        A.COD_ATENDIMENTO

FROM DWH.BI_FP_ATENDIMENTO_MINT A
LEFT JOIN DWH.BI_DIM_CANAL_MINT B ON A.DW_NUM_CANAL_MINT = B.DW_NUM_CANAL_MINT
WHERE A.COD_SHORT_CODE = 9652 --- SHORT CODE DO WHATSAPP
--WHERE A.COD_SHORT_CODE = 1052 --- SHORT CODE DO USSD
AND A.DAT_REFERENCIA BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')),

TMP_SQD_AA_WTSAPP_02 AS

(SELECT  /*+PARALLEL (32)*/
        A.DAT_REFERENCIA
       ,A.COD_PLATAFORMA
       ,C.DSC_NOS_MINT
       ,D.PARA AS DSC_PARA_MINT

FROM TMP_SQD_AA_WTSAPP_01 A
LEFT JOIN DWH.BI_FP_NAVEGACAO_MINT B ON A.COD_ATENDIMENTO = B.COD_ATENDIMENTO
                                    AND A.DAT_REFERENCIA  = B.DAT_REFERENCIA
LEFT JOIN DWH.BI_DIM_NOS_MINT C ON B.DW_NOS_MINT = C.DW_NOS_MINT
LEFT JOIN INTMKT.DE_PARA_MINT D ON C.DSC_NOS_MINT = D.DE
                                                                      
WHERE B.DW_NUM_CANAL_MINT = 2)

SELECT * FROM TMP_SQD_AA_WTSAPP_02
