
/*--===========================================================================================================================
OBJETIVO: 
		ANALISE SOBRE CLIENTE NÃO RETIDO NO WHATSAPP
		
--===========================================================================================================================*/

       
/*WITH 
ATEND_FECHADO_P1 AS (*/
DROP TABLE TMP_SQDAA_MOT_RET_P1;
CREATE TABLE TMP_SQDAA_MOT_RET_P1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*PARALLEL (32) */
 * 
FROM BI_FT_RET_DIG_WHATSAPP W
WHERE W.SAFRA = &SAFRA
      AND W.DSC_VISAO_ANALISE = 'ACESSOU E LIGOU' 
      AND W.DSC_SAFRA = 'D 0'
;

DROP TABLE TMP_SQDAA_MOT_RET_P2;
CREATE TABLE TMP_SQDAA_MOT_RET_P2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*PARALLEL (32) */
        T.NUM_NTC
        ,T.DAT_INICIO_ATENDIMENTO
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO), 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000')) AS SK_LIGA 
        ,W.SK_ACESSO
        ,TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO), 'RRRRMMDD') AS SK_DATA
        ,T.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO
        ,T.DW_MOTIVO_ATENDIMENTO
        ,regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_1,'00000')||
                        TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_2,'00000'),'[[:space:]]*','')|| 
               (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_3 = -3 THEN '00000' 
                     ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_3,'00000'),'[[:space:]]*',''))END)||         
               (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_4 = -3 THEN '00000' 
                     ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_4,'00000'),'[[:space:]]*',''))END)||
                (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_5 = -3 THEN '00000' 
                      ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_5,'00000'),'[[:space:]]*',''))END)
                           AS ID_MOTIVOS_TUPLA
         ,M.DSC_MOTIVO_ATEND_NIVEL_1         
         ,M.DSC_MOTIVO_ATEND_NIVEL_2
         ,M.DSC_MOTIVO_ATEND_NIVEL_3
         ,M.DSC_MOTIVO_ATEND_NIVEL_4
         ,M.DSC_MOTIVO_ATEND_NIVEL_5
--SELECT *                 
FROM BI_FP_ASSINANTE_ATEND_FECHADO T
INNER JOIN TMP_SQDAA_MOT_RET_P1 W
      ON T.NUM_NTC = W.NUM_NTC
      AND TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO), 'RRRRMMDD') = W.SK_DATA

LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
     ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC
     ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO

WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
      AND MC.DW_METODO_CONTATO IN (83,37,25,45,42,621,551) --- SOMENTE METODOS QUE RECEBE LIGAÇÃO NO PS8
--      AND MC.DW_METODO_CONTATO NOT IN (81, 411, 451,552,681,701,781,791) --EXPURGO WEB SITES E APP
    
GROUP BY 
         T.NUM_NTC
         ,T.DAT_INICIO_ATENDIMENTO
         ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO), 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000')) 
         ,W.SK_ACESSO
        ,T.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO
        ,T.DW_MOTIVO_ATENDIMENTO
        ,regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_1,'00000')||
                        TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_2,'00000'),'[[:space:]]*','')|| 
               (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_3 = -3 THEN '00000' 
                     ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_3,'00000'),'[[:space:]]*',''))END)||         
               (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_4 = -3 THEN '00000' 
                     ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_4,'00000'),'[[:space:]]*',''))END)||
                (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_5 = -3 THEN '00000' 
                      ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_5,'00000'),'[[:space:]]*',''))END)
        ,M.DSC_MOTIVO_ATEND_NIVEL_1         
         ,M.DSC_MOTIVO_ATEND_NIVEL_2
         ,M.DSC_MOTIVO_ATEND_NIVEL_3
         ,M.DSC_MOTIVO_ATEND_NIVEL_4
         ,M.DSC_MOTIVO_ATEND_NIVEL_5
;

SELECT  
      &SAFRA AS SAFRA
      ,T.DSC_MOTIVO_ATEND_NIVEL_1         
      ,T.DSC_MOTIVO_ATEND_NIVEL_2
      ,T.DSC_MOTIVO_ATEND_NIVEL_3
      ,T.DSC_MOTIVO_ATEND_NIVEL_4
      ,T.DSC_MOTIVO_ATEND_NIVEL_5
      ,NVL(DMO.DSC_CATEGORIA,'-3') AS DSC_CATEGORIA
      ,NVL(DMO.DSC_FUNCIONALIDADE,'-3') AS DSC_FUNCIONALIDADE        
      ,COUNT(DISTINCT(T.SK_LIGA)) AS QT_LIGAÇÕES
      ,COUNT(DISTINCT(T.NUM_NTC)) AS QT_USUARIOS               
FROM TMP_SQDAA_MOT_RET_P2 T
LEFT JOIN TMP_SQDAA_DIM_MOT_CMV DMO
     ON T.ID_MOTIVOS_TUPLA = DMO.ID_MOTIVOS_TUPLA

GROUP BY
      T.DSC_MOTIVO_ATEND_NIVEL_1         
      ,T.DSC_MOTIVO_ATEND_NIVEL_2
      ,T.DSC_MOTIVO_ATEND_NIVEL_3
      ,T.DSC_MOTIVO_ATEND_NIVEL_4
      ,T.DSC_MOTIVO_ATEND_NIVEL_5 
      ,NVL(DMO.DSC_CATEGORIA,'-3') 
       ,NVL(DMO.DSC_FUNCIONALIDADE,'-3')     



/*

SELECT DISTINCT
       DAT_INICIO_ATENDIMENTO
       ,DSC_CATEGORIA
       ,ID_FUNCIONALIDADE
       ,DSC_FUNCIONALIDADE
      -- ,FC_APP_SITE
      -- ,FC_MOTIVO_AUTOM
      ,COUNT(NUM_NTC) QT_NTC
FROM ATEND_FECHADO_P3 
GROUP BY DAT_INICIO_ATENDIMENTO
       ,DSC_CATEGORIA
       ,ID_FUNCIONALIDADE
       ,DSC_FUNCIONALIDADE
      -- ,FC_APP_SITE
      -- ,FC_MOTIVO_AUTOM
              
  ;*/


/*--===========================================================================================================================
	ABAIXO O MODELO 2 DE MOTIVOS
		
--===========================================================================================================================*/






DROP TABLE TMP_SQDAA_MOT_RET_P1;
CREATE TABLE TMP_SQDAA_MOT_RET_P1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*PARALLEL (32) */
 * 
FROM BI_FT_RET_DIG_WHATSAPP W
WHERE W.SAFRA = &SAFRA
      AND W.DSC_VISAO_ANALISE = 'ACESSOU E LIGOU' 
      AND W.DSC_SAFRA = 'D 0'
;

DROP TABLE TMP_SQDAA_MOT_RET_P2;
CREATE TABLE TMP_SQDAA_MOT_RET_P2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*PARALLEL (32) */
        T.NUM_NTC
        ,T.DAT_INICIO_ATENDIMENTO
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO), 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000')) AS SK_LIGA 
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO)+1, 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000')) AS SK_LIGA1
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO)+2, 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000')) AS SK_LIGA2
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO)+3, 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000')) AS SK_LIGA3
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO)+7, 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000')) AS SK_LIGA7        
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(LAST_DAY(T.DAT_INICIO_ATENDIMENTO), 'RRRRMMDD') ||' '||'235959') AS SK_LIGA30
        ,TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO), 'RRRRMMDD') AS SK_DATA
        ,T.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO
        ,T.DW_MOTIVO_ATENDIMENTO
        ,regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_1,'00000')||
                        TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_2,'00000'),'[[:space:]]*','')|| 
               (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_3 = -3 THEN '00000' 
                     ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_3,'00000'),'[[:space:]]*',''))END)||         
               (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_4 = -3 THEN '00000' 
                     ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_4,'00000'),'[[:space:]]*',''))END)||
                (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_5 = -3 THEN '00000' 
                      ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_5,'00000'),'[[:space:]]*',''))END)
                           AS ID_MOTIVOS_TUPLA
         ,M.DSC_MOTIVO_ATEND_NIVEL_1         
         ,M.DSC_MOTIVO_ATEND_NIVEL_2
         ,M.DSC_MOTIVO_ATEND_NIVEL_3
         ,M.DSC_MOTIVO_ATEND_NIVEL_4
         ,M.DSC_MOTIVO_ATEND_NIVEL_5
--SELECT *                 
FROM BI_FP_ASSINANTE_ATEND_FECHADO T
INNER JOIN TMP_SQDAA_MOT_RET_P1 W
      ON T.NUM_NTC = W.NUM_NTC
      AND TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO), 'RRRRMMDD') = W.SK_DATA

LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
     ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC
     ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
      AND MC.DW_METODO_CONTATO IN (83,37,25,45,42,621,551) --- SOMENTE METODOS QUE RECEBE LIGAÇÃO NO PS8
--      AND MC.DW_METODO_CONTATO NOT IN (81, 411, 451,552,681,701,781,791) --EXPURGO WEB SITES E APP    
GROUP BY 
         T.NUM_NTC
         ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO), 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000')) 
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO)+1, 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000'))
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO)+2, 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000'))
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO)+3, 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000'))
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO)+7, 'RRRRMMDD') ||' '||TO_CHAR(T.HOR_INICIO_ATENDIMENTO,'000000'))
        ,T.DAT_INICIO_ATENDIMENTO
        ,T.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO
        ,T.DW_MOTIVO_ATENDIMENTO
        ,regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_1,'00000')||
                        TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_2,'00000'),'[[:space:]]*','')|| 
               (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_3 = -3 THEN '00000' 
                     ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_3,'00000'),'[[:space:]]*',''))END)||         
               (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_4 = -3 THEN '00000' 
                     ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_4,'00000'),'[[:space:]]*',''))END)||
                (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_5 = -3 THEN '00000' 
                      ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_5,'00000'),'[[:space:]]*',''))END)
        ,M.DSC_MOTIVO_ATEND_NIVEL_1         
         ,M.DSC_MOTIVO_ATEND_NIVEL_2
         ,M.DSC_MOTIVO_ATEND_NIVEL_3
         ,M.DSC_MOTIVO_ATEND_NIVEL_4
         ,M.DSC_MOTIVO_ATEND_NIVEL_5
;

SELECT  
      &SAFRA AS SAFRA
       ,NVL(DMO.DSC_FUNCIONALIDADE,'-3') AS DSC_FUNCIONALIDADE
       ,NVL(DMO.DSC_CATEGORIA,'-3') AS DSC_CATEGORIA 
       ,COUNT(DISTINCT(T.SK_LIGA)) AS QT_LIGAÇÕES
       ,COUNT(DISTINCT(T.NUM_NTC)) AS QT_USUARIOS               
FROM TMP_SQDAA_MOT_RET_P2 T
LEFT JOIN TMP_SQDAA_DIM_MOT_CMV DMO
     ON T.ID_MOTIVOS_TUPLA = DMO.ID_MOTIVOS_TUPLA