---======================== CRIAÇÃO DE TABELAS DE/PARA MOTIVOS PS8
CREATE TABLE U92277452.SQDAA_DIM_MOT_CMV
(
ID_MOTIVOS_TUPLA   CHAR(25) PRIMARY KEY,
DSC_MOVITOS_TUPLA   VARCHAR2(200) NOT NULL,
ID_FUNCIONALIDADE  NUMBER(10) NOT NULL,
DSC_FUNCIONALIDADE  CHAR(100) NOT NULL,
DSC_CATEGORIA    CHAR(50) NOT NULL,
FC_APP_SITE      NUMBER(2) NOT NULL,
FC_ATH        NUMBER(2) NOT NULL,
FC_URA        NUMBER(2) NOT NULL,
FC_MOTIVO_AUTOM    NUMBER(2) NOT NULL,
DT_CARGA      DATE DEFAULT (sysdate)
)
INDEX (ID_FUNCIONALIDADE ASC, ID_MOTIVOS_TUPLA ASC)
COMMENT ON TABLE U92277452.SQDAA_DIM_MOT_CMV IS 'Classificação Motivos PS8 CMV';


CREATE TABLE U92277452.SQDAA_DIM_FUNC_CMV
(
ID_FUNCIONALIDADE NUMBER(10),
DSC_FUNCIONALIDADE VARCHAR2 (100),  
DSC_CATEGORIA VARCHAR2 (50),
INDEX (ID_FUNCIONALIDADE ASC)
);
COMMENT ON TABLE U92277452.SQDAA_DIM_FUNC_CMV IS 'Classificação Funcionalidades Motivos PS8 CMV';
--==========================================================================================================================


ACESSOS_MINHA AS 

(SELECT DISTINCT /*+ PARALLEL (32)*/
       TO_NUMBER(TO_CHAR(DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')) SK_DATA
--     ,MIN(TO_NUMBER(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD'))) SK_DATA_MIN
       ,NUM_NTC
       
FROM DWH.BI_FP_ASSINANTE_ATEND_FECHADO@BASECLARO  

WHERE DW_METODO_CONTATO IN (81, 411, 451,701,552)                                               ---EXPURDO 681 APP_FLEX
      AND UPPER(DSC_OBSERVACAO_ATENDIMENTO) LIKE '%MINHACLAROWEB%AUTENTICA%USU%'
      AND DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')

GROUP BY 
       TO_NUMBER(TO_CHAR(DAT_INICIO_ATENDIMENTO, 'RRRRMMDD'))
      ,NUM_NTC
)

--===========================================================================================================================
SELECT /*PARALLEL (8) */
        MC.DW_METODO_CONTATO,
        MC.DSC_METODO_CONTATO AS METODO_CONTATO,
        M.COD_MOTIVO_ATEND_NIVEL_1,
        M.DSC_MOTIVO_ATEND_NIVEL_1,
        M.COD_MOTIVO_ATEND_NIVEL_2,
        M.DSC_MOTIVO_ATEND_NIVEL_2,
        M.COD_MOTIVO_ATEND_NIVEL_3,
        M.DSC_MOTIVO_ATEND_NIVEL_3,
        M.COD_MOTIVO_ATEND_NIVEL_4,
        M.DSC_MOTIVO_ATEND_NIVEL_4,
        M.COD_MOTIVO_ATEND_NIVEL_5,
        M.DSC_MOTIVO_ATEND_NIVEL_5,
        COUNT (*) AS QTDE_PROCT
---select *
FROM BI_FP_ASSINANTE_ATEND_FECHADO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC
ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND MC.DW_METODO_CONTATO IN (81, 411, 451,681,701,552)
GROUP BY 
        MC.DW_METODO_CONTATO,
        MC.DSC_METODO_CONTATO,
        M.COD_MOTIVO_ATEND_NIVEL_1,
        M.DSC_MOTIVO_ATEND_NIVEL_1,
        M.COD_MOTIVO_ATEND_NIVEL_2,
        M.DSC_MOTIVO_ATEND_NIVEL_2,
        M.COD_MOTIVO_ATEND_NIVEL_3,
        M.DSC_MOTIVO_ATEND_NIVEL_3,
        M.COD_MOTIVO_ATEND_NIVEL_4,
        M.DSC_MOTIVO_ATEND_NIVEL_4,
        M.COD_MOTIVO_ATEND_NIVEL_5,
        M.DSC_MOTIVO_ATEND_NIVEL_5

--===========================================================================================================================


SELECT * FROM ALL_ALL_TABLES WHERE OWNER LIKE '%U92277452%'

---TABELAS MOTIVOS PS8 & RETIDO DIGITAL
select * from U92277452.TMP_SQDAA_DIM_FUNC_CMV;
SELECT * FROM U92277452.TMP_SQDAA_DIM_MOT_CMV;

---TABELAS COMPORTAMENTO DE ACESSO
SELECT * FROM U92277452.BUS_SQD_AA_BASE_CAD_CMV_AGG
SELECT * FROM U92277452.BUS_SQD_AA_BASE_CAD_CMV_DTL

SELECT DISTINCT A.DSC_VISAO_ANALISE FROM U92277452.TMP_SQDAA_RET_DIG_03A A   
--- (não retido d=0) TABELA INICIAL COM OS MOTIVOS "FLG_LIG_ACESSA = 0"
SELECT * FROM U92277452.TMP_SQDAA_RET_DIG_03B;  --- retido LIG_0/LIG_1/ATEND_0/ATEND_1 "FLG_LIG_ACESSA = 0"
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03C;  --- retido digital ate 2 dias flag "FLG_LIG_ACESSA = 0"
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03D;  --- retido digital ate 3 dias flag "FLG_LIG_ACESSA = 0"
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03E;  --- retido digital ate 7 dias flag "FLG_LIG_ACESSA = 0"

SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03A@BASECLARO; ---WHERE FLG_LIG_ACESSA = 0;
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03B@BASECLARO;
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03c@BASECLARO;
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03D@BASECLARO;
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03E@BASECLARO;

--===========================================================================================================================
--                        CONSULTA NO ATENDIMENTO FECHAMDO DE SET.19 
--                                         VS
--                                 MOTIVOS CLASSIFICADOS 
--===========================================================================================================================

WITH ATEND_FECHADO AS (

SELECT /*PARALLEL (32) */
        T.NUM_NTC
        ,T.DAT_INICIO_ATENDIMENTO
        ,T.DW_METODO_CONTATO
        ,T.DW_MOTIVO_ATENDIMENTO
        ,regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_1,'00000')||
                        TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_2,'00000')|| 
                        TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_3,'00000'),'[[:space:]]*','')||
               (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_4 = -3 THEN '00000' 
                     ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_4,'00000'),'[[:space:]]*',''))END)||
                (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_5 = -3 THEN '00000' 
                      ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_5,'00000'),'[[:space:]]*',''))END) 
                           AS ID_MOTIVOS_TUPLA
---SELECT *                  
FROM BI_FP_ASSINANTE_ATEND_FECHADO@BASECLARO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO@BASECLARO M
     ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO@BASECLARO MC
     ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
      AND MC.DW_METODO_CONTATO IN (81, 411, 451,701) --EXPURGO 681 FLEX, 552 Minha Claro Empresa
--and UPPER(t.DSC_OBSERVACAO_ATENDIMENTO) LIKE '%MINHACLAROWEB%AUTENTICA%USU%'        
---AND T.NUM_NTC = '67991820001'
GROUP BY 
         T.NUM_NTC
        ,T.DAT_INICIO_ATENDIMENTO
        ,T.DW_METODO_CONTATO
        ,T.DW_MOTIVO_ATENDIMENTO
    ,regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_1,'00000')||
                        TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_2,'00000')|| 
                        TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_3,'00000'),'[[:space:]]*','')||
               (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_4 = -3 THEN '00000' 
                     ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_4,'00000'),'[[:space:]]*',''))END)||
                (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_5 = -3 THEN '00000' 
                      ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_5,'00000'),'[[:space:]]*',''))END) 
                           
),

ATEND_FECHADO2 AS (
SELECT  
      T.NUM_NTC
        ,T.DAT_INICIO_ATENDIMENTO
        ,T.DW_METODO_CONTATO
        ,T.DW_MOTIVO_ATENDIMENTO
       ,DMO.ID_FUNCIONALIDADE
       ,DMO.DSC_FUNCIONALIDADE
       ,DMO.DSC_CATEGORIA
       ,DMO.FC_APP_SITE
       ,DMO.FC_MOTIVO_AUTOM               
FROM ATEND_FECHADO T
LEFT JOIN U92277452.TMP_SQDAA_DIM_MOT_CMV@BASECLARO DMO
     ON T.ID_MOTIVOS_TUPLA = DMO.ID_MOTIVOS_TUPLA

   
          
GROUP BY T.NUM_NTC
        ,T.DAT_INICIO_ATENDIMENTO
        ,T.DW_METODO_CONTATO
        ,T.DW_MOTIVO_ATENDIMENTO
       ,DMO.ID_FUNCIONALIDADE 
       ,DMO.DSC_FUNCIONALIDADE
       ,DMO.DSC_CATEGORIA
       ,DMO.FC_APP_SITE
       ,DMO.FC_MOTIVO_AUTOM      
)

SELECT DISTINCT
       DAT_INICIO_ATENDIMENTO
       ,DSC_CATEGORIA
       ,ID_FUNCIONALIDADE
       ,DSC_FUNCIONALIDADE
      -- ,FC_APP_SITE
      -- ,FC_MOTIVO_AUTOM
      ,COUNT(NUM_NTC) QT_NTC
FROM ATEND_FECHADO2 
GROUP BY DAT_INICIO_ATENDIMENTO
       ,DSC_CATEGORIA
       ,ID_FUNCIONALIDADE
       ,DSC_FUNCIONALIDADE
      -- ,FC_APP_SITE
      -- ,FC_MOTIVO_AUTOM
              
  ;
 --===========================================================================================================================
--                                 VISÃO 2.: MARCANDO BASE DE MOTIVOS
--                                 RETIDO DIGITAL DIA  (DEZ.19)
--                                         VS
--                                 MOTIVOS CLASSIFICADOS 
-- RESSALVAS:
-- RETIDO DIGITAL CONSTA PARA TODOS OS PRODUTOS CLARO (CONTROLE/PRE PAGO/FLEX...)
-- DSC_VISAO_ANALISE = 'RETIDO DIGITAL' ---SOMENTE RETIDO DIGITAL 
--===========================================================================================================================
---SELECT /*PARALLEL (32) */ * FROM U92277452.BI_FT_SQDAA_RET_DIG;

WITH 
       RETIDO1 AS (
         SELECT DISTINCT /*PARALLEL (32) */
              SUBSTR(TO_CHAR(SK_DATA),1,6) AS SAFRA
              ,R.SK_DATA
              ,R.NUM_NTC
              ,COUNT (DISTINCT R.NUM_NTC || TO_CHAR(R.DAT_INI_ATENDIMENTO,'RRRRMMDD HH24MISS'))  AS QTD_ACESSOS
             --- SELECT /*PARALLEL (32) */ *                          
              FROM U92277452.BI_FT_SQDAA_RET_DIG R
              WHERE R.DAT_INI_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
                  AND R.DSC_VISAO_ANALISE = 'RETIDO DIGITAL' ---SOMENTE RETIDO DIGITAL
                  AND R.DSC_SAFRA = 'D 0' --- SOMENTE RETIDO NO DIA
                    GROUP BY 
                             SUBSTR(TO_CHAR(R.SK_DATA),1,6)
                            ,R.SK_DATA
                            ,R.NUM_NTC
),                                                
       RETIDO2 AS (
       SELECT DISTINCT  
             R1.SAFRA
             ,R1.SK_DATA
             ,R1.NUM_NTC
             ,regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_1,'00000')||
                                  TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_2,'00000')|| 
                                  TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_3,'00000'),'[[:space:]]*','')||
                         (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_4 = -3 THEN '00000' 
                               ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_4,'00000'),'[[:space:]]*',''))END)||
                          (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_5 = -3 THEN '00000' 
                                ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_5,'00000'),'[[:space:]]*',''))END) 
                                     AS ID_MOTIVOS_TUPLA
                  ,1 AS QT_TRANSACAO
                               
          FROM RETIDO1 R1
          LEFT JOIN BI_FP_ASSINANTE_ATEND_FECHADO T
               ON R1.NUM_NTC = T.NUM_NTC
               AND R1.SK_DATA = TO_CHAR(T.DAT_INICIO_ATENDIMENTO,'RRRRMMDD')
          LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
               ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
          LEFT JOIN BI_DIM_METODO_CONTATO MC
               ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
          
          WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')  
                AND MC.DW_METODO_CONTATO IN (81, 411, 451,701) --EXPURGO 681 FLEX, 552 Minha Claro Empresa
          GROUP BY 
                 R1.SAFRA
                 ,R1.SK_DATA
                 ,R1.NUM_NTC
                 ,regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_1,'00000')||
                                  TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_2,'00000')|| 
                                  TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_3,'00000'),'[[:space:]]*','')||
                         (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_4 = -3 THEN '00000' 
                               ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_4,'00000'),'[[:space:]]*',''))END)||
                          (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_5 = -3 THEN '00000' 
                                ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_5,'00000'),'[[:space:]]*',''))END)
ORDER BY R1.NUM_NTC ,R1.SK_DATA            
)---,
      ---RETIDO3 AS( -- TABELAS COM TODOS OS MOTIVOS
            SELECT DISTINCT
                    R2.SAFRA
                    ,R2.SK_DATA
                    ,R2.NUM_NTC
                    ,R2.ID_MOTIVOS_TUPLA
                    ,MOT.DSC_MOVITOS_TUPLA 
                    ,MOT.ID_FUNCIONALIDADE 
                    ,MOT.DSC_FUNCIONALIDADE
            FROM RETIDO2 R2 --TABELA COM OS CLIENTES RETIDOS: "ID_MOTIVOS_TUPLA"  
            LEFT JOIN  U92277452.TMP_SQDAA_DIM_MOT_CMV MOT -- TABELA DE MOTIVOS: "ID_MOTIVOS_TUPLA + DESCRICAO"
                 ON R2.ID_MOTIVOS_TUPLA = MOT.ID_MOTIVOS_TUPLA
            GROUP BY 
                    R2.SAFRA
                    ,R2.SK_DATA
                    ,R2.NUM_NTC
                    ,R2.ID_MOTIVOS_TUPLA
                    ,MOT.DSC_MOVITOS_TUPLA 
                    ,MOT.ID_FUNCIONALIDADE 
                    ,MOT.DSC_FUNCIONALIDADE
            ORDER BY R2.NUM_NTC ,R2.SK_DATA          
),
        RETIDO4 AS ( ---CLIENTES QUE GERAM 1 ANTEDIMENTO E OUTROS MOTIVOS
              SELECT DISTINCT
                      R3.SK_DATA
                      ,R3.NUM_NTC                        
              FROM RETIDO3 R3 WHERE R3.ID_FUNCIONALIDADE <> 8
              GROUP BY R3.SK_DATA ,R3.NUM_NTC
              ORDER BY R3.NUM_NTC ,R3.SK_DATA
),

---SELECT COUNT(DISTINCT(R4.NUM_NTC)) QT_USUARIOS_UNICOS FROM RETIDO4; 
        RETIDO5 AS ( -- TABELA DE CLIENTES CONSIDERANDO TODOS OS MOTIVOS EXCETO "ATENDIMENTO"/DASH
              SELECT 
                  R4.SK_DATA
                  ,R4.NUM_NTC
                  ,R3.ID_FUNCIONALIDADE
                  ,R3.DSC_FUNCIONALIDADE
                  ,COUNT(*) AS QT_FUNCIONALIDADE            
              FROM RETIDO4 R4
              INNER JOIN RETIDO3 R3
                  ON R3.SK_DATA = R4.SK_DATA
                  AND R3.NUM_NTC = R4.NUM_NTC
              WHERE R3.ID_FUNCIONALIDADE NOT IN 8
              GROUP BY 
                  R4.SK_DATA
                  ,R4.NUM_NTC
                  ,R3.ID_FUNCIONALIDADE
                  ,R3.DSC_FUNCIONALIDADE
),
        RETIDO6 AS (
            SELECT R3.SAFRA
                   ,R3.SK_DATA
                   ,R3.NUM_NTC
                   ,R3.ID_MOTIVOS_TUPLA
                   ,R3.DSC_MOVITOS_TUPLA
                   ,R3.ID_FUNCIONALIDADE
                   ,R3.DSC_FUNCIONALIDADE
            FROM RETIDO3 R3 -- COMPLETO COM TODOS OS MOTIVOS
            LEFT JOIN RETIDO4 R4 ---CLIENTES QUE GERAM 1 ANTEDIMENTO E OUTROS MOTIVOS
                  ON R3.SK_DATA = R4.SK_DATA
                  AND R3.NUM_NTC = R4.NUM_NTC
            WHERE R4.NUM_NTC IS NULL
            GROUP BY R3.SAFRA
                   ,R3.SK_DATA
                   ,R3.NUM_NTC
                   ,R3.ID_MOTIVOS_TUPLA
                   ,R3.DSC_MOVITOS_TUPLA
                   ,R3.ID_FUNCIONALIDADE
                   ,R3.DSC_FUNCIONALIDADE
)
/*SELECT ---retidos no dash 10.124.667 ACESSOS E 3.642.670 CLIENTES ÚNICOS
       R6.ID_FUNCIONALIDADE
       ,COUNT(DISTINCT(R6.SK_DATA || R6.NUM_NTC)) AS QT_ACESSOS
       ,COUNT(DISTINCT(R6.NUM_NTC)) AS QT_CLI_UNICOS 
FROM RETIDO6 R6
     GROUP BY R6.ID_FUNCIONALIDADE           
;*/
/*SELECT DISTINCT --retidos fora do dash 
       R5.SK_DATA
       ,R5.ID_FUNCIONALIDADE
       ,R5.DSC_FUNCIONALIDADE
       ,SUM(R5.QT_FUNCIONALIDADE) AS QT_FUNCIONALIDADE
       ,COUNT(DISTINCT(R5.SK_DATA || R5.NUM_NTC)) AS QT_ACESSOS
       
FROM RETIDO5 R5
GROUP BY 
        R5.SK_DATA
       ,R5.ID_FUNCIONALIDADE
       ,R5.DSC_FUNCIONALIDADE;*/

/*SELECT R3.*            
FROM RETIDO4 R4
INNER JOIN RETIDO3 R3
      ON R3.SK_DATA = R4.SK_DATA
      AND R3.NUM_NTC = R4.NUM_NTC
WHERE R3.NUM_NTC IN ('21968944097','68992086245', '68992223246' ) --- CLIENTES QUE EXECUTARAM MAIS DE UMA FUNCIONALIDADE NO DIA 01/12/2019*/

 --===========================================================================================================================
--                                 VISÃO 3.: MARCANDO TIPO DE PLANO E PRODUTO
--                                 RETIDO DIGITAL DIA  (DEZ.19)
--                                         VS
--                                 MOTIVOS CLASSIFICADOS 
-- RESSALVAS:
-- RETIDO DIGITAL CONSTA PARA TODOS OS PRODUTOS CLARO (CONTROLE/PRE PAGO/FLEX...)
-- DSC_VISAO_ANALISE = 'RETIDO DIGITAL' ---SOMENTE RETIDO DIGITAL
--===========================================================================================================================

SELECT /* PARALLEL (32)*/ * FROM BI_FP_ASS_ULT_MUDANCA;
SELECT DISTINCT/* PARALLEL (32)*/ 
       
       BMD.COD_PLATAFORMA_ATU
       ,COUNT(DISTINCT(R.NUM_NTC)) AS QT_CLIENTES_UNICOS
       
FROM U92277452.BI_FT_SQDAA_RET_DIG R 
LEFT JOIN BI_FP_ASS_ULT_MUDANCA BMD
ON R.NUM_NTC = BMD.NUM_NTC

       WHERE R.DAT_INI_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
                  AND R.DSC_VISAO_ANALISE = 'RETIDO DIGITAL' ---SOMENTE RETIDO DIGITAL
                  AND R.DSC_SAFRA = 'D 0' --- SOMENTE RETIDO NO DIA
---                  AND R.NUM_NTC = '66999251313'
        GROUP BY BMD.COD_PLATAFORMA_ATU
       --ORDER BY R.NUM_NTC ,R.DAT_INI_ATENDIMENTO
       ;
SELECT /*PARALELL (32)*/ * FROM BI_FP_ASS_ULT_MUDANCA BMU WHERE BMU.NUM_NTC = '66999251313';
SELECT /*PARALELL (32)*/ * FROM DM_HIS_ASSINANTE_FAT;


--===========================================================================================================================
--                                 VISÃO 1.: ACESSO POR CANAL EXCLUINDO CANAL DIGITAL
-- JAN.2020 22.245.373 TRANSAÇÕES DE CADA CANAL POR NTC                                 
-- 
--===========================================================================================================================
SELECT DISTINCT /*PARALLEL (8) */ 
        T.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO AS METODO_CONTATO
        ,COUNT(DISTINCT(T.NUM_NTC)) QT_CLI_UNICOS
        ,COUNT (*) AS QTDE_PROCT
     
FROM BI_FP_ASSINANTE_ATEND_FECHADO T
--LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
--ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC
ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
   --   AND UPPER(t.DSC_OBSERVACAO_ATENDIMENTO) NOT IN '%MINHACLAROWEB%AUTENTICA%USU%' 
      AND MC.DW_METODO_CONTATO NOT IN (81, 411, 451,681,701,552) ----excluindo os metodos app/site
GROUP BY T.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO;
        
--===========================================================================================================================
--                                 VISÃO 2.: ACESSO POR CANAL EXCLUINDO CANAL DIGITAL
-- JAN.2020 22.245.373 TRANSAÇÕES DE CADA CANAL POR NTC                                 
-- 
--===========================================================================================================================

SELECT DISTINCT /*PARALLEL (8) */ 
        T.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO
        ,M.COD_MOTIVO_ATEND_NIVEL_1
        ,M.DSC_MOTIVO_ATEND_NIVEL_1
        ,M.COD_MOTIVO_ATEND_NIVEL_2
        ,M.DSC_MOTIVO_ATEND_NIVEL_2
        ,M.COD_MOTIVO_ATEND_NIVEL_3
        ,M.DSC_MOTIVO_ATEND_NIVEL_3
        ,M.COD_MOTIVO_ATEND_NIVEL_4
        ,M.DSC_MOTIVO_ATEND_NIVEL_4
        ,M.COD_MOTIVO_ATEND_NIVEL_5
        ,M.DSC_MOTIVO_ATEND_NIVEL_5
        ,COUNT (*) AS QTDE_PROCT
FROM BI_FP_ASSINANTE_ATEND_FECHADO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC
ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
   --   AND UPPER(t.DSC_OBSERVACAO_ATENDIMENTO) NOT IN '%MINHACLAROWEB%AUTENTICA%USU%' 
      AND MC.DW_METODO_CONTATO IN (37, 25, 45,83) ---- Telefonema Recebido + Cobrança + Retenção + URA

GROUP BY T.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO
        ,M.COD_MOTIVO_ATEND_NIVEL_1
        ,M.DSC_MOTIVO_ATEND_NIVEL_1
        ,M.COD_MOTIVO_ATEND_NIVEL_2
        ,M.DSC_MOTIVO_ATEND_NIVEL_2
        ,M.COD_MOTIVO_ATEND_NIVEL_3
        ,M.DSC_MOTIVO_ATEND_NIVEL_3
        ,M.COD_MOTIVO_ATEND_NIVEL_4
        ,M.DSC_MOTIVO_ATEND_NIVEL_4
        ,M.COD_MOTIVO_ATEND_NIVEL_5
        ,M.DSC_MOTIVO_ATEND_NIVEL_5;

--===========================================================================================================================
--                                 VISÃO 2.: CANAL ATH
--                                 
-- 
--===========================================================================================================================
SELECT DISTINCT /*PARALLEL (8) */ 
        T.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO AS METODO_CONTATO
       
     
FROM BI_FP_ASSINANTE_ATEND_FECHADO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
     ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC
     ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
   --   AND UPPER(t.DSC_OBSERVACAO_ATENDIMENTO) NOT IN '%MINHACLAROWEB%AUTENTICA%USU%' 
      AND MC.DW_METODO_CONTATO NOT IN (81, 411, 451,681,701,552)
GROUP BY T.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO;





SELECT * FROM ALL_ALL_TABLES WHERE OWNER LIKE '%U92277452%'
--TMP_SQD_AA_APP_ACC TMP_SQDAA_RET_DIG_01A MP_SQDAA_RET_DIG_01B

SELECT DISTINCT DSC_METODO_CONTATO
        
FROM BI_FP_ASSINANTE_ATEND_FECHADO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC
ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')




SELECT /*PARALLEL (8) */
        MC.DW_METODO_CONTATO,
        MC.DSC_METODO_CONTATO AS METODO_CONTATO,
        M.COD_MOTIVO_ATEND_NIVEL_1,
        M.DSC_MOTIVO_ATEND_NIVEL_1,
        M.COD_MOTIVO_ATEND_NIVEL_2,
        M.DSC_MOTIVO_ATEND_NIVEL_2,
        M.COD_MOTIVO_ATEND_NIVEL_3,
        M.DSC_MOTIVO_ATEND_NIVEL_3,
        M.COD_MOTIVO_ATEND_NIVEL_4,
        M.DSC_MOTIVO_ATEND_NIVEL_4,
        M.COD_MOTIVO_ATEND_NIVEL_5,
        M.DSC_MOTIVO_ATEND_NIVEL_5,
        COUNT (*) AS QTDE_PROCT
---select *
FROM BI_FP_ASSINANTE_ATEND_FECHADO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC
ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
UPPER(A.DSC_OBSERVACAO_ATENDIMENTO) LIKE '%MINHACLAROWEB%AUTENTICA%USU%'

---AND MC.DW_METODO_CONTATO IN (81, 411, 451,681,701,552)
GROUP BY 
        MC.DW_METODO_CONTATO,
        MC.DSC_METODO_CONTATO,
        M.COD_MOTIVO_ATEND_NIVEL_1,
        M.DSC_MOTIVO_ATEND_NIVEL_1,
        M.COD_MOTIVO_ATEND_NIVEL_2,
        M.DSC_MOTIVO_ATEND_NIVEL_2,
        M.COD_MOTIVO_ATEND_NIVEL_3,
        M.DSC_MOTIVO_ATEND_NIVEL_3,
        M.COD_MOTIVO_ATEND_NIVEL_4,
        M.DSC_MOTIVO_ATEND_NIVEL_4,
        M.COD_MOTIVO_ATEND_NIVEL_5,
        M.DSC_MOTIVO_ATEND_NIVEL_5


SELECT SUBSTR(TO_CHAR(R.DAT_REFERENCIA),1,6) AS FROM U92277452.BI_AGG_SQDAA_RET_DIG R;
---======================== CRIAÇÃO DE TABELAS DE/PARA MOTIVOS PS8
CREATE TABLE U92277452.SQDAA_DIM_MOT_CMV
(
ID_MOTIVOS_TUPLA   CHAR(25) PRIMARY KEY,
DSC_MOVITOS_TUPLA   VARCHAR2(200) NOT NULL,
ID_FUNCIONALIDADE  NUMBER(10) NOT NULL,
DSC_FUNCIONALIDADE  CHAR(100) NOT NULL,
DSC_CATEGORIA    CHAR(50) NOT NULL,
FC_APP_SITE      NUMBER(2) NOT NULL,
FC_ATH        NUMBER(2) NOT NULL,
FC_URA        NUMBER(2) NOT NULL,
FC_MOTIVO_AUTOM    NUMBER(2) NOT NULL,
DT_CARGA      DATE DEFAULT (sysdate)
)
INDEX (ID_FUNCIONALIDADE ASC, ID_MOTIVOS_TUPLA ASC)
COMMENT ON TABLE U92277452.SQDAA_DIM_MOT_CMV IS 'Classificação Motivos PS8 CMV';


CREATE TABLE U92277452.SQDAA_DIM_FUNC_CMV
(
ID_FUNCIONALIDADE NUMBER(10),
DSC_FUNCIONALIDADE VARCHAR2 (100),	
DSC_CATEGORIA VARCHAR2 (50),
INDEX (ID_FUNCIONALIDADE ASC)
);
COMMENT ON TABLE U92277452.SQDAA_DIM_FUNC_CMV IS 'Classificação Funcionalidades Motivos PS8 CMV';
--==========================================================================================================================


ACESSOS_MINHA AS 

(SELECT DISTINCT /*+ PARALLEL (32)*/
       TO_NUMBER(TO_CHAR(DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')) SK_DATA
--     ,MIN(TO_NUMBER(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD'))) SK_DATA_MIN
       ,NUM_NTC
       
FROM DWH.BI_FP_ASSINANTE_ATEND_FECHADO@BASECLARO  

WHERE DW_METODO_CONTATO IN (81, 411, 451,701,552)                                               ---EXPURDO 681 APP_FLEX
      AND UPPER(DSC_OBSERVACAO_ATENDIMENTO) LIKE '%MINHACLAROWEB%AUTENTICA%USU%'
      AND DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')

GROUP BY 
       TO_NUMBER(TO_CHAR(DAT_INICIO_ATENDIMENTO, 'RRRRMMDD'))
      ,NUM_NTC
)

--===========================================================================================================================
SELECT /*PARALLEL (8) */
        MC.DW_METODO_CONTATO,
        MC.DSC_METODO_CONTATO AS METODO_CONTATO,
        M.COD_MOTIVO_ATEND_NIVEL_1,
        M.DSC_MOTIVO_ATEND_NIVEL_1,
        M.COD_MOTIVO_ATEND_NIVEL_2,
        M.DSC_MOTIVO_ATEND_NIVEL_2,
        M.COD_MOTIVO_ATEND_NIVEL_3,
        M.DSC_MOTIVO_ATEND_NIVEL_3,
        M.COD_MOTIVO_ATEND_NIVEL_4,
        M.DSC_MOTIVO_ATEND_NIVEL_4,
        M.COD_MOTIVO_ATEND_NIVEL_5,
        M.DSC_MOTIVO_ATEND_NIVEL_5,
        COUNT (*) AS QTDE_PROCT
FROM BI_FP_ASSINANTE_ATEND_FECHADO@BASECLARO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO@BASECLARO M
ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO@BASECLARO MC
ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND MC.DW_METODO_CONTATO IN (81, 411, 451,681,701,552)
GROUP BY 
        MC.DW_METODO_CONTATO,
        MC.DSC_METODO_CONTATO,
        M.COD_MOTIVO_ATEND_NIVEL_1,
        M.DSC_MOTIVO_ATEND_NIVEL_1,
        M.COD_MOTIVO_ATEND_NIVEL_2,
        M.DSC_MOTIVO_ATEND_NIVEL_2,
        M.COD_MOTIVO_ATEND_NIVEL_3,
        M.DSC_MOTIVO_ATEND_NIVEL_3,
        M.COD_MOTIVO_ATEND_NIVEL_4,
        M.DSC_MOTIVO_ATEND_NIVEL_4,
        M.COD_MOTIVO_ATEND_NIVEL_5,
        M.DSC_MOTIVO_ATEND_NIVEL_5

--===========================================================================================================================


SELECT * FROM ALL_ALL_TABLES WHERE OWNER LIKE '%U92277452%'

---TABELAS MOTIVOS PS8 & RETIDO DIGITAL
select * from U92277452.TMP_SQDAA_DIM_FUNC_CMV
SELECT * FROM U92277452.TMP_SQDAA_DIM_MOT_CMV



---TABELAS COMPORTAMENTO DE ACESSO
SELECT * FROM U92277452.BUS_SQD_AA_BASE_CAD_CMV_AGG
SELECT * FROM U92277452.BUS_SQD_AA_BASE_CAD_CMV_DTL

SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03A;  --- (não retido d=0) TABELA INICIAL COM OS MOTIVOS "FLG_LIG_ACESSA = 0"
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03B;  --- retido LIG_0/LIG_1/ATEND_0/ATEND_1 "FLG_LIG_ACESSA = 0"
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03C;  --- retido digital ate 2 dias flag "FLG_LIG_ACESSA = 0"
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03D;  --- retido digital ate 3 dias flag "FLG_LIG_ACESSA = 0"
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03E;  --- retido digital ate 7 dias flag "FLG_LIG_ACESSA = 0"

SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03A@BASECLARO;
---WHERE FLG_LIG_ACESSA = 0;
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03B@BASECLARO;
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03c@BASECLARO;
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03D@BASECLARO;
SELECT * FROM U92277452.TMP_SQDAA_RETIDO_DIG_03E@BASECLARO;
-- CONSULTA MOTIVOS E RETIDO

SELECT 



---------------------------------------------------------------------------------------------------------------------

SELECT /*PARALLEL (8) */
        MC.DW_METODO_CONTATO,
        MC.DSC_METODO_CONTATO AS METODO_CONTATO,
        M.COD_MOTIVO_ATEND_NIVEL_1,
        M.DSC_MOTIVO_ATEND_NIVEL_1,
        M.COD_MOTIVO_ATEND_NIVEL_2,
        M.DSC_MOTIVO_ATEND_NIVEL_2,
        M.COD_MOTIVO_ATEND_NIVEL_3,
        M.DSC_MOTIVO_ATEND_NIVEL_3,
        M.COD_MOTIVO_ATEND_NIVEL_4,
        M.DSC_MOTIVO_ATEND_NIVEL_4,
        M.COD_MOTIVO_ATEND_NIVEL_5,
        M.DSC_MOTIVO_ATEND_NIVEL_5,
        COUNT (*) AS QTDE_PROCT
      
FROM BI_FP_ASSINANTE_ATEND_FECHADO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC
ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
--AND MC.DW_METODO_CONTATO IN (81, 411, 451,681,701,552)
GROUP BY 
        MC.DW_METODO_CONTATO,
        MC.DSC_METODO_CONTATO,
        M.COD_MOTIVO_ATEND_NIVEL_1,
        M.DSC_MOTIVO_ATEND_NIVEL_1,
        M.COD_MOTIVO_ATEND_NIVEL_2,
        M.DSC_MOTIVO_ATEND_NIVEL_2,
        M.COD_MOTIVO_ATEND_NIVEL_3,
        M.DSC_MOTIVO_ATEND_NIVEL_3,
        M.COD_MOTIVO_ATEND_NIVEL_4,
        M.DSC_MOTIVO_ATEND_NIVEL_4,
        M.COD_MOTIVO_ATEND_NIVEL_5,
        M.DSC_MOTIVO_ATEND_NIVEL_5
---------------------------------------------------------------------------------------------------------------------
SELECT /*PARALLEL (32) */
        T.NUM_NTC
        ,T.DAT_INICIO_ATENDIMENTO
        ,T.DW_METODO_CONTATO
        ,T.DW_MOTIVO_ATENDIMENTO
        ,((TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_1,'00000'))||
                (TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_2,'00000'))|| 
                (TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_3,'00000'))||
                (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_4 = -3 THEN '00000' 
                      ELSE (TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_4,'00000'))END)||
                (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_5 = -3 THEN '00000' 
                      ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_5,'00000'),'[[:space:]]*',''))END) AS ID_MOTIVOS_TUPLA
---SELECT *                  
FROM BI_FP_ASSINANTE_ATEND_FECHADO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
     ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC
     ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
      AND T.NUM_NTC = '67991820001'
GROUP BY 
         T.NUM_NTC
        ,T.DAT_INICIO_ATENDIMENTO
        ,T.DW_METODO_CONTATO
        ,T.DW_MOTIVO_ATENDIMENTO
       ,((TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_1,'00000'))||
                (TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_2,'00000'))|| 
                (TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_3,'00000'))||
                (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_4 = -3 THEN '00000' 
                      ELSE (TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_4,'00000'))END)||
                (CASE WHEN M.COD_MOTIVO_ATEND_NIVEL_5 = -3 THEN '00000' 
                      ELSE (regexp_replace(TO_CHAR(M.COD_MOTIVO_ATEND_NIVEL_5,'00000'),'[[:space:]]*',''))END);

   
