SELECT 
TIPO_OC,
SEGMENTACAO_DO_CLIENTE,
DT_OCORRENCIA,
CASE WHEN CIDADE
  IN ('SAO PEDRO DA ALDEIA','LAGES','ITANHAEM','PEDREIRA','CORONEL FABRICIANO','SERRANA','POUSO ALEGRE','JARAGUA DO SUL','MIRASSOL','TORRES','RIBEIRAO PIRES','SAO ROQUE','MONTENEGRO','SERRA NEGRA','PERUIBE','SOBRAL','TREMEMBE','CATANDUVA','PARANAGUA','DIVINOPOLIS','GRAMADO','APUCARANA','NOVA FRIBURGO','GUARAMIRIM','ROLANDIA','UBATUBA','AMPARO','RIO VERDE','IJUI','CABO FRIO','SAO SEBASTIAO','PRESIDENTE BERNARDES','BARRINHA','MONGAGUA','MONTES CLAROS','CANELA','TRES CORACOES','ARUJA','TIMÓTEO','CAIEIRAS','SÃO JOSE DO RIO PARDO','CARAZINHO','GUAIBA','ITAPIRA','ITATIBA','POCOS DE CALDAS','CARAGUATATUBA','CAMACARI','JAGUARIUNA',
'TATUI','LOUVEIRA','BIGUACU','PENAPOLIS','SAO JOAQUIM DA BARRA','ORLANDIA','IMPERATRIZ','BOITUVA','ARMACAO DOS BUZIOS','CAMBE','ITAJUBA','ARAGUARI','DRACENA')
THEN 'Sim'
  ELSE 'Não'
END AS GPON,
COUNT(*) QTD_OC
FROM INN.dw_ocorrencia_net
WHERE NM_STATUS_CONTRATO = 'CONECTADO'
AND DT_OCORRENCIA BETWEEN TO_DATE('01/07/2019','DD/MM/YYYY') AND TO_DATE('30/09/2019','DD/MM/YYYY')
AND TIPO_OC 
            IN (SELECT OC FROM U92277452.TMP_SQD_AA_OC@BASECLARO)
GROUP BY
TIPO_OC,
SEGMENTACAO_DO_CLIENTE,
DT_OCORRENCIA,
CASE WHEN CIDADE
  IN ('SAO PEDRO DA ALDEIA','LAGES','ITANHAEM','PEDREIRA','CORONEL FABRICIANO','SERRANA','POUSO ALEGRE','JARAGUA DO SUL','MIRASSOL','TORRES','RIBEIRAO PIRES','SAO ROQUE','MONTENEGRO','SERRA NEGRA','PERUIBE','SOBRAL','TREMEMBE','CATANDUVA','PARANAGUA','DIVINOPOLIS','GRAMADO','APUCARANA','NOVA FRIBURGO','GUARAMIRIM','ROLANDIA','UBATUBA','AMPARO','RIO VERDE','IJUI','CABO FRIO','SAO SEBASTIAO','PRESIDENTE BERNARDES','BARRINHA','MONGAGUA','MONTES CLAROS','CANELA','TRES CORACOES','ARUJA','TIMÓTEO','CAIEIRAS','SÃO JOSE DO RIO PARDO','CARAZINHO','GUAIBA','ITAPIRA','ITATIBA','POCOS DE CALDAS','CARAGUATATUBA','CAMACARI','JAGUARIUNA',
'TATUI','LOUVEIRA','BIGUACU','PENAPOLIS','SAO JOAQUIM DA BARRA','ORLANDIA','IMPERATRIZ','BOITUVA','ARMACAO DOS BUZIOS','CAMBE','ITAJUBA','ARAGUARI','DRACENA')
THEN 'Sim'
  ELSE 'Não'
END    
