
--====================================================================================================
-- QUERY ORIGINAL DO PHELIPE           PROMESSA DE PAGAMENTO SITE/APP MÓVEL
--====================================================================================================


SELECT /*PARALLEL (8) */
        TO_NUMBER(TO_CHAR(DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')) AS DT_REGISTRO,
        DSC_METODO_CONTATO AS METODO_DE_CONTATO,
        COUNT (*) AS QTDE_PROMESSA
FROM BI_FP_ASSINANTE_ATEND_FECHADO@BASECLARO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO@BASECLARO M
ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO@BASECLARO MC
ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND UPPER(M.DSC_MOTIVO_ATEND_NIVEL_3) = 'RESTITUIÇÃO/RETOMADA'
AND UPPER(M.DSC_MOTIVO_ATEND_NIVEL_1) = 'SOLICITAÇÃO'
AND MC.DW_METODO_CONTATO IN (81, 411, 451,681,701,552)
GROUP BY
        TO_NUMBER(TO_CHAR(DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')),
        DSC_METODO_CONTATO

/*nova versão alinhada com Neosyx*/

SELECT /*PARALLEL (8) */
        TO_NUMBER(TO_CHAR(DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')) AS DT_REGISTRO,
        DSC_METODO_CONTATO AS METODO_DE_CONTATO,
        COUNT (*) AS QTDE_PROMESSA
FROM BI_FP_ASSINANTE_ATEND_FECHADO@BASECLARO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO@BASECLARO M
ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO@BASECLARO MC
ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND UPPER(M.DSC_MOTIVO_ATEND_NIVEL_4) LIKE '%RESTITUIÇÃO/RETOMADA%'
AND M.DSC_MOTIVO_ATEND_NIVEL_2 IN ('Claro Controle','Banda Larga Conta')
AND MC.DW_METODO_CONTATO IN (81, 411, 451,681,701,552)
GROUP BY
        TO_NUMBER(TO_CHAR(DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')),
        DSC_METODO_CONTATO


--====================================================================================================
--                  PROMESSA DE PAGAMENTO SITE/APP MÓVEL
--====================================================================================================


SELECT /*PARALLEL (32) */
        TO_NUMBER(TO_CHAR(DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')) AS DT_REGISTRO
        ,T.NUM_NTC
        ,DSC_METODO_CONTATO AS METODO_DE_CONTATO
        ,T.COD_LOGIN_ATEND_CRIACAO
     --   ,T.DSC_OBSERVACAO_ATENDIMENTO
    --    ,COUNT (*) AS QTDE_PROMESSA
        ,count(distinct(T.NUM_NTC)) AS QT_NTC
     
FROM BI_FP_ASSINANTE_ATEND_FECHADO@BASECLARO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO@BASECLARO M                   ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO@BASECLARO MC                      ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
LEFT JOIN OPS_ALTERYX.BI_FP_BASE_ASSINANTE_CMV@BASECLARO CLI      ON T.NUM_NTC = CLI.NUM_NTC


WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND UPPER(M.DSC_MOTIVO_ATEND_NIVEL_4) LIKE '%RESTITUIÇÃO/RETOMADA%'
AND M.DSC_MOTIVO_ATEND_NIVEL_2 IN ('Claro Controle','Banda Larga Conta')
AND MC.DW_METODO_CONTATO IN (81, 411, 451,681,701,552)
GROUP BY
        TO_NUMBER(TO_CHAR(DAT_INICIO_ATENDIMENTO, 'RRRRMMDD'))
        ,T.NUM_NTC
        ,DSC_METODO_CONTATO
        ,T.COD_LOGIN_ATEND_CRIACAO
       -- ,T.DSC_OBSERVACAO_ATENDIMENTO
;

select * from BI_FP_ASSINANTE_ATEND_FECHADO@BASECLARO T

select * FROM OPS_ALTERYX.BI_FP_BASE_ASSINANTE_CMV@BASECLARO

select * from U93073449.BI_FT_CLIENTE_DIGITAL@BASECLARO DIG ;
-- 

SELECT * FROM DWH.BI_DIM_CLIENTE@BASECLARO CLI 

CLI.NUM_CPF NUM_CNPJ;
select * from all_all_tables where TABLE_NAME like '%CPF_CNPJ%';
