

/*--======================================================================================================================================
	ETAPA 1 - SQL
--======================================================================================================================================*/
--ETAPA 1A
DROP TABLE TMP_MCR_NLOGADA;
CREATE TABLE TMP_MCR_NLOGADA COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 2 ACESSO MCR
      TO_DATE('31/10/2020') AS DT_REFERENCIA         
      ,TO_NUMBER(TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMM')) AS SAFRA
      ,TO_NUMBER(TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMMDD')) AS SK_DATA
     ,TO_DATE(A.DT_HR_SOLICITACAO,'DD/MM/RRRR') AS DATA_SOLICITACAO
     ,A.DT_HR_SOLICITACAO
     ,A.CODIGO_NET
     ,A.NM_CIDADE
     ,TO_CHAR(A.CODIGO_NET ||' '||TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMMDD') 
                                 ||' '||REPLACE(SUBSTR(TO_CHAR(A.DT_HR_SOLICITACAO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
           ,'AREA_NLOGADA' AS AREA_ACESSO     
FROM INN.EXT_ADMINSITE A
---LEFT JOIN DT_REFERENCIA B ON TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMM') = B.SAFRA
     
WHERE TRUNC(A.DT_HR_SOLICITACAO) BETWEEN TO_DATE(&&DATA_INI, 'YYYYMMDD')AND TO_DATE(&&DATA_FIM, 'YYYYMMDD') 
      AND UPPER(A.NM_TIPO_PEDIDO) LIKE '%FATURA F?CIL%' --->>> SOMENTE ACESSO
      AND A.NM_DESC_PEDIDO LIKE 'LOG de Aplicacao' -- MARCACAO DA AREA NÃO LOGADA DO FATURA FÁCIL;
GROUP BY   
    TO_DATE('31/10/2020')
,TO_NUMBER(TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMM'))
,TO_NUMBER(TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMMDD'))
/*OK*/     ,TO_DATE(A.DT_HR_SOLICITACAO,'DD/MM/RRRR')
/*OK*/     ,A.DT_HR_SOLICITACAO
/*OK*/     ,A.CODIGO_NET
/*OK*/     ,A.NM_CIDADE
/*OK*/     ,TO_CHAR(A.CODIGO_NET ||' '||TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMMDD') 
                                 ||' '||REPLACE(SUBSTR(TO_CHAR(A.DT_HR_SOLICITACAO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) 
ORDER BY TO_CHAR(A.CODIGO_NET ||' '||TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DT_HR_SOLICITACAO,'dd/mm/yyyy hh24:mi:ss'),12,8),':',''))
;

--ETAPA 1B
DROP TABLE TMP_MCR_LOGADA;
CREATE TABLE TMP_MCR_LOGADA COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 2 ACESSO MCR
          TO_DATE('31/10/2020') AS DT_REFERENCIA         
      ,TO_NUMBER(TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMM')) AS SAFRA
      ,TO_NUMBER(TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMMDD')) AS SK_DATA
/*OK*/     ,TO_DATE(A.DT_HR_SOLICITACAO,'DD/MM/RRRR') AS DATA_SOLICITACAO
/*OK*/     ,A.DT_HR_SOLICITACAO
/*OK*/     ,A.CODIGO_NET
/*OK*/     ,A.NM_CIDADE
/*OK*/     ,TO_CHAR(A.CODIGO_NET ||' '||TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMMDD') 
                                 ||' '||REPLACE(SUBSTR(TO_CHAR(A.DT_HR_SOLICITACAO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
           ,'AREA_LOGADA' AS AREA_ACESSO     
FROM INN.EXT_ADMINSITE A
--LEFT JOIN DT_REFERENCIA B ON TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMM') = B.SAFRA
     
WHERE TRUNC(A.DT_HR_SOLICITACAO) BETWEEN TO_DATE(&&DATA_INI, 'YYYYMMDD')AND TO_DATE(&&DATA_FIM, 'YYYYMMDD') 
      AND NM_TIPO_PEDIDO = 'Consulta VT DashBoard' --->>> SOMENTE ACESSO
      AND TRIM(SUBSTR(NM_DESC_PEDIDO,INSTR(A.NM_DESC_PEDIDO,'|origem:')+8)) IN ('NETAPP','MINHANET','MEUTECNICO','NETAPPNOVO') --'BOT','MIND';
GROUP BY       
     TO_DATE('31/10/2020')
,TO_NUMBER(TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMM'))
,TO_NUMBER(TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMMDD'))
     ,TO_DATE(A.DT_HR_SOLICITACAO,'DD/MM/RRRR')
     ,A.DT_HR_SOLICITACAO
     ,A.CODIGO_NET
/*OK*/     ,A.NM_CIDADE
/*OK*/     ,TO_CHAR(A.CODIGO_NET ||' '||TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMMDD') 
                                 ||' '||REPLACE(SUBSTR(TO_CHAR(A.DT_HR_SOLICITACAO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) 
ORDER BY TO_CHAR(A.CODIGO_NET ||' '||TO_CHAR(A.DT_HR_SOLICITACAO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DT_HR_SOLICITACAO,'dd/mm/yyyy hh24:mi:ss'),12,8),':',''))
;



/*--======================================================================================================================================
	ETAPA 2 - SAS 
		CONEXÃO ORACLE E SAS
--======================================================================================================================================*/
libname CobINT '/u01/sasdata/cobranca/DADOS_COBRANCA/CI';
libname CobINT '/u01/sasdata/cobranca/DADOS_COBRANCA/STAGE';
libname SCORE '/u01/sasdata/cobranca/DADOS_COBRANCA/MODELAGEM/NET/SCORE';
libname CI '/u01/sasdata/cobranca/DADOS_COBRANCA/CI';
libname CRF '/u01/sasdata/cobranca/DADOS_COBRANCA/CRF';
libname DI '/u01/sasdata/cobranca/DADOS_COBRANCA/DI';
LIBNAME PDD "/u01/sasdata/cobranca/DADOS_COBRANCA/PDD";
libname Wagner '/u01/sasdata/cobranca/DADOS_COBRANCA/WORK/WAGNER';
				
options compress=yes;

%include "%sysget (CIENVVAR)";

LIBNAME INN ORACLE REREAD_EXPOSURE=YES DBMAX_TEXT=32767 READBUFF=32767 UTILCONN_TRANSIENT=YES PATH=INN SCHEMA=INN USER=OPS_DBM PASSWORD="{SAS002}C4A1204825B98E4808DFB08507FC7D39";


/*LIBNAME P00DW1 ORACLE PATH=P00DW1_SAS SCHEMA=DWH USER=U92047747 PASSWORD="Claro*202002";*/
/*LIBNAME P00DW1 ORACLE PATH=P00DW1_SAS SCHEMA=DWH USER=U92047747 PASSWORD="Claro*202002";*/
LIBNAME P00DW1 ORACLE PATH=P00DW1_SAS SCHEMA=DWH USER=U92047747 PASSWORD="W@6n45*001";
LIBNAME T6137207 ORACLE PATH=INN SCHEMA=INN USER=T6137207 PASSWORD="Claro*202004";


%let MES_ATU = 202006;
%LET FIM_MES = '30Jun2020'D;

/* ETAPA 2A*/
proc sql; 
	connect to oracle (USER="T6137207" PASSWORD="Claro*202004" path = "INN");   
		create table work.ACESSO_MCR_NLOG_&MES_ATU. AS SELECT * from connection to oracle   
			(
		SELECT * FROM T6137207.TMP_MCR_NLOGADA           
			);run;
LIBNAME T6137207 ORACLE PATH=INN SCHEMA=INN USER=T6137207 PASSWORD="Claro*202004";

%let MES_ATU = 202006;
%LET FIM_MES = '30Jun2020'D;
proc sql; 
	connect to oracle (USER="T6137207" PASSWORD="Claro*202004" path = "INN");   
		create table work.ACESSO_MCR_NLOG_&MES_ATU. AS SELECT * from connection to oracle   
			(
		SELECT * FROM T6137207.TMP_MCR_NLOGADA           
			);run;
LIBNAME T6137207 ORACLE PATH=INN SCHEMA=INN USER=T6137207 PASSWORD="Claro*202004";


proc sql; 
	connect to oracle (USER="T6137207" PASSWORD="Claro*202004" path = "INN");   
		create table work.ACESSO_MCR_LOG_&MES_ATU. AS SELECT * from connection to oracle   
			(
		SELECT * FROM T6137207.TMP_MCR_NLOGADA           
			);run;
LIBNAME T6137207 ORACLE PATH=INN SCHEMA=INN USER=T6137207 PASSWORD="Claro*202004";



/*--=============================================================================================================================
								Retido Digital Minha Claro Residencial NET
	Base de acesso no DWH
	Base de Ligações no SAS
	Retido Digital em D0
--=============================================================================================================================*/


%let MES_ATU = 202006;
%LET FIM_MES = '30Jun2020'D;

DATA WAGNER.ACESSO_MCR_&MES_ATU.;
SET work.ACESSO_MCR_&MES_ATU.
	work.ACESSO_MCR_NLOG_&MES_ATU.;
SK_ACESSO1 = CODIGO_NET||' '|| put((DATA_SOLICITACAO)+1,yymmddn8.)||' '||COMPRESS(PUT(HOUR(DT_HR_SOLICITACAO),Z2.)||PUT(minute(DT_HR_SOLICITACAO),Z2.)||PUT(second(DT_HR_SOLICITACAO),Z2.));
SK_ACESSO2 = CODIGO_NET||' '|| put((DATA_SOLICITACAO)+2,yymmddn8.)||' '||COMPRESS(PUT(HOUR(DT_HR_SOLICITACAO),Z2.)||PUT(minute(DT_HR_SOLICITACAO),Z2.)||PUT(second(DT_HR_SOLICITACAO),Z2.));
SK_ACESSO3 = CODIGO_NET||' '|| put((DATA_SOLICITACAO)+3,yymmddn8.)||' '||COMPRESS(PUT(HOUR(DT_HR_SOLICITACAO),Z2.)||PUT(minute(DT_HR_SOLICITACAO),Z2.)||PUT(second(DT_HR_SOLICITACAO),Z2.));
SK_ACESSO7 = CODIGO_NET||' '|| put((DATA_SOLICITACAO)+7,yymmddn8.)||' '||COMPRESS(PUT(HOUR(DT_HR_SOLICITACAO),Z2.)||PUT(minute(DT_HR_SOLICITACAO),Z2.)||PUT(second(DT_HR_SOLICITACAO),Z2.));
SK_ACESSO30 = CODIGO_NET||' '|| put(&FIM_MES.,yymmddn8.)||' '||'235959'||PUT(minute(DT_HR_SOLICITACAO),Z2.)||PUT(second(DT_HR_SOLICITACAO),Z2.);
RUN;


DATA RET_CR_&mes_atu._P1;
SET COBRANCA.CR_NET_&mes_atu.(KEEP = NM_MARCA NM_SUB_MARCA SK_DATA DH_LIGACAO CD_OPERADORA NR_CONTRATO);
SAFRA = put(datepart(DH_LIGACAO),yymmn6.)*1;
/*HORA = COMPRESS(PUT(HOUR(DH_LIGACAO),Z2.)||PUT(minute(DH_LIGACAO),Z2.)||PUT(second(DH_LIGACAO),Z2.));*/
CODIGO_NET = PUT(CD_OPERADORA,Z3.)||PUT(NR_CONTRATO,Z9.); 
SK_LIGA = CODIGO_NET||' '|| put(datepart(DH_LIGACAO),yymmddn8.)||' '||COMPRESS(PUT(HOUR(DH_LIGACAO),Z2.)||PUT(minute(DH_LIGACAO),Z2.)||PUT(second(DH_LIGACAO),Z2.));

SK_DATA1 = put(datepart(DH_LIGACAO)+1, yymmddn8.)*1;
SK_LIGA1 = CODIGO_NET||' '|| put(datepart(DH_LIGACAO)+1,yymmddn8.)||' '||COMPRESS(PUT(HOUR(DH_LIGACAO),Z2.)||PUT(minute(DH_LIGACAO),Z2.)||PUT(second(DH_LIGACAO),Z2.));

SK_DATA2 = put(datepart(DH_LIGACAO)+2, yymmddn8.)*1;
SK_LIGA2 = CODIGO_NET||' '|| put(datepart(DH_LIGACAO)+2,yymmddn8.)||' '||COMPRESS(PUT(HOUR(DH_LIGACAO),Z2.)||PUT(minute(DH_LIGACAO),Z2.)||PUT(second(DH_LIGACAO),Z2.));

SK_DATA3 = put(datepart(DH_LIGACAO)+3, yymmddn8.)*1;
SK_LIGA3 = CODIGO_NET||' '|| put(datepart(DH_LIGACAO)+3,yymmddn8.)||' '||COMPRESS(PUT(HOUR(DH_LIGACAO),Z2.)||PUT(minute(DH_LIGACAO),Z2.)||PUT(second(DH_LIGACAO),Z2.));

SK_DATA7 = put(datepart(DH_LIGACAO)+7, yymmddn8.)*1;
SK_LIGA7 = CODIGO_NET||' '|| put(datepart(DH_LIGACAO)+7,yymmddn8.)||' '||COMPRESS(PUT(HOUR(DH_LIGACAO),Z2.)||PUT(minute(DH_LIGACAO),Z2.)||PUT(second(DH_LIGACAO),Z2.));

SK_DATA30 = put(&FIM_MES., yymmddn8.)*1;
SK_LIGA30 = CODIGO_NET||' '|| put(&FIM_MES.,yymmddn8.)||' '||COMPRESS(PUT(HOUR(DH_LIGACAO),Z2.)||PUT(minute(DH_LIGACAO),Z2.)||PUT(second(DH_LIGACAO),Z2.));


RUN;

PROC SQL; CREATE TABLE RET_CR_&mes_atu._P2 AS
SELECT DISTINCT 
	A.SAFRA
	,MAX(SK_DATA) AS DT_REFERENCIA 
FROM WORK.RET_CR_&MES_ATU._P1 A
GROUP BY 1
;QUIT;
DATA RET_CR_&mes_atu._P4;
SET WAGNER.ACESSO_MCR_&MES_ATU.;
DT_REFERENCIA = MAX(SK_DATA)*1 ;
SAFRA1 = SAFRA*1;
KEEP SAFRA1 DT_REFERENCIA;
RUN;
PROC SQL; CREATE TABLE RET_CR_&mes_atu._P4B AS /*BASE DATA LIMITE DE ACESSO*/
SELECT DISTINCT 
	A.SAFRA FORMAT=BEST9. AS SAFRA 
	,MAX(SK_DATA) FORMAT=BEST9. AS DT_REFERENCIA
FROM WORK.ACESSO_MCR_&MES_ATU. A
GROUP BY 1
;QUIT;
PROC SQL; CREATE TABLE RET_CR_&mes_atu._P5 AS 
	SELECT 
	A.*
	,C.DT_REFERENCIA 
FROM RET_CR_&mes_atu._P1 AS A
LEFT JOIN RET_CR_&mes_atu._P2 AS B /*BASE COM A DATA LIMITE DE LIGAÇÃO*/
	ON A.SAFRA = B.SAFRA 
LEFT JOIN RET_CR_&mes_atu._P4 AS C 	/*BASE COM A DATA LIMITE DE ACESSO*/
	ON B.SAFRA = C.SAFRA1  
WHERE C.DT_REFERENCIA >= A.SK_DATA

;QUIT;
PROC SQL; CREATE TABLE RET_CR_&mes_atu._P6 AS 
SELECT DISTINCT
	A.SK_ACESSO
	,CASE WHEN A.SK_ACESSO > B.SK_LIGA THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
	FROM WAGNER.ACESSO_MCR_&MES_ATU. AS A 		/*BASE DE ACESSO*/
	INNER JOIN RET_CR_&mes_atu._P5 AS B /*BASE DE LIGAÇÃO*/
		ON A.CODIGO_NET = B.CODIGO_NET
		AND A.SK_DATA = B.SK_DATA
		
GROUP BY A.SK_ACESSO 
ORDER BY A.SK_ACESSO 
;QUIT;

PROC SQL; CREATE TABLE RET_CR_&mes_atu._P8 AS
SELECT DISTINCT
	A.SAFRA
	,A.DT_REFERENCIA
	,A.SK_ACESSO
	,A.AREA_ACESSO
	,A.CODIGO_NET
	,'D 0' AS DSC_SAFRA
	,(CASE WHEN B.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' 
		   WHEN MAX(B.FLG_ACESSA_LIGA) = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END) AS DSC_VISAO_ANALISE
	

	FROM WAGNER.ACESSO_MCR_&MES_ATU. AS A		/*BASE DE ACESSO MCR*/
	LEFT JOIN RET_CR_&mes_atu._P6 AS B	/*BASE DE CLIENTES QUE ACESSA E LIGA*/
	ON A.SK_ACESSO = B.SK_ACESSO 		


GROUP BY 
	A.SAFRA
	,A.DT_REFERENCIA
	,A.SK_ACESSO
	,A.AREA_ACESSO
	,A.CODIGO_NET

;QUIT;
TITLE "RETIDO DIGITAL";
PROC SQL; CREATE TABLE WORK.AGG_RET_DIGITAL_MCR AS
	SELECT 
	A.SAFRA 
	,A.DT_REFERENCIA 
	,A.AREA_ACESSO
	,A.DSC_VISAO_ANALISE
	,A.DSC_SAFRA
	,(COUNT(DISTINCT(A.CODIGO_NET))) AS QT_USU_UNICOS 
    ,(COUNT(DISTINCT(A.SK_ACESSO))) AS QT_TRANSACOES
FROM RET_CR_&mes_atu._P8 AS A
GROUP BY A.SAFRA 
	,A.DT_REFERENCIA 
	,A.AREA_ACESSO
	,A.DSC_VISAO_ANALISE
	,A.DSC_SAFRA 

;QUIT;

DATA WAGNER.TMP_N_RET_MCR_&mes_atu.; /*BASE DE CLIENTES NÃO RETIDOS*/
SET RET_CR_&mes_atu._P6;
DSC_VISAO_ANALISE = "NAO RETIDO DIGITAL MCR";

WHERE FLG_ACESSA_LIGA = 0;
RUN;


DROP TABLE TMP_SQDAA_WHP_RET_P1;
CREATE TABLE TMP_SQDAA_DTH_RET_P1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel (32)*/ ----------------------------------------------------------------------------------------------ETAPA 1 BASE DE LIGACOES
	TO_DATE(
      ADD_MONTHS(
              LAST_DAY(TO_DATE(&&DT_MOVIMENTO, 'YYYYMMDD')),-1)+1,'DD/MM/YYYY') AS DAT_MOVIMENTO
	,'CTV' AS NM_MARCA
	,LIG.CD_CIDADE_CONTRATO
	,LIG.NR_CONTRATO AS NUM_CONTRATO
    ,LIG.SK_DATA
	,LIG.DH_LIGACAO AS DT_INI_LIGACAO
    ,TO_CHAR(LIG.NR_CONTRATO,'000000000') ||' '|| REPLACE(TO_CHAR(LIG.DH_LIGACAO,'yyyymmdd hh24:mi:ss'),':','') AS SK_LIGA
		
FROM INN.ANALITICA_CR_BI_LIG_NET LIG
WHERE 0 = 0
      AND LIG.SK_DATA BETWEEN 
		TO_NUMBER(
                  TO_CHAR(
                      (ADD_MONTHS(
                            LAST_DAY(
                                TO_DATE(&&DT_MOVIMENTO, 'YYYYMMDD')),-1)+1),'YYYYMMDD')) AND 
		TO_NUMBER(
            TO_CHAR(
                LAST_DAY(
                    TO_DATE(&&DT_MOVIMENTO, 'YYYYMMDD')),'YYYYMMDD')) 
      AND LIG.NR_CONTRATO IS NOT NULL          
;