/*---===========================================================================================================================
Ação: Lançamento Canal WhatsApp 
Inicio: 04/11/19
objetivo: RETENÇÃO NO ATENDIMENTO DO CANAL  

TABELAS:
          U92047747.AGG_RET_DIG_WHATSAPP
		  
          SELECT UNIQUE DAT_REFERENCIA FROM U92047747.AGG_RET_DIG_WHATSAPP;


CONCEITO:

	O RETIDO DIGITAL DO WHATSAPP CONSISTE EM IDENTIFICAR APÓS O ACESSO SE O CLIENTE LIGOU NA CENTRAL DE ATENDIMENTO OU O CLIENTES SEGUIU NO FLUXO DO TRANSBORDO HUMANO, O QUAL 
	ESTE TRANSBORDO HUMANO ERA TRABALHADO PELO FORNCEDOR TEL_BLIP (ANALISE DE ABRIL/2020);
	ANALISAMOS O RETIDO DIGITAL DO WHATSAPP QUANDO O CLIENTE LIGA NO MESMO DIA (SAFRA D0) OU EM D+1 (SAFRA 24HORAS) OU EM D+2 (SAFRA 48HORAS) OU EM D+3 (SAFRA 72HORAS) 
	OU EM D+7 (SAFRA ACESSO E LIGAÇÃO APÓS 7 DIAS) OU EM D+30 (SAFRA ACESSO E DENTRO DO MÊS);
	
PROBLEMAS NA BASE:
	
	NA BASE DO MINT POSSUEM CLIENTES RESIDENCIAS ONDE NÃO HÁ CÓDIGO DE PLATAFORMA OU NTC, ESTES CLIENTES SÃO EXPURGADOS DA ANALISE;
	POSSUEM TAMBÉM CLIENTE COM DDI OU NÚMEROS INTERNACIONAIS O QUAL NÃO CONSIGO IDENTIFICAR COMO CLIENTE;

INSTRUÇÕES:

	A QUERY POSSUI 18 ETAPAS SENDO DENTRO DELAS SUB ETAPAS;
	
          
RELAÇÃO DE CLIENTES UTILIZADOS PARA TESTE:

--NUM_NTC = '11920023824'   --09.01.2020 -> 11920023824 CLIENTES QUE ACESSOU WPP  
--NUM_NTC = '11976881122'   --02.03.2020 -> CLIENTE TRANSBORDO WPP
--NUM_NTC = '51991419490'   --07.02.2020 -> CLIENTE TRANSBORDO WPP
--NUM_NTC = '11980299093' -- 20.02.2020 --> INTERAÇÃO NO WPP
--NUM_NTC = '11930002132' -- 24.02.2020 --> LIGOU E ACESSOU 
--NUM_NTC = '11930003116' -- 14.02.2020 --> ACESSOU E ACESSOU
---===========================================================================================================================*/

--ETAPA 1 ACESSO WPP
DROP TABLE TMP_SQDAA_WPP_RET_P1;
CREATE TABLE TMP_SQDAA_WPP_RET_P1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 1 ACESSO WPP
        A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6) AS SAFRA --ok
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') AS SK_DATA --ok
        ,A.COD_PLATAFORMA --ok
        ,A.NUM_NTC --ok
        ,A.DAT_INICIO_ATENDIMENTO AS DT_INI_ATENDIMENTO
        ,TRUNC(A.DAT_INICIO_ATENDIMENTO) AS DAT_INICIO_ATENDIMENTO --ok
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO+1, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO1
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO+2, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO2
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO+3, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO3
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO+7, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO7        
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(LAST_DAY(A.DAT_INICIO_ATENDIMENTO), 'YYYYMMDD') ||' '||'235959') AS SK_ACESSO30
        ,A.COD_SHORT_CODE AS DW_SHORT_CODE_MINT
    ,SYSDATE                       AS DAT_CRIACAO
FROM DWH.BI_FP_ATENDIMENTO_MINT A
LEFT JOIN DWH.BI_DIM_CANAL_MINT B ON A.DW_NUM_CANAL_MINT = B.DW_NUM_CANAL_MINT
WHERE A.COD_SHORT_CODE = 9652 --- SHORT CODE WPP
AND A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&&DATA_FINAL, 'RRRRMMDD')


GROUP BY  A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6)
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD')
        ,A.COD_PLATAFORMA
        ,A.NUM_NTC
        ,A.DAT_INICIO_ATENDIMENTO
    ,A.COD_SHORT_CODE
;

--ETAPA 2 LIGACOES CR
DROP TABLE TMP_SQDAA_WPP_RET_P2;
CREATE TABLE TMP_SQDAA_WPP_RET_P2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+ PARALLEL (32)*/ ------------------------------------------------------------------------ETAPA 2 LIGACOES CR
       LAST_DAY(TO_DATE(FT.DT_INICIO_LIGACAO,'YYYY/MM/DD')) AS DAT_REFERENCIA       
       ,FT.DT_INICIO_LIGACAO SK_DATA       
       ,'CMV' AS NM_MARCA
       ,FT.SK_ATENDIMENTO_URA AS COD_CHAMADA -- CALL_ID
       ,TO_CHAR(FT.CD_NUMERO_TELEFONE ||' '||FT.DT_INICIO_LIGACAO ||' '||FT.NR_HORA_INICIO_LIGACAO) AS SK_LIGA
       ,TO_DATE(TO_DATE(FT.DT_INICIO_LIGACAO,'YYYY/MM/DD') ||' ' ||FT.NR_HORA_INICIO_LIGACAO,'DD/MM/RRRR HH24:MI:SS') AS DT_INI_LIGACAO
       ,TO_DATE(TO_DATE(FT.DT_FIM_LIGACAO,'YYYY/MM/DD') ||' ' ||FT.NR_HORA_FIM_LIGACAO,'DD/MM/RRRR HH24:MI:SS') AS DT_FIM_LIGACAO
       ,FT.CD_NUMERO_TELEFONE                           AS NUM_NTC
       ,CASE
         WHEN FT.FN_LIGACAO_IDENTIFICADA = 1 THEN
          'SIM'
         ELSE
          'NAO'
       END                                AS FLG_LIG_IDENTIFICADA
       ,STS.COD_SUB_STS_ATU DSC_STS_CLIENTE
       ,CASE
         WHEN FT.FN_CORPORATIVO = 1 THEN
          'SIM'
         ELSE
          'NAO'
       END                               AS FLG_CORPORATIVO
       ,CASE
         WHEN VA.NM_VISAO_ANALISE_BI = 'CONTACT RATE DIRECIONADO AO HUMANO' THEN
          'DIRECIONADO HUMANO'
         ELSE
          'RETIDO URA'
       END                           AS DSC_DIRECIONADO_RETIDO
       ,ATM.NM_TIPO_MOTIVO_BI         AS DSC_MOTIVO_URA
       ,STM.NM_SUB_TIPO_MOTIVO_BI     AS DSC_SUB_MOTIVO_URA
       ,ATL.NM_TIPO_LIGACAO_BI        AS DSC_EXPURGO_URA
       ,PP.DSC_PLANO_PRECO_BI         AS DSC_PLANO_CLIENTE
       ,SYSDATE                       AS DAT_CRIACAO

  FROM INTMKT.FT_ATENDIMENTO_URA FT -- OK
  LEFT JOIN DWH.BI_DIM_STATUS STS -- OK
    ON STS.STS_DW = FT.SK_STATUS
  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_MOTIVO ATM -- OK
    ON ATM.SK_ATENDIMENTO_TIPO_MOTIVO = FT.SK_ATENDIMENTO_TIPO_MOTIVO
 
  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_LIGACAO ATL -- OK
    ON ATL.SK_ATENDIMENTO_TIPO_LIGACAO = FT.SK_ATENDIMENTO_TIPO_LIGACAO
  LEFT JOIN DWH.BI_DIM_PLANO_PRECO PP -- OK
    ON PP.DW_PLANO = FT.SK_PLANO
  LEFT JOIN INTMKT.DS_ATENDIMENTO_SUB_TIPO_MOTIVO STM -- OK
   ON STM.SK_ATENDIMENTO_SUB_TIPO_MOTIVO =
       FT.SK_ATENDIMENTO_SUB_TIPO_MOTIVO
  LEFT JOIN INTMKT.DS_VISAO_ANALISE VA -- OK
    ON VA.SK_VISAO_ANALISE = FT.SK_VISAO_ANALISE
  LEFT JOIN intmkt.ds_atendimento_tipo_ligacao ATL 
ON        atl.sk_atendimento_tipo_ligacao = ft.sk_atendimento_tipo_ligacao 

WHERE FT.SK_DATA BETWEEN &&DATA_INICIAL AND &&DATA_FINAL
---AND       atl.nm_tipo_ligacao_bi = 'Ligações Válidas' -- FILTRO OK (SÃO CLIENTES QUE NÃO TIVERAM ABANDONO)
---AND va.nm_visao_analise_bi = 'Contact Rate Direcionado ao Humano' -- FILTRO OK
;

--ETAPA 3.0 D0
DROP TABLE TMP_SQDAA_WPP_RET_P3A; 
CREATE TABLE TMP_SQDAA_WPP_RET_P3A COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT  /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3.1 ACESSO COM CR
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.DT_INI_ATENDIMENTO > CR.DT_INI_LIGACAO THEN 1 ELSE 0 END FLG_ACESSA_LIGA 
     ,CASE WHEN AC.DT_INI_ATENDIMENTO > CR.DT_INI_LIGACAO THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE 
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 AC -- WPP
INNER JOIN TMP_SQDAA_WPP_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(AC.DT_INI_ATENDIMENTO) = TRUNC(CR.DT_INI_LIGACAO) ---------->>>>> SOMENTE D+0
WHERE COD_PLATAFORMA <> '-2'
    
ORDER BY  AC.SK_ACESSO
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 3.1 24H APOS O ACESSO
DROP TABLE TMP_SQDAA_WPP_RET_P3B;
CREATE TABLE TMP_SQDAA_WPP_RET_P3B COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 24H APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO1 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO1 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 1' AS DSC_SAFRA
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 AC -- WPP
INNER JOIN TMP_SQDAA_WPP_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.DT_INI_ATENDIMENTO) AND TRUNC(AC.DT_INI_ATENDIMENTO)+1 ---- 24H APOS O ACESSO

WHERE COD_PLATAFORMA <> '-2' 

ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
;


--ETAPA 3.2 48H APOS O ACESSO
DROP TABLE TMP_SQDAA_WPP_RET_P3C;
CREATE TABLE TMP_SQDAA_WPP_RET_P3C COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 48H APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO2 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO2 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 2' AS DSC_SAFRA
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 AC -- WPP
INNER JOIN TMP_SQDAA_WPP_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.DT_INI_ATENDIMENTO) AND TRUNC(AC.DT_INI_ATENDIMENTO)+2 ---- 48H APOS O ACESSO

WHERE COD_PLATAFORMA <> '-2' 

ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
;

--ETAPA 3.3 72H APOS O ACESSO
DROP TABLE TMP_SQDAA_WPP_RET_P3D;
CREATE TABLE TMP_SQDAA_WPP_RET_P3D COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 72H APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO3 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO3 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 3' AS DSC_SAFRA
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 AC -- WPP
INNER JOIN TMP_SQDAA_WPP_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.DT_INI_ATENDIMENTO) AND TRUNC(AC.DT_INI_ATENDIMENTO)+3 ---- 72H APOS O ACESSO

WHERE COD_PLATAFORMA <> '-2' 

ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 3.4 7 DIAS APOS O ACESSO
DROP TABLE TMP_SQDAA_WPP_RET_P3E;
CREATE TABLE TMP_SQDAA_WPP_RET_P3E COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 7 DIAS APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO7 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO7 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 7' AS DSC_SAFRA
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 AC -- WPP
INNER JOIN TMP_SQDAA_WPP_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.DT_INI_ATENDIMENTO) AND TRUNC(AC.DT_INI_ATENDIMENTO)+7 ---- 7 DIAS APOS O ACESSO

WHERE COD_PLATAFORMA <> '-2' 

ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 3.5 DENTRO DO MÊS DE O ACESSO
DROP TABLE TMP_SQDAA_WPP_RET_P3F;
CREATE TABLE TMP_SQDAA_WPP_RET_P3F COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 DENTRO DO MÊS DE ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
--       ,AC.SK_ACESSO30
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1 
             WHEN CR.SK_LIGA BETWEEN AC.SK_ACESSO AND AC.SK_ACESSO30 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA 
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA BETWEEN AC.SK_ACESSO AND AC.SK_ACESSO30 THEN 'ACESSOU E LIGOU' ELSE  'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'DM0' AS DSC_SAFRA
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 AC -- WPP
INNER JOIN TMP_SQDAA_WPP_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.DT_INI_ATENDIMENTO) AND TRUNC(LAST_DAY(AC.DT_INI_ATENDIMENTO)) ---- DENTRO DO MÊS DE ACESSO

WHERE COD_PLATAFORMA <> '-2' 
    

ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 4 TRANSBORDO BLIP_TEL
DROP TABLE TMP_SQDAA_WPP_RET_P4;
CREATE TABLE TMP_SQDAA_WPP_RET_P4 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /* +PARALLEL (32) */ ----------------------------------------------------------------ETAPA 4 TRANSBORDO BLIP_TEL
        TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO, 'DD/MM/RRRR'),'RRRRMM') AS SAFRA --ok
        ,TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO, 'DD/MM/RRRR'),'RRRRMMDD') AS SK_DATA --ok
        ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(T.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||T.HOR_INICIO_ATENDIMENTO) AS SK_ACESSO 
        ,TO_DATE(TO_DATE(T.DAT_INICIO_ATENDIMENTO,'DD/MM/YYYY') ||' ' ||T.HOR_INICIO_ATENDIMENTO,'DD/MM/RRRR HH24:MI:SS') AS DT_INI_CHAT
        ,T.NUM_NTC
        ,T.COD_LOGIN_ATEND_CRIACAO
        ,MC.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO AS METODO_CONTATO
        ,CASE WHEN T.NUM_NTC = AC.NUM_NTC 
              AND TRUNC(AC.DT_INI_ATENDIMENTO) = TRUNC(T.DAT_INICIO_ATENDIMENTO) THEN 0 ELSE 1 END AS FLG_ACESSA_TRANSBORDO

FROM BI_FP_ASSINANTE_ATEND_FECHADO T
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M ON T.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO MC    ON T.DW_METODO_CONTATO = MC.DW_METODO_CONTATO
INNER JOIN TMP_SQDAA_WPP_RET_P1 AC    ON T.NUM_NTC = AC.NUM_NTC -- ACESSO
      AND TRUNC(AC.DT_INI_ATENDIMENTO) = TRUNC(T.DAT_INICIO_ATENDIMENTO) ---------->>>>> SOMENTE D+0
WHERE T.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&&DATA_FINAL, 'RRRRMMDD')
      AND T.DW_METODO_CONTATO IN (781)---WhatsApp
      AND T.COD_LOGIN_ATEND_CRIACAO NOT IN ('USSD')
GROUP BY 
        TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO, 'DD/MM/RRRR'),'RRRRMM')
        ,TO_CHAR(TO_DATE(T.DAT_INICIO_ATENDIMENTO, 'DD/MM/RRRR'),'RRRRMMDD')
    ,TO_CHAR(T.NUM_NTC ||' '||TO_CHAR(T.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||T.HOR_INICIO_ATENDIMENTO)
        ,TO_DATE(TO_DATE(T.DAT_INICIO_ATENDIMENTO,'DD/MM/YYYY') ||' ' ||T.HOR_INICIO_ATENDIMENTO,'DD/MM/RRRR HH24:MI:SS')
        ,T.NUM_NTC
        ,T.COD_LOGIN_ATEND_CRIACAO
        ,MC.DW_METODO_CONTATO
        ,MC.DSC_METODO_CONTATO
        ,CASE WHEN T.NUM_NTC = AC.NUM_NTC 
              AND TRUNC(AC.DT_INI_ATENDIMENTO) = TRUNC(T.DAT_INICIO_ATENDIMENTO) THEN 0 ELSE 1 END
ORDER BY T.NUM_NTC ,TO_DATE(TO_DATE(T.DAT_INICIO_ATENDIMENTO,'DD/MM/YYYY') ||' ' ||T.HOR_INICIO_ATENDIMENTO,'DD/MM/RRRR HH24:MI:SS')
;




--ETAPA 5.0 D0 ACESSO + CR + TRANSBORDO
DROP TABLE FT_RET_DIGITAL_WHATSAPP0; 
CREATE TABLE FT_RET_DIGITAL_WHATSAPP0 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT ------------------------------------------------------------------------ETAPA 5 ACESSO + CR + TRANSBORDO
        A.SK_ACESSO 
        ,A.SAFRA 
        ,A.NUM_NTC 
        ,A.SK_DATA 
        ,A.COD_PLATAFORMA 
        ,A.DAT_INICIO_ATENDIMENTO
        ,A.DT_INI_ATENDIMENTO
        ,A.DW_SHORT_CODE_MINT
        ,'WhatsApp' AS DSC_METODO_CONTATO
        ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
        ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_TRANSBORDA
        ,CASE WHEN B.SK_ACESSO IS NULL 
               AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
        ,'D 0' AS DSC_SAFRA              
        ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 A

LEFT JOIN TMP_SQDAA_WPP_RET_P3A B --->>LIGA URA
     ON A.SK_ACESSO = B.SK_ACESSO

LEFT JOIN TMP_SQDAA_WPP_RET_P4 C --->>TRANSBORDO
     ON A.SK_ACESSO = C.SK_ACESSO

WHERE COD_PLATAFORMA <> '-2'

GROUP BY  
           A.SK_ACESSO
            ,A.SAFRA 
           ,A.NUM_NTC 
           ,A.SK_DATA 
           ,A.COD_PLATAFORMA 
           ,A.DAT_INICIO_ATENDIMENTO
           ,A.DW_SHORT_CODE_MINT
           ,A.DT_INI_ATENDIMENTO
           ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
           ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END
           ,CASE WHEN B.SK_ACESSO IS NULL 
               AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END  
       
ORDER BY A.SK_ACESSO
;


--ETAPA 5.1 - D1 24H APOS O ACESSO + CR + TRANSBORDO
DROP TABLE FT_RET_DIGITAL_WHATSAPP1;   
CREATE TABLE FT_RET_DIGITAL_WHATSAPP1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT ------------------------------------------------------------------------ETAPA 5 ACESSO + CR + TRANSBORDO
    A.SK_ACESSO 
    ,A.SAFRA 
    ,A.NUM_NTC 
    ,A.SK_DATA 
    ,A.COD_PLATAFORMA 
    ,A.DAT_INICIO_ATENDIMENTO
    ,A.DT_INI_ATENDIMENTO
    ,A.DW_SHORT_CODE_MINT
  ,'WhatsApp' AS DSC_METODO_CONTATO
        ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
        ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_TRANSBORDA
  ,CASE WHEN B.SK_ACESSO IS NULL 
               AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
  ,'D 1' AS DSC_SAFRA ----------------------------------------------------------------------------------------->> D1 24H APOS O ACESSO          
        ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 A

LEFT JOIN TMP_SQDAA_WPP_RET_P3B B ----------------------------------------------------------------------------------->> D1 24H APOS O ACESSO 
     ON A.SK_ACESSO = B.SK_ACESSO

LEFT JOIN TMP_SQDAA_WPP_RET_P4 C --->>TRANSBORDO
     ON A.SK_ACESSO = C.SK_ACESSO

WHERE COD_PLATAFORMA <> '-2'

GROUP BY  
  A.SK_ACESSO
  ,A.SAFRA 
  ,A.NUM_NTC 
  ,A.SK_DATA 
  ,A.COD_PLATAFORMA 
  ,A.DAT_INICIO_ATENDIMENTO
  ,A.DW_SHORT_CODE_MINT
  ,A.DT_INI_ATENDIMENTO
  ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
  ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END
  ,CASE WHEN B.SK_ACESSO IS NULL 
               AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END  
       
ORDER BY A.SK_ACESSO
;



--ETAPA 5.2 - D2 48H APOS O ACESSO + CR + TRANSBORDO
DROP TABLE FT_RET_DIGITAL_WHATSAPP2;   
CREATE TABLE FT_RET_DIGITAL_WHATSAPP2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS ---------------------------->> D2 48H APOS O ACESSO
SELECT DISTINCT 
          A.SK_ACESSO 
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.DT_INI_ATENDIMENTO
          ,A.DW_SHORT_CODE_MINT
          ,'WhatsApp' AS DSC_METODO_CONTATO
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
          ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_TRANSBORDA
          ,CASE WHEN B.SK_ACESSO IS NULL 
               AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
          ,'D 2' AS DSC_SAFRA ----------------------------------------------------------------------------------------->> D2 48H APOS O ACESSO          
        ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 A

LEFT JOIN TMP_SQDAA_WPP_RET_P3C B ----------------------------------------------------------------------------------->> D2 48H APOS O ACESSO 
     ON A.SK_ACESSO = B.SK_ACESSO

LEFT JOIN TMP_SQDAA_WPP_RET_P4 C --->>TRANSBORDO
     ON A.SK_ACESSO = C.SK_ACESSO

WHERE COD_PLATAFORMA <> '-2'

GROUP BY  
          A.SK_ACESSO
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.DW_SHORT_CODE_MINT
          ,A.DT_INI_ATENDIMENTO
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN B.SK_ACESSO IS NULL 
               AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END  
       
ORDER BY A.SK_ACESSO
;


--ETAPA 5.3 - D3 72H APOS O ACESSO + CR + TRANSBORDO
DROP TABLE FT_RET_DIGITAL_WHATSAPP3;   
CREATE TABLE FT_RET_DIGITAL_WHATSAPP3 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS ---------------------------->> D3 72H APOS O ACESSO
SELECT DISTINCT 
        A.SK_ACESSO 
        ,A.SAFRA 
        ,A.NUM_NTC 
        ,A.SK_DATA 
        ,A.COD_PLATAFORMA 
        ,A.DAT_INICIO_ATENDIMENTO
        ,A.DT_INI_ATENDIMENTO
        ,A.DW_SHORT_CODE_MINT
        ,'WhatsApp' AS DSC_METODO_CONTATO
        ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
        ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_TRANSBORDA
        ,CASE WHEN B.SK_ACESSO IS NULL 
               AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
        ,'D 3' AS DSC_SAFRA ----------------------------------------------------------------------------------------->> D3 72H APOS O ACESSO          
        ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 A

LEFT JOIN TMP_SQDAA_WPP_RET_P3D B ----------------------------------------------------------------------------------->> D3 72H APOS O ACESSO 
     ON A.SK_ACESSO = B.SK_ACESSO

LEFT JOIN TMP_SQDAA_WPP_RET_P4 C --->>TRANSBORDO
     ON A.SK_ACESSO = C.SK_ACESSO

WHERE COD_PLATAFORMA <> '-2'

GROUP BY  
          A.SK_ACESSO
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.DW_SHORT_CODE_MINT
          ,A.DT_INI_ATENDIMENTO
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN B.SK_ACESSO IS NULL 
               AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END        
ORDER BY A.SK_ACESSO
;


--ETAPA 5.4 - D7 7 DIAS APOS O ACESSO + CR + TRANSBORDO
DROP TABLE FT_RET_DIGITAL_WHATSAPP7;   
CREATE TABLE FT_RET_DIGITAL_WHATSAPP7 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS ---------------------------->> D7 7 DIAS APOS O ACESSO
SELECT DISTINCT 
          A.SK_ACESSO 
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.DT_INI_ATENDIMENTO
          ,A.DW_SHORT_CODE_MINT
          ,'WhatsApp' AS DSC_METODO_CONTATO
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
          ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_TRANSBORDA
          ,CASE WHEN B.SK_ACESSO IS NULL 
                 AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
          ,'D 7' AS DSC_SAFRA ----------------------------------------------------------------------------------------->> D7 7 DIAS APOS O ACESSO          
          ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 A

LEFT JOIN TMP_SQDAA_WPP_RET_P3E B ----------------------------------------------------------------------------------->> D7 7 DIAS APOS O ACESSO 
     ON A.SK_ACESSO = B.SK_ACESSO

LEFT JOIN TMP_SQDAA_WPP_RET_P4 C --->>TRANSBORDO
     ON A.SK_ACESSO = C.SK_ACESSO

WHERE COD_PLATAFORMA <> '-2'

GROUP BY  
          A.SK_ACESSO
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.DW_SHORT_CODE_MINT
          ,A.DT_INI_ATENDIMENTO
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN B.SK_ACESSO IS NULL 
                 AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END  
ORDER BY A.SK_ACESSO
;

--ETAPA 5.5 - M0 ACESSOS DENTRO DO MES + CR + TRANSBORDO
DROP TABLE FT_RET_DIGITAL_WHATSAPP30;   
CREATE TABLE FT_RET_DIGITAL_WHATSAPP30 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS ---------------------------->> M0 ACESSOS DENTRO DO MES 
SELECT DISTINCT 
            A.SK_ACESSO 
            ,A.SAFRA 
            ,A.NUM_NTC 
            ,A.SK_DATA 
            ,A.COD_PLATAFORMA 
            ,A.DAT_INICIO_ATENDIMENTO
            ,A.DT_INI_ATENDIMENTO
            ,A.DW_SHORT_CODE_MINT
            ,'WhatsApp' AS DSC_METODO_CONTATO
            ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
            ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_TRANSBORDA
            ,CASE WHEN B.SK_ACESSO IS NULL 
                   AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
            ,'DM0' AS DSC_SAFRA ----------------------------------------------------------------------------------------->> M0 ACESSOS DENTRO DO MES           
            ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_WPP_RET_P1 A

LEFT JOIN TMP_SQDAA_WPP_RET_P3F B ----------------------------------------------------------------------------------->> M0 ACESSOS DENTRO DO MES  
     ON A.SK_ACESSO = B.SK_ACESSO

LEFT JOIN TMP_SQDAA_WPP_RET_P4 C --->>TRANSBORDO
     ON A.SK_ACESSO = C.SK_ACESSO

WHERE COD_PLATAFORMA <> '-2'

GROUP BY  
          A.SK_ACESSO
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.DW_SHORT_CODE_MINT
          ,A.DT_INI_ATENDIMENTO
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN C.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN B.SK_ACESSO IS NULL 
                 AND C.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END        
ORDER BY A.SK_ACESSO
;

--ETAPA 6  DATA REFERENCIA
DROP TABLE TMP_RET_DIG_WHATSAPP_DTREF; 
CREATE TABLE TMP_RET_DIG_WHATSAPP_DTREF COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT ------------------------------------------------------------------------ETAPA 6  TABELA AGREGADA
SAFRA ,MAX(DAT_INICIO_ATENDIMENTO) AS DAT_REFERENCIA FROM TMP_SQDAA_WPP_RET_P1 GROUP BY SAFRA;


--ETAPA 7  TABELA FATO
--INSERT /*+APPEND */ INTO BI_FT_RET_DIG_WHATSAPP --------------------------------------------------------------------------ETAPA 7 TABELA FATO
DROP TABLE BI_FT_RET_DIG_WHATSAPP;
CREATE TABLE BI_FT_RET_DIG_WHATSAPP COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT B.DAT_REFERENCIA ,A.* FROM FT_RET_DIGITAL_WHATSAPP0 A LEFT JOIN TMP_RET_DIG_WHATSAPP_DTREF B ON A.SAFRA = B.SAFRA
UNION ALL
SELECT B.DAT_REFERENCIA ,A.* FROM FT_RET_DIGITAL_WHATSAPP1 A LEFT JOIN TMP_RET_DIG_WHATSAPP_DTREF B ON A.SAFRA = B.SAFRA
UNION ALL
SELECT B.DAT_REFERENCIA ,A.* FROM FT_RET_DIGITAL_WHATSAPP2 A LEFT JOIN TMP_RET_DIG_WHATSAPP_DTREF B ON A.SAFRA = B.SAFRA
UNION ALL
SELECT B.DAT_REFERENCIA ,A.* FROM FT_RET_DIGITAL_WHATSAPP3 A LEFT JOIN TMP_RET_DIG_WHATSAPP_DTREF B ON A.SAFRA = B.SAFRA
UNION ALL
SELECT B.DAT_REFERENCIA ,A.* FROM FT_RET_DIGITAL_WHATSAPP7 A LEFT JOIN TMP_RET_DIG_WHATSAPP_DTREF B ON A.SAFRA = B.SAFRA
UNION ALL
SELECT B.DAT_REFERENCIA ,A.* FROM FT_RET_DIGITAL_WHATSAPP30 A LEFT JOIN TMP_RET_DIG_WHATSAPP_DTREF B ON A.SAFRA = B.SAFRA
;

--ETAPA 8 TABELA AGREGADA
--*************************PRECISA REALIZAR O COMMIT APÓS O INSERT*****************************************************
INSERT /*+APPEND */ INTO AGG_RET_DIG_WHATSAPP ------------------------------------------------------------------------ETAPA 8 TABELA AGREGADA
SELECT DISTINCT       
          SAFRA
          ,DAT_REFERENCIA
          ,DW_SHORT_CODE_MINT
          ,DSC_METODO_CONTATO
          ,COD_PLATAFORMA
          ,DSC_SAFRA
          ,DSC_VISAO_ANALISE
          ,COUNT(DISTINCT(NUM_NTC))            AS QT_USU_UNICOS
          ,COUNT(DISTINCT(SK_ACESSO))          AS QT_ACESSO
          ,SYSDATE                               AS DAT_CRIACAO
           
FROM BI_FT_RET_DIG_WHATSAPP 
WHERE SAFRA = &SAFRA_YYYYMM
GROUP BY     
          SAFRA
          ,DAT_REFERENCIA
          ,DW_SHORT_CODE_MINT
          ,DSC_METODO_CONTATO
          ,COD_PLATAFORMA
          ,DSC_SAFRA
          ,DSC_VISAO_ANALISE

ORDER BY 
          SAFRA
          ,DAT_REFERENCIA
          ,DW_SHORT_CODE_MINT
          ,DSC_METODO_CONTATO
          ,COD_PLATAFORMA
          ,DSC_SAFRA
          ,DSC_VISAO_ANALISE;
COMMIT;
--SELECT UNIQUE DAT_REFERENCIA ,DSC_SAFRA FROM AGG_RET_DIG_WHATSAPP;

SELECT  ------------------------------------------------ CONSULTA 1 -------> UU_WPP_PLATAFORMA
         SAFRA
         ,COD_PLATAFORMA
         ,DSC_SAFRA
         ,DSC_VISAO_ANALISE
         ,SUM(QT_USU_UNICOS)AS QT_USU_UNICOS
         ,SUM(QT_ACESSO) AS QT_ACESSO

   FROM U92047747.AGG_RET_DIG_WHATSAPP   
GROUP BY SAFRA ,COD_PLATAFORMA ,DSC_SAFRA ,DSC_VISAO_ANALISE
ORDER BY SAFRA ,COD_PLATAFORMA ,DSC_SAFRA ,DSC_VISAO_ANALISE;




DROP TABLE TMP_SQDAA_WPP_RET_P1;
DROP TABLE TMP_SQDAA_WPP_RET_P2;
DROP TABLE TMP_SQDAA_WPP_RET_P3A; 
DROP TABLE TMP_SQDAA_WPP_RET_P3B;
DROP TABLE TMP_SQDAA_WPP_RET_P3C;
DROP TABLE TMP_SQDAA_WPP_RET_P3D;
DROP TABLE TMP_SQDAA_WPP_RET_P3E;
DROP TABLE TMP_SQDAA_WPP_RET_P3F;
DROP TABLE TMP_SQDAA_WPP_RET_P4;
DROP TABLE FT_RET_DIGITAL_WHATSAPP0; 
DROP TABLE FT_RET_DIGITAL_WHATSAPP1;  
DROP TABLE FT_RET_DIGITAL_WHATSAPP2;
DROP TABLE FT_RET_DIGITAL_WHATSAPP3; 
DROP TABLE FT_RET_DIGITAL_WHATSAPP7;  
DROP TABLE FT_RET_DIGITAL_WHATSAPP30;   
DROP TABLE TMP_RET_DIG_WHATSAPP_DTREF;
DROP TABLE BI_FT_RET_DIG_WHATSAPP;

