/* 
--====================================================================================================================================================================================

	76421 | Construção retido digital CTV
	
	O que precisa ser feito: Construir o indicador de retido digital para site e App CTV (considerando a abertura por canal)
	+ detalhes:
	O card pode ser concluído quando (específico): tivermos o indicador finalizado com as mesmas métricas e visões dos demais retidos
	
	CONTRATO TESTE:
		CONTRATO TEST NO ACESSO 021/168951997 (CONECTADO)  e 021/180907227
		site loga com e-mail: renanx@me.com renanx@gmail.com
		no app com cpf: 22484340818
	
	MUDANÇAS:
		
--====================================================================================================================================================================================
*/

DROP TABLE TMP_SQDAA_DTH_RET_P1;
CREATE TABLE TMP_SQDAA_DTH_RET_P1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel (32)*/ ----------------------------------------------------------------------------------------------ETAPA 1 BASE DE LIGACOES
	TO_DATE(
      ADD_MONTHS(
              LAST_DAY(TO_DATE(&&DT_MOVIMENTO, 'YYYYMMDD')),-1)+1,'DD/MM/YYYY') AS DAT_MOVIMENTO
	,'CTV' AS NM_MARCA
	,LIG.CD_CIDADE_CONTRATO
	,LIG.NR_CONTRATO AS NUM_CONTRATO
    ,LIG.SK_DATA
	,LIG.DH_LIGACAO AS DT_INI_LIGACAO
    ,TO_CHAR(LIG.NR_CONTRATO,'000000000') ||' '|| REPLACE(TO_CHAR(LIG.DH_LIGACAO,'yyyymmdd hh24:mi:ss'),':','') AS SK_LIGA
		
FROM INN.ANALITICA_CR_BI_LIG_CTV LIG
WHERE 0 = 0
      AND LIG.SK_DATA BETWEEN 
		TO_NUMBER(
                  TO_CHAR(
                      (ADD_MONTHS(
                            LAST_DAY(
                                TO_DATE(&&DT_MOVIMENTO, 'YYYYMMDD')),-1)+1),'YYYYMMDD')) AND 
		TO_NUMBER(
            TO_CHAR(
                LAST_DAY(
                    TO_DATE(&&DT_MOVIMENTO, 'YYYYMMDD')),'YYYYMMDD')) 
      AND LIG.NR_CONTRATO IS NOT NULL          
;

DROP TABLE TMP_SQDAA_DTH_RET_P2A;
CREATE TABLE TMP_SQDAA_DTH_RET_P2A COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT   /*+parallel (32)*/ ----------------------------------------------------------------------------------------------ETAPA 3A BASE DE ACESSOS IDM 
  DISTINCT
    TO_DATE(
      ADD_MONTHS(
              LAST_DAY(TO_DATE(TRUNC(&&DT_MOVIMENTO), 'YYYYMMDD')),-1)+1,'DD/MM/YYYY') AS DAT_MOVIMENTO
    ,IDM.USER_ID AS LOGIN_AUTENTICA
    ,SUBSTR(TO_CHAR(IDM.EVENT_DATE, 'YYYYMMDD'),1,6) AS SAFRA
    ,IDM.SK_DATA
    ,IDM.EVENT_DATE
    ,TO_CHAR(REPLACE(TO_CHAR(IDM.EVENT_TIMESTAMP,'yyyymmdd hh24:mi:ss'),':','')) AS SK_EVENTO
    ,TO_CHAR(IDM.EVENT_DATE +1, 'YYYYMMDD') ||' '|| REPLACE(SUBSTR(TO_CHAR(IDM.EVENT_TIMESTAMP,'dd/mm/yyyy hh24:mi:ss'),12,8),':','') SK_EVENTO1
    ,TO_CHAR(IDM.EVENT_DATE +2, 'YYYYMMDD') ||' '|| REPLACE(SUBSTR(TO_CHAR(IDM.EVENT_TIMESTAMP,'dd/mm/yyyy hh24:mi:ss'),12,8),':','') SK_EVENTO2
    ,TO_CHAR(IDM.EVENT_DATE +3, 'YYYYMMDD') ||' '|| REPLACE(SUBSTR(TO_CHAR(IDM.EVENT_TIMESTAMP,'dd/mm/yyyy hh24:mi:ss'),12,8),':','') SK_EVENTO3
    ,TO_CHAR(IDM.EVENT_DATE +7, 'YYYYMMDD') ||' '|| REPLACE(SUBSTR(TO_CHAR(IDM.EVENT_TIMESTAMP,'dd/mm/yyyy hh24:mi:ss'),12,8),':','') SK_EVENTO7
    ,TO_CHAR(LAST_DAY(IDM.EVENT_DATE), 'YYYYMMDD') ||' '|| '235959' SK_EVENTO30
    --,TO_CHAR(IDM.EVENT_DATE +1, 'YYYYMMDD') SK_DATA1
    --,REPLACE(SUBSTR(TO_CHAR(IDM.EVENT_TIMESTAMP,'dd/mm/yyyy hh24:mi:ss'),12,8),':','') AS HORA
    ,SYSDATE                       AS DAT_CRIACAO
FROM INN.DW_IDM_LOG IDM  
WHERE 0 = 0
    AND TRUNC(IDM.EVENT_TIMESTAMP) BETWEEN 
        add_months(LAST_DAY(TO_DATE(&&DT_MOVIMENTO, 'YYYYMMDD')),-1)+1
            AND 
              LAST_DAY(TO_DATE(&&DT_MOVIMENTO, 'YYYYMMDD')) 
    AND IDM.EVENT_NAME = 'TOKEN_SUCCESS'
    AND UPPER(IDM.CLIENT_ID) IN ('NETAPP','CLAROTV_WCP_PROD','MINHA_NET_WCP')
    AND UPPER(IDM.USER_ID) IN (SELECT UPPER(ds_email) AS LOGIN_AUTENTICA FROM INN.DW_ASSINANTE_CTV WHERE ds_email IS NOT NULL
                        UNION ALL
                        SELECT TO_CHAR(nr_cpf_cnpj_assinante) AS LOGIN_AUTENTICA FROM INN.DW_ASSINANTE_CTV WHERE nr_cpf_cnpj_assinante IS NOT NULL
                        UNION ALL
                        SELECT UPPER(REPLACE(REGEXP_SUBSTR (ds_email,'^.*@'),'@','')) AS LOGIN_AUTENTICA FROM INN.DW_ASSINANTE_CTV WHERE ds_email IS NOT NULL
                        UNION ALL
                        SELECT TO_CHAR(nr_contrato) AS LOGIN_AUTENTICA FROM INN.DW_ASSINANTE_CTV  WHERE nr_contrato IS NOT NULL)

;
DROP TABLE TMP_SQDAA_DTH_RET_P2B;
CREATE TABLE TMP_SQDAA_DTH_RET_P2B COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT   /*+parallel (32)*/ ----------------------------------------------------------------------------------------------ETAPA 3B ACESSO SITE
  DISTINCT
		TO_DATE(
      ADD_MONTHS(
              LAST_DAY(TO_DATE(TRUNC(&&DT_MOVIMENTO), 'YYYYMMDD')),-1)+1,'DD/MM/YYYY') AS DAT_MOVIMENTO
	,CD.NR_CONTRATO AS NUM_CONTRATO
    ,CD.NR_CPF_CNPJ_ASSINANTE AS NUM_CPF_CNPJ
	,1  AS FL_ACESSO
    ,'SITE MCR CTV' AS CANAL_ATD
    ,'CPF_CNPJ' AS TP_AUTENTICACAO
	,IDM.SAFRA
	,IDM.SK_DATA
	,IDM.EVENT_DATE
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO AS SK_ACESSO
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO1 AS SK_ACESSO1
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO2 AS SK_ACESSO2
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO3 AS SK_ACESSO3
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO7 AS SK_ACESSO7
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO30 AS SK_ACESSO30
FROM INN.DW_ASSINANTE_CTV CD
INNER JOIN TMP_SQDAA_DTH_RET_P2A IDM ON TO_CHAR(CD.nr_cpf_cnpj_assinante) = IDM.LOGIN_AUTENTICA

UNION ALL

SELECT   /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 3B ACESSO SITE
  DISTINCT
		TO_DATE(
      ADD_MONTHS(
              LAST_DAY(TO_DATE(TRUNC(&&DT_MOVIMENTO), 'YYYYMMDD')),-1)+1,'DD/MM/YYYY') AS DAT_MOVIMENTO
	,CD.NR_CONTRATO AS NUM_CONTRATO
    ,CD.NR_CPF_CNPJ_ASSINANTE AS NUM_CPF_CNPJ
	,1  AS FL_ACESSO
    ,'SITE MCR CTV' AS CANAL_ATD
    ,'EMAIL' AS TP_AUTENTICACAO
	,IDM.SAFRA
	,IDM.SK_DATA
	,IDM.EVENT_DATE
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO AS SK_ACESSO
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO1 AS SK_ACESSO1
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO2 AS SK_ACESSO2
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO3 AS SK_ACESSO3
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO7 AS SK_ACESSO7
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO30 AS SK_ACESSO30
FROM INN.DW_ASSINANTE_CTV CD
INNER JOIN TMP_SQDAA_DTH_RET_P2A IDM ON UPPER(TO_CHAR(CD.DS_EMAIL)) = UPPER(IDM.LOGIN_AUTENTICA)

UNION ALL

SELECT   /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 3B ACESSO SITE
  DISTINCT
		TO_DATE(
      ADD_MONTHS(
              LAST_DAY(TO_DATE(TRUNC(&&DT_MOVIMENTO), 'YYYYMMDD')),-1)+1,'DD/MM/YYYY') AS DAT_MOVIMENTO
	,CD.NR_CONTRATO AS NUM_CONTRATO
    ,CD.NR_CPF_CNPJ_ASSINANTE AS NUM_CPF_CNPJ
	,1  AS FL_ACESSO
    ,'SITE MCR CTV' AS CANAL_ATD
    ,'CONTRATO' AS TP_AUTENTICACAO
	,IDM.SAFRA
	,IDM.SK_DATA
	,IDM.EVENT_DATE
    ,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO AS SK_ACESSO
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO1 AS SK_ACESSO1
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO2 AS SK_ACESSO2
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO3 AS SK_ACESSO3
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO7 AS SK_ACESSO7
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO30 AS SK_ACESSO30
FROM INN.DW_ASSINANTE_CTV CD
INNER JOIN TMP_SQDAA_DTH_RET_P2A IDM ON TO_CHAR(CD.NR_CONTRATO) = IDM.LOGIN_AUTENTICA

UNION ALL 

SELECT   /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 3B ACESSO SITE
  DISTINCT
		TO_DATE(
      ADD_MONTHS(
              LAST_DAY(TO_DATE(TRUNC(&&DT_MOVIMENTO), 'YYYYMMDD')),-1)+1,'DD/MM/YYYY') AS DAT_MOVIMENTO
    ,CD.NR_CONTRATO AS NUM_CONTRATO
    ,CD.NR_CPF_CNPJ_ASSINANTE AS NUM_CPF_CNPJ
    ,1  AS FL_ACESSO
    ,'SITE MCR CTV' AS CANAL_ATD
    ,'USERNAME' AS TP_AUTENTICACAO
	,IDM.SAFRA
	,IDM.SK_DATA
	,IDM.EVENT_DATE
    ,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO AS SK_ACESSO
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO1 AS SK_ACESSO1
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO2 AS SK_ACESSO2
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO3 AS SK_ACESSO3
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO7 AS SK_ACESSO7
	,TO_CHAR(CD.NR_CONTRATO,'000000000') ||' '||IDM.SK_EVENTO30 AS SK_ACESSO30
FROM INN.DW_ASSINANTE_CTV CD
INNER JOIN TMP_SQDAA_DTH_RET_P2A IDM ON UPPER(REPLACE(REGEXP_SUBSTR (CD.ds_email,'^.*@'),'@','')) = UPPER(IDM.LOGIN_AUTENTICA)
;

--ETAPA 3.0 D0
DROP TABLE TMP_SQDAA_DTH_RET_P3A; 
CREATE TABLE TMP_SQDAA_DTH_RET_P3A COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT  /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3.1 ACESSO COM CR
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.EVENT_DATE > CR.DT_INI_LIGACAO THEN 1 ELSE 0 END FLG_ACESSA_LIGA 
     ,CASE WHEN AC.EVENT_DATE > CR.DT_INI_LIGACAO THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE 
       ,1 AS QT_REF
FROM TMP_SQDAA_DTH_RET_P2B AC -- 
INNER JOIN TMP_SQDAA_DTH_RET_P1 CR ON AC.NUM_CONTRATO = CR.NUM_CONTRATO -- cr
      AND TRUNC(AC.EVENT_DATE) = TRUNC(CR.DT_INI_LIGACAO) ---------->>>>> SOMENTE D+0  
ORDER BY  AC.SK_ACESSO
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 3.1 24H APOS O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P3B;
CREATE TABLE TMP_SQDAA_DTH_RET_P3B COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 24H APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO1 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO1 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 1' AS DSC_SAFRA
       ,1 AS QT_REF
FROM TMP_SQDAA_DTH_RET_P2B AC -- 
INNER JOIN TMP_SQDAA_DTH_RET_P1 CR ON AC.NUM_CONTRATO = CR.NUM_CONTRATO -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.EVENT_DATE) AND TRUNC(AC.EVENT_DATE)+1 ---- 24H APOS O ACESSO
ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
;


--ETAPA 3.2 48H APOS O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P3C;
CREATE TABLE TMP_SQDAA_DTH_RET_P3C COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 48H APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO2 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO2 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 2' AS DSC_SAFRA
	   ,1 AS QT_REF
       
FROM TMP_SQDAA_DTH_RET_P2B AC -- WPP
INNER JOIN TMP_SQDAA_DTH_RET_P1 CR ON AC.NUM_CONTRATO = CR.NUM_CONTRATO -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.EVENT_DATE) AND TRUNC(AC.EVENT_DATE)+2 ---- 48H APOS O ACESSO

ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
;

--ETAPA 3.3 72H APOS O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P3D;
CREATE TABLE TMP_SQDAA_DTH_RET_P3D COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 72H APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO3 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO3 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 3' AS DSC_SAFRA
        ,1 AS QT_REF
FROM TMP_SQDAA_DTH_RET_P2B AC -- 
INNER JOIN TMP_SQDAA_DTH_RET_P1 CR ON AC.NUM_CONTRATO = CR.NUM_CONTRATO -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.EVENT_DATE) AND TRUNC(AC.EVENT_DATE)+3 ---- 72H APOS O ACESSO
ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 3.4 7 DIAS APOS O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P3E;
CREATE TABLE TMP_SQDAA_DTH_RET_P3E COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 7 DIAS APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO7 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO7 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 7' AS DSC_SAFRA
       ,1 AS QT_REF
FROM TMP_SQDAA_DTH_RET_P2B AC -- 
INNER JOIN TMP_SQDAA_DTH_RET_P1 CR ON AC.NUM_CONTRATO = CR.NUM_CONTRATO -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.EVENT_DATE) AND TRUNC(AC.EVENT_DATE)+7 ---- 7 DIAS APOS O ACESSO
ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 3.5 DENTRO DO MÊS DE O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P3F;
CREATE TABLE TMP_SQDAA_DTH_RET_P3F COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 DENTRO DO MÊS DE ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
--       ,AC.SK_ACESSO30
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1 
             WHEN CR.SK_LIGA BETWEEN AC.SK_ACESSO AND AC.SK_ACESSO30 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA 
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA BETWEEN AC.SK_ACESSO AND AC.SK_ACESSO30 THEN 'ACESSOU E LIGOU' ELSE  'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'DM0' AS DSC_SAFRA
       ,1 AS QT_REF
FROM TMP_SQDAA_DTH_RET_P2B AC -- WPP
INNER JOIN TMP_SQDAA_DTH_RET_P1 CR ON AC.NUM_CONTRATO = CR.NUM_CONTRATO -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.EVENT_DATE) AND TRUNC(LAST_DAY(AC.EVENT_DATE)) ---- DENTRO DO MÊS DE ACESSO

ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
; 


/*--======================================================--======================================================
			VALIDAÇÃO: SET/2020
 
 
 
SELECT '1 ACSS' AS TP  ,EVENT_DATE AS DT ,SK_ACESSO AS SK FROM TMP_SQDAA_DTH_RET_P2B 
WHERE NUM_CONTRATO = 101361257 
UNION ALL 

SELECT '2 LIGA' AS TP ,DT_INI_LIGACAO AS DT ,SK_LIGA AS SK FROM TMP_SQDAA_DTH_RET_P1 
WHERE NUM_CONTRATO = 101361257 ;

-- VALIDAÇÃO
 -- 101350352 20200930 193748 RETIDO DIGITAL -- CORRETO D0
 -- 101361257 20200910 191359 ACESSOU E LIGOU -- CORRETO D0

-- VALIDAÇÃO - D1
 --  000015137 20200928 095510 ACESSOU E LIGOU -- CORRETO D1
 --  000026872 20200919 111954 ACESSOU E LIGOU -- CORRETO D1
 --   000038480 20200915 103737 ACESSOU E LIGOU -- CORRETO D1
 --  000026872 20200919 174738 RETIDO DIGITAL -- CORRETO D1

-- VALIDAÇÃO - D2
 --   143641616 20200915 183222 RETIDO DIGITAL -- CORRETO D2
 --    143641616 20200915 183222 ACESSOU E LIGOU -- **** VERIFICAR
--======================================================--======================================================*/
--ETAPA 4B 24H APOS O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P4A;
CREATE TABLE TMP_SQDAA_DTH_RET_P4A COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 0' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1  ELSE 0 END AS FLG_ACESSA_LIGA
FROM TMP_SQDAA_DTH_RET_P2B        A
LEFT 
JOIN TMP_SQDAA_DTH_RET_P3A   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = 0
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO	,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
        ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1 ELSE 0 END
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 0' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 	  TMP_SQDAA_DTH_RET_P2B        A
LEFT JOIN TMP_SQDAA_DTH_RET_P3A   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = QT_REF 
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO ,A.NUM_CONTRATO	,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END	
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
   'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 0' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 			TMP_SQDAA_DTH_RET_P2B        A
LEFT OUTER JOIN TMP_SQDAA_DTH_RET_P3A   RET         ON A.SK_ACESSO = RET.SK_ACESSO 
WHERE 0 = 0  AND RET.SK_ACESSO IS NULL
GROUP BY A.DAT_MOVIMENTO, A.SAFRA ,A.EVENT_DATE ,A.SK_DATA  ,A.SK_ACESSO ,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END  
;  

--======================================================--======================================================*/
--ETAPA 4B 24H APOS O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P4B;
CREATE TABLE TMP_SQDAA_DTH_RET_P4B COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 1' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1  ELSE 0 END AS FLG_ACESSA_LIGA
FROM TMP_SQDAA_DTH_RET_P2B        A
LEFT 
JOIN TMP_SQDAA_DTH_RET_P3B   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = 0
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO	,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
        ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1 ELSE 0 END
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 1' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 	  TMP_SQDAA_DTH_RET_P2B        A
LEFT JOIN TMP_SQDAA_DTH_RET_P3B   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = QT_REF 
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO ,A.NUM_CONTRATO	,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END	
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
   'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 1' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 			TMP_SQDAA_DTH_RET_P2B        A
LEFT OUTER JOIN TMP_SQDAA_DTH_RET_P3B   RET         ON A.SK_ACESSO = RET.SK_ACESSO 
WHERE 0 = 0  AND RET.SK_ACESSO IS NULL
GROUP BY A.DAT_MOVIMENTO, A.SAFRA ,A.EVENT_DATE ,A.SK_DATA  ,A.SK_ACESSO ,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END  
;  
--======================================================--======================================================*/
--ETAPA 4C 48H APOS O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P4C;
CREATE TABLE TMP_SQDAA_DTH_RET_P4C COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 2' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1  ELSE 0 END AS FLG_ACESSA_LIGA
FROM TMP_SQDAA_DTH_RET_P2B        A
LEFT 
JOIN TMP_SQDAA_DTH_RET_P3C   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = 0
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO	,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
        ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1 ELSE 0 END
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 2' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 	  TMP_SQDAA_DTH_RET_P2B        A
LEFT JOIN TMP_SQDAA_DTH_RET_P3C   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = QT_REF 
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO ,A.NUM_CONTRATO	,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END	
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
   'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 2' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 			TMP_SQDAA_DTH_RET_P2B        A
LEFT OUTER JOIN TMP_SQDAA_DTH_RET_P3C   RET         ON A.SK_ACESSO = RET.SK_ACESSO 
WHERE 0 = 0  AND RET.SK_ACESSO IS NULL
GROUP BY A.DAT_MOVIMENTO, A.SAFRA ,A.EVENT_DATE ,A.SK_DATA  ,A.SK_ACESSO ,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END  
;  

--======================================================--======================================================*/
--ETAPA 4D 72H APOS O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P4D;
CREATE TABLE TMP_SQDAA_DTH_RET_P4D COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 3' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1  ELSE 0 END AS FLG_ACESSA_LIGA
FROM TMP_SQDAA_DTH_RET_P2B        A
LEFT 
JOIN TMP_SQDAA_DTH_RET_P3D   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = 0
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO	,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
        ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1 ELSE 0 END
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 3' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 	  TMP_SQDAA_DTH_RET_P2B        A
LEFT JOIN TMP_SQDAA_DTH_RET_P3D   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = QT_REF 
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO ,A.NUM_CONTRATO	,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END	
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
   'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 3' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 			TMP_SQDAA_DTH_RET_P2B        A
LEFT OUTER JOIN TMP_SQDAA_DTH_RET_P3D   RET         ON A.SK_ACESSO = RET.SK_ACESSO 
WHERE 0 = 0  AND RET.SK_ACESSO IS NULL
GROUP BY A.DAT_MOVIMENTO, A.SAFRA ,A.EVENT_DATE ,A.SK_DATA  ,A.SK_ACESSO ,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END  
; 

--======================================================--======================================================*/
--ETAPA 4E 7DIAS APOS O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P4E;
CREATE TABLE TMP_SQDAA_DTH_RET_P4E COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 7' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1  ELSE 0 END AS FLG_ACESSA_LIGA
FROM TMP_SQDAA_DTH_RET_P2B        A
LEFT 
JOIN TMP_SQDAA_DTH_RET_P3E   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = 0
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO	,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
        ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1 ELSE 0 END
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 7' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 	  TMP_SQDAA_DTH_RET_P2B        A
LEFT JOIN TMP_SQDAA_DTH_RET_P3E   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = QT_REF 
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO ,A.NUM_CONTRATO	,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END	
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
   'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'D 7' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 			TMP_SQDAA_DTH_RET_P2B        A
LEFT OUTER JOIN TMP_SQDAA_DTH_RET_P3E   RET         ON A.SK_ACESSO = RET.SK_ACESSO 
WHERE 0 = 0  AND RET.SK_ACESSO IS NULL
GROUP BY A.DAT_MOVIMENTO, A.SAFRA ,A.EVENT_DATE ,A.SK_DATA  ,A.SK_ACESSO ,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END  
;  
--======================================================--======================================================*/
--ETAPA 4F DENTRO APOS O ACESSO
DROP TABLE TMP_SQDAA_DTH_RET_P4F;
CREATE TABLE TMP_SQDAA_DTH_RET_P4F COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'M 0' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1  ELSE 0 END AS FLG_ACESSA_LIGA
FROM TMP_SQDAA_DTH_RET_P2B        A
LEFT 
JOIN TMP_SQDAA_DTH_RET_P3F   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = 0
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO	,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
        ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = 1 THEN 1 ELSE 0 END
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
    'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'M 0' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 	  TMP_SQDAA_DTH_RET_P2B        A
LEFT JOIN TMP_SQDAA_DTH_RET_P3F   RET         ON A.SK_ACESSO = RET.SK_ACESSO
WHERE 0 = 0  AND RET.FLG_ACESSA_LIGA = QT_REF 
GROUP BY A.DAT_MOVIMENTO ,A.SAFRA ,A.EVENT_DATE ,A.SK_DATA ,A.SK_ACESSO ,A.NUM_CONTRATO	,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF THEN 'RETIDO DIGITAL' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL OR RET.FLG_ACESSA_LIGA = RET.QT_REF  THEN 1 ELSE 0 END	
UNION ALL
SELECT /*+parallel(32) */
  DISTINCT
   'CTV' AS NM_MARCA
    ,'MCR SITE APP' AS DSC_METODO_CONTATO
    ,A.DAT_MOVIMENTO
    ,A.SAFRA
    ,A.EVENT_DATE
	,A.SK_DATA 
	,A.SK_ACESSO 
	,A.NUM_CONTRATO
	,A.NUM_CPF_CNPJ
    ,'M 0' AS DSC_SAFRA
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END AS DSC_VISAO_ANALISE
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
FROM 			TMP_SQDAA_DTH_RET_P2B        A
LEFT OUTER JOIN TMP_SQDAA_DTH_RET_P3F   RET         ON A.SK_ACESSO = RET.SK_ACESSO 
WHERE 0 = 0  AND RET.SK_ACESSO IS NULL
GROUP BY A.DAT_MOVIMENTO, A.SAFRA ,A.EVENT_DATE ,A.SK_DATA  ,A.SK_ACESSO ,A.NUM_CONTRATO ,A.NUM_CPF_CNPJ
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 'SOMENTE ACESSA' ELSE 'ACESSA LIGA' END
    ,CASE WHEN RET.SK_ACESSO IS NULL THEN 1 ELSE 0 END  
; 

INSERT /*+APPEND */ INTO AGG_RET_DIG_MCR_DTH ------------------------------------------------------------------------ETAPA 8 TABELA AGREGADA
--DROP TABLE AGG_RET_DIG_MCR_DTH; 
--CREATE TABLE AGG_RET_DIG_MCR_DTH COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT 
  A.DAT_MOVIMENTO ,'1 BASE ACESSO' AS DSC_SAFRA ,'1 BASE ACESSO' AS DSC_VISAO_ANALISE ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO ,SYSDATE AS DAT_CRIACAO
FROM TMP_SQDAA_DTH_RET_P2B A 
GROUP BY A.DAT_MOVIMENTO 
UNION ALL
SELECT DISTINCT
  A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO ,SYSDATE AS DAT_CRIACAO
FROM TMP_SQDAA_DTH_RET_P4A A 
GROUP BY A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE
UNION ALL
SELECT DISTINCT
  A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO ,SYSDATE AS DAT_CRIACAO
FROM TMP_SQDAA_DTH_RET_P4B A 
GROUP BY A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE
UNION ALL
SELECT DISTINCT
  A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO ,SYSDATE AS DAT_CRIACAO
FROM TMP_SQDAA_DTH_RET_P4C A 
GROUP BY A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE
UNION ALL
SELECT DISTINCT
  A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO ,SYSDATE AS DAT_CRIACAO
FROM TMP_SQDAA_DTH_RET_P4D A 
GROUP BY A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE
UNION ALL
SELECT DISTINCT
  A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO ,SYSDATE AS DAT_CRIACAO
FROM TMP_SQDAA_DTH_RET_P4E A 
GROUP BY A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE
UNION ALL
SELECT DISTINCT
  A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO ,SYSDATE AS DAT_CRIACAO
FROM TMP_SQDAA_DTH_RET_P4F A 
GROUP BY A.DAT_MOVIMENTO ,A.DSC_SAFRA ,A.DSC_VISAO_ANALISE
;
COMMIT;



/*			VALIDAÇÃO

/*OK*/--AND A.sk_acesso LIKE '%143641616 20200915 183222%' --- ACESSOU E LIGOU QT_REF 3X 
/*OK*/--  AND A.sk_acesso LIKE '%149999539 20200921 164749%' -- ACESSOU E LIGOU QT_REF 1X 
       -- AND A.sk_acesso LIKE '%143641616 20200929 081238%' --- RETIDO DIGITAL QT_REF 1X "LIGAÇÃO OCORREU ANTES ' 143641616 20200929 080610'"
/*OK*/--  AND A.sk_acesso LIKE '%142353250 20200926 102928%' --- ACESSOU E LIGOU QT_REF 2X
--AND A.SK_ACESSO LIKE '%069166153 20200918 172310%' --- LIGAÇÕES FORAM ANTES ACESSO QT_REF 3X


------*********************** COMPARATIVO
SELECT DISTINCT 
  'BASE GERAL DE ACESSO' AS TP_BASE ,A.DAT_MOVIMENTO ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO
FROM TMP_SQDAA_DTH_RET_P2B A 
GROUP BY A.DAT_MOVIMENTO
UNION ALL
SELECT DISTINCT
  'BASE RETIDO SAFRA D 0' AS TP_BASE ,A.DAT_MOVIMENTO ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO
FROM TMP_SQDAA_DTH_RET_P4A A 
GROUP BY A.DAT_MOVIMENTO
UNION ALL
SELECT DISTINCT
  'BASE RETIDO SAFRA D 1' AS TP_BASE ,A.DAT_MOVIMENTO ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO
FROM TMP_SQDAA_DTH_RET_P4B A 
GROUP BY A.DAT_MOVIMENTO
UNION ALL
SELECT DISTINCT
  'BASE RETIDO SAFRA D 2' AS TP_BASE ,A.DAT_MOVIMENTO ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO
FROM TMP_SQDAA_DTH_RET_P4C A 
GROUP BY A.DAT_MOVIMENTO
UNION ALL
SELECT DISTINCT
  'BASE RETIDO SAFRA D 3' AS TP_BASE ,A.DAT_MOVIMENTO ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO
FROM TMP_SQDAA_DTH_RET_P4D A 
GROUP BY A.DAT_MOVIMENTO
UNION ALL
SELECT DISTINCT
  'BASE RETIDO SAFRA D 7' AS TP_BASE ,A.DAT_MOVIMENTO ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO
FROM TMP_SQDAA_DTH_RET_P4E A 
GROUP BY A.DAT_MOVIMENTO
UNION ALL
SELECT DISTINCT
  'BASE RETIDO SAFRA M 0' AS TP_BASE ,A.DAT_MOVIMENTO ,COUNT(DISTINCT(A.SK_ACESSO)) AS QT_ACESSO ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO
FROM TMP_SQDAA_DTH_RET_P4F A 
GROUP BY A.DAT_MOVIMENTO
;
BASE GERAL DE ACESSO	01/09/20	1632734	453282	375181
BASE RETIDO SAFRA D 0	01/09/20	1632734	453282	375181
BASE RETIDO SAFRA D 1	01/09/20	1632734	453282	375181
BASE RETIDO SAFRA D 2	01/09/20	1632734	453282	375181
BASE RETIDO SAFRA D 3	01/09/20	1632734	453282	375181
BASE RETIDO SAFRA D 7	01/09/20	1632734	453282	375181
BASE RETIDO SAFRA M 0	01/09/20	1632734	453282	375181               




SELECT A.* 
FROM TMP_SQDAA_DTH_RET_P2B A
WHERE A.sk_acesso NOT IN (SELECT DISTINCT B.SK_ACESSO FROM TMP_SQDAA_DTH_RET_P4C B GROUP BY B.SK_ACESSO);

SELECT DISTINCT 
  'BASE GERAL DE ACESSO' AS TP_BASE
  ,A.DAT_MOVIMENTO 
  ,COUNT(A.NUM_CONTRATO) AS QT_CTR 
  ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO 
  ,COUNT(A.NUM_CPF_CNPJ) AS QT_CPF_CNPJ 
  ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO
    FROM TMP_SQDAA_DTH_RET_P2B A 
GROUP BY A.DAT_MOVIMENTO
UNION ALL
SELECT DISTINCT
  'BASE RETIDO SAFRA D 1' AS TP_BASE
  ,A.DAT_MOVIMENTO 
  ,COUNT(A.NUM_CONTRATO) AS QT_CTR 
  ,COUNT(DISTINCT(A.NUM_CONTRATO)) AS QT_CTR_UNICO 
  ,COUNT(A.NUM_CPF_CNPJ) AS QT_CPF_CNPJ 
  ,COUNT(DISTINCT(A.NUM_CPF_CNPJ)) AS QT_CPF_CNPJ_UNICO
    FROM TMP_SQDAA_DTH_RET_P4B A 
GROUP BY A.DAT_MOVIMENTO;

BASE GERAL DE ACESSO	01/09/20	1632742	453282	1632742	375181
BASE RETIDO SAFRA D 1	01/09/20	1638485	453282	1638485	375181

*/
