
/*---===========================================================================================================================
Ação: Retido Digital USSD 
Inicio: 13/05/20
objetivo: RETENÇÃO NO ATENDIMENTO DO CANAL  

TABELAS:
          
CONCEITO:

  O RETIDO DIGITAL DO WHATSAPP CONSISTE EM IDENTIFICAR APÓS O ACESSO SE O CLIENTE LIGOU NA CENTRAL DE ATENDIMENTO OU O CLIENTES SEGUIU NO FLUXO DO TRANSBORDO HUMANO, O QUAL 
  ESTE TRANSBORDO HUMANO ERA TRABALHADO PELO FORNCEDOR TEL_BLIP (ANALISE DE ABRIL/2020);
  ANALISAMOS O RETIDO DIGITAL DO WHATSAPP QUANDO O CLIENTE LIGA NO MESMO DIA (SAFRA D0) OU EM D+1 (SAFRA 24HORAS) OU EM D+2 (SAFRA 48HORAS) OU EM D+3 (SAFRA 72HORAS) 
  OU EM D+7 (SAFRA ACESSO E LIGAÇÃO APÓS 7 DIAS) OU EM D+30 (SAFRA ACESSO E DENTRO DO MÊS);
  
PROBLEMAS NA BASE:
  
  NA BASE DO MINT POSSUEM CLIENTES RESIDENCIAS ONDE NÃO HÁ CÓDIGO DE PLATAFORMA OU NTC, ESTES CLIENTES SÃO EXPURGADOS DA ANALISE;
  POSSUEM TAMBÉM CLIENTE COM DDI OU NÚMEROS INTERNACIONAIS O QUAL NÃO CONSIGO IDENTIFICAR COMO CLIENTE;

INSTRUÇÕES:
  COD_SHORT_CODE = '1052' -->CODIGO DOS CLIENTES QUE ACESSAM O WHATS APP
  COD_LOGIN_ATEND_CRIACAO = 'USSD'
         
RELAÇÃO DE CLIENTES UTILIZADOS PARA TESTE:


---===========================================================================================================================*/

DROP TABLE TMP_SQDAA_USSD_RET_P1;
DROP TABLE TMP_SQDAA_USSD_RET_P2;
DROP TABLE TMP_SQDAA_USSD_RET_P3A;
DROP TABLE TMP_SQDAA_USSD_RET_P3B;
DROP TABLE TMP_SQDAA_USSD_RET_P3C;
DROP TABLE TMP_SQDAA_USSD_RET_P3D;
DROP TABLE TMP_SQDAA_USSD_RET_P3E;
DROP TABLE TMP_SQDAA_USSD_RET_P3F;
DROP TABLE TMP_RET_DIGITAL_USSD0;
DROP TABLE TMP_RET_DIGITAL_USSD1;
DROP TABLE TMP_RET_DIGITAL_USSD2;
DROP TABLE TMP_RET_DIGITAL_USSD3;
DROP TABLE TMP_RET_DIGITAL_USSD7;
DROP TABLE TMP_RET_DIGITAL_USSD30;
DROP TABLE TMP_RET_DIG_USSD_DTREF;
DROP TABLE BI_FT_RET_DIG_USSD;

--ETAPA 1 ACESSO USSD
DROP TABLE TMP_SQDAA_USSD_RET_P1;
CREATE TABLE TMP_SQDAA_USSD_RET_P1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 1 ACESSO USSD
        A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6) AS SAFRA --ok
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') AS SK_DATA --ok
        ,A.COD_PLATAFORMA --ok
        ,A.NUM_NTC --ok
        ,A.DAT_INICIO_ATENDIMENTO AS DT_INI_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,A.COD_ATENDIMENTO
        ,A.DW_NUM_CANAL_MINT
        ,A.NUM_PROTOCOLO
        ,TRUNC(A.DAT_INICIO_ATENDIMENTO) AS DAT_INICIO_ATENDIMENTO --ok
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO+1, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO1
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO+2, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO2
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO+3, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO3
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO+7, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO7        
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(LAST_DAY(A.DAT_INICIO_ATENDIMENTO), 'YYYYMMDD') ||' '||'235959') AS SK_ACESSO30        
    ,SYSDATE                       AS DAT_CRIACAO
 
FROM DWH.BI_FP_ATENDIMENTO_MINT A
     
WHERE A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&&DATA_FINAL, 'RRRRMMDD')
AND A.COD_SHORT_CODE = 1052 --- SHORT CODE USSD
AND A.COD_PLATAFORMA NOT IN ('-2','-3') -->SOMENTE CLIENTES CLARO
AND A.DW_NUM_CANAL_MINT = 2 --> CANAL USSD VER NA TABELA VER TABELA "DWH.BI_DIM_CANAL_MINT"
AND A.NUM_PROTOCOLO IS NOT NULL --> SOMENTE ACESSOS QUE POSSUEM PROTOCOLOS

GROUP BY  A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6)
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD')
        ,A.COD_PLATAFORMA
        ,A.NUM_NTC
        ,A.DAT_INICIO_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,A.COD_ATENDIMENTO
        ,A.DW_NUM_CANAL_MINT 
        ,A.NUM_PROTOCOLO     
;
SELECT COD_PLATAFORMA ,COUNT(DISTINCT(NUM_NTC)) QT_UU ,COUNT(DISTINCT(SK_ACESSO)) QT_ACESSO FROM TMP_SQDAA_USSD_RET_P1 GROUP BY COD_PLATAFORMA;

--ETAPA 2 LIGACOES CR
DROP TABLE TMP_SQDAA_USSD_RET_P2;
CREATE TABLE TMP_SQDAA_USSD_RET_P2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+ PARALLEL (32)*/ ------------------------------------------------------------------------ETAPA 2 LIGACOES CR
       LAST_DAY(TO_DATE(FT.DT_INICIO_LIGACAO,'YYYY/MM/DD')) AS DAT_REFERENCIA       
       ,FT.DT_INICIO_LIGACAO SK_DATA       
       ,'CMV' AS NM_MARCA
       ,FT.SK_ATENDIMENTO_URA AS COD_CHAMADA -- CALL_ID
       ,TO_CHAR(FT.CD_NUMERO_TELEFONE ||' '||FT.DT_INICIO_LIGACAO ||' '||FT.NR_HORA_INICIO_LIGACAO) AS SK_LIGA
       ,TO_DATE(TO_DATE(FT.DT_INICIO_LIGACAO,'YYYY/MM/DD') ||' ' ||FT.NR_HORA_INICIO_LIGACAO,'DD/MM/RRRR HH24:MI:SS') AS DT_INI_LIGACAO
       ,TO_DATE(TO_DATE(FT.DT_FIM_LIGACAO,'YYYY/MM/DD') ||' ' ||FT.NR_HORA_FIM_LIGACAO,'DD/MM/RRRR HH24:MI:SS') AS DT_FIM_LIGACAO
       ,FT.CD_NUMERO_TELEFONE                           AS NUM_NTC
       ,CASE
         WHEN FT.FN_LIGACAO_IDENTIFICADA = 1 THEN
          'SIM'
         ELSE
          'NAO'
       END                                AS FLG_LIG_IDENTIFICADA
       ,STS.COD_SUB_STS_ATU DSC_STS_CLIENTE
       ,CASE
         WHEN FT.FN_CORPORATIVO = 1 THEN
          'SIM'
         ELSE
          'NAO'
       END                               AS FLG_CORPORATIVO
       ,CASE
         WHEN VA.NM_VISAO_ANALISE_BI = 'CONTACT RATE DIRECIONADO AO HUMANO' THEN
          'DIRECIONADO HUMANO'
         ELSE
          'RETIDO URA'
       END                           AS DSC_DIRECIONADO_RETIDO
       ,ATM.NM_TIPO_MOTIVO_BI         AS DSC_MOTIVO_URA
       ,STM.NM_SUB_TIPO_MOTIVO_BI     AS DSC_SUB_MOTIVO_URA
       ,ATL.NM_TIPO_LIGACAO_BI        AS DSC_EXPURGO_URA
       ,PP.DSC_PLANO_PRECO_BI         AS DSC_PLANO_CLIENTE
       ,SYSDATE                       AS DAT_CRIACAO

  FROM INTMKT.FT_ATENDIMENTO_URA FT -- OK
  LEFT JOIN DWH.BI_DIM_STATUS STS -- OK
    ON STS.STS_DW = FT.SK_STATUS
  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_MOTIVO ATM -- OK
    ON ATM.SK_ATENDIMENTO_TIPO_MOTIVO = FT.SK_ATENDIMENTO_TIPO_MOTIVO

  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_LIGACAO ATL -- OK
    ON ATL.SK_ATENDIMENTO_TIPO_LIGACAO = FT.SK_ATENDIMENTO_TIPO_LIGACAO
  LEFT JOIN DWH.BI_DIM_PLANO_PRECO PP -- OK
    ON PP.DW_PLANO = FT.SK_PLANO
  LEFT JOIN INTMKT.DS_ATENDIMENTO_SUB_TIPO_MOTIVO STM -- OK
   ON STM.SK_ATENDIMENTO_SUB_TIPO_MOTIVO =
       FT.SK_ATENDIMENTO_SUB_TIPO_MOTIVO
  LEFT JOIN INTMKT.DS_VISAO_ANALISE VA -- OK
    ON VA.SK_VISAO_ANALISE = FT.SK_VISAO_ANALISE
  LEFT JOIN intmkt.ds_atendimento_tipo_ligacao ATL 
ON        atl.sk_atendimento_tipo_ligacao = ft.sk_atendimento_tipo_ligacao 

WHERE FT.SK_DATA BETWEEN &&DATA_INICIAL AND &&DATA_FINAL
---AND       atl.nm_tipo_ligacao_bi = 'Ligações Válidas' -- FILTRO OK (SÃO CLIENTES QUE NÃO TIVERAM ABANDONO)
---AND va.nm_visao_analise_bi = 'Contact Rate Direcionado ao Humano' -- FILTRO OK
;

--ETAPA 3.0 D0
DROP TABLE TMP_SQDAA_USSD_RET_P3A; 
CREATE TABLE TMP_SQDAA_USSD_RET_P3A COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT  /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3.1 ACESSO COM CR
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.DT_INI_ATENDIMENTO > CR.DT_INI_LIGACAO THEN 1 ELSE 0 END FLG_ACESSA_LIGA 
     ,CASE WHEN AC.DT_INI_ATENDIMENTO > CR.DT_INI_LIGACAO THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE 
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_USSD_RET_P1 AC -- USSD
INNER JOIN TMP_SQDAA_USSD_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(AC.DT_INI_ATENDIMENTO) = TRUNC(CR.DT_INI_LIGACAO) ---------->>>>> SOMENTE D+0  
ORDER BY  AC.SK_ACESSO
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 3.1 24H APOS O ACESSO
DROP TABLE TMP_SQDAA_USSD_RET_P3B;
CREATE TABLE TMP_SQDAA_USSD_RET_P3B COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 24H APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO1 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO1 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 1' AS DSC_SAFRA
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_USSD_RET_P1 AC -- USSD
INNER JOIN TMP_SQDAA_USSD_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.DT_INI_ATENDIMENTO) AND TRUNC(AC.DT_INI_ATENDIMENTO)+1 ---- 24H APOS O ACESSO
ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
;


--ETAPA 3.2 48H APOS O ACESSO
DROP TABLE TMP_SQDAA_USSD_RET_P3C;
CREATE TABLE TMP_SQDAA_USSD_RET_P3C COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 48H APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO2 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO2 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 2' AS DSC_SAFRA
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_USSD_RET_P1 AC -- USSD
INNER JOIN TMP_SQDAA_USSD_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.DT_INI_ATENDIMENTO) AND TRUNC(AC.DT_INI_ATENDIMENTO)+2 ---- 48H APOS O ACESSO
ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
;

--ETAPA 3.3 72H APOS O ACESSO
DROP TABLE TMP_SQDAA_USSD_RET_P3D;
CREATE TABLE TMP_SQDAA_USSD_RET_P3D COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 72H APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO3 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO3 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 3' AS DSC_SAFRA
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_USSD_RET_P1 AC -- USSD
INNER JOIN TMP_SQDAA_USSD_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.DT_INI_ATENDIMENTO) AND TRUNC(AC.DT_INI_ATENDIMENTO)+3 ---- 72H APOS O ACESSO
ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 3.4 7 DIAS APOS O ACESSO
DROP TABLE TMP_SQDAA_USSD_RET_P3E;
CREATE TABLE TMP_SQDAA_USSD_RET_P3E COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 7 DIAS APOS O ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1
             WHEN CR.SK_LIGA < AC.SK_ACESSO7 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA < AC.SK_ACESSO7 THEN 'ACESSOU E LIGOU' ELSE 'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'D 7' AS DSC_SAFRA
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_USSD_RET_P1 AC -- USSD
INNER JOIN TMP_SQDAA_USSD_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.DT_INI_ATENDIMENTO) AND TRUNC(AC.DT_INI_ATENDIMENTO)+7 ---- 7 DIAS APOS O ACESSO
ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 3.5 DENTRO DO MÊS DE O ACESSO
DROP TABLE TMP_SQDAA_USSD_RET_P3F;
CREATE TABLE TMP_SQDAA_USSD_RET_P3F COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+parallel(32) */ ------------------------------------------------------------------------ETAPA 3 DENTRO DO MÊS DE ACESSO
       AC.SK_ACESSO
       ,CR.DT_INI_LIGACAO
--       ,AC.SK_ACESSO30
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 1 
             WHEN CR.SK_LIGA BETWEEN AC.SK_ACESSO AND AC.SK_ACESSO30 THEN 0 ELSE 1 END AS FLG_ACESSA_LIGA 
       ,CASE WHEN AC.SK_ACESSO > CR.SK_LIGA THEN 'RETIDO DIGITAL'
             WHEN CR.SK_LIGA BETWEEN AC.SK_ACESSO AND AC.SK_ACESSO30 THEN 'ACESSOU E LIGOU' ELSE  'RETIDO DIGITAL' END AS DSC_VISAO_ANALISE       
       ,'DM0' AS DSC_SAFRA
       ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_USSD_RET_P1 AC -- USSD
INNER JOIN TMP_SQDAA_USSD_RET_P2 CR ON AC.NUM_NTC = CR.NUM_NTC -- cr
      AND TRUNC(CR.DT_INI_LIGACAO) BETWEEN TRUNC(AC.DT_INI_ATENDIMENTO) AND TRUNC(LAST_DAY(AC.DT_INI_ATENDIMENTO)) ---- DENTRO DO MÊS DE ACESSO
ORDER BY  AC.SK_ACESSO 
          ,CR.DT_INI_LIGACAO
; 

--ETAPA 4.0 D0 ACESSO + CR 
DROP TABLE TMP_RET_DIGITAL_USSD0; -->OK    
CREATE TABLE TMP_RET_DIGITAL_USSD0 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT ------------------------------------------------------------------------ETAPA 5 ACESSO + CR + TRANSBORDO
        A.SK_ACESSO 
        ,A.SAFRA 
        ,A.NUM_NTC 
        ,A.SK_DATA 
        ,A.COD_PLATAFORMA 
        ,A.DAT_INICIO_ATENDIMENTO
        ,A.DT_INI_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,'USSD' AS DSC_METODO_CONTATO -->OK
        ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
        ,CASE WHEN B.SK_ACESSO IS NULL -->OK 
               THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
        ,'D 0' AS DSC_SAFRA              
        ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_USSD_RET_P1 A

LEFT JOIN TMP_SQDAA_USSD_RET_P3A B --->>LIGA URA
     ON A.SK_ACESSO = B.SK_ACESSO

GROUP BY  
           A.SK_ACESSO
            ,A.SAFRA 
           ,A.NUM_NTC 
           ,A.SK_DATA 
           ,A.COD_PLATAFORMA 
           ,A.DAT_INICIO_ATENDIMENTO
           ,A.COD_SHORT_CODE
           ,A.DT_INI_ATENDIMENTO
           ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
           ,CASE WHEN B.SK_ACESSO IS NULL -->OK
               THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END  
       
ORDER BY A.SK_ACESSO
;


--ETAPA 4.1 - D1 24H APOS O ACESSO + CR 
DROP TABLE TMP_RET_DIGITAL_USSD1; -->OK  
CREATE TABLE TMP_RET_DIGITAL_USSD1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT ------------------------------------------------------------------------ETAPA 4 ACESSO + CR 
    A.SK_ACESSO 
    ,A.SAFRA 
    ,A.NUM_NTC 
    ,A.SK_DATA 
    ,A.COD_PLATAFORMA 
    ,A.DAT_INICIO_ATENDIMENTO
    ,A.DT_INI_ATENDIMENTO
    ,A.COD_SHORT_CODE
    ,'USSD' AS DSC_METODO_CONTATO -->OK
        ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
  ,CASE WHEN B.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE -->OK
  ,'D 1' AS DSC_SAFRA ----------------------------------------------------------------------------------------->> D1 24H APOS O ACESSO          
        ,SYSDATE                       AS DAT_CRIACAO
FROM      TMP_SQDAA_USSD_RET_P1 A
LEFT JOIN TMP_SQDAA_USSD_RET_P3B B ----------------------------------------------------------------------------------->> D1 24H APOS O ACESSO 
          ON A.SK_ACESSO = B.SK_ACESSO

GROUP BY  
  A.SK_ACESSO
  ,A.SAFRA 
  ,A.NUM_NTC 
  ,A.SK_DATA 
  ,A.COD_PLATAFORMA 
  ,A.DAT_INICIO_ATENDIMENTO
  ,A.COD_SHORT_CODE
  ,A.DT_INI_ATENDIMENTO
  ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
  ,CASE WHEN B.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END       
ORDER BY A.SK_ACESSO
;

--ETAPA 4.2 - D2 48H APOS O ACESSO + CR 
DROP TABLE TMP_RET_DIGITAL_USSD2;  -->OK 
CREATE TABLE TMP_RET_DIGITAL_USSD2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS ---------------------------->> D2 48H APOS O ACESSO
SELECT DISTINCT 
          A.SK_ACESSO 
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.DT_INI_ATENDIMENTO
          ,A.COD_SHORT_CODE
          ,'USSD' AS DSC_METODO_CONTATO -->OK
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
          ,'D 2' AS DSC_SAFRA ----------------------------------------------------------------------------------------->> D2 48H APOS O ACESSO          
          ,SYSDATE                       AS DAT_CRIACAO
FROM      TMP_SQDAA_USSD_RET_P1 A
LEFT JOIN TMP_SQDAA_USSD_RET_P3C B ----------------------------------------------------------------------------------->> D2 48H APOS O ACESSO 
          ON A.SK_ACESSO = B.SK_ACESSO
GROUP BY  
          A.SK_ACESSO
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.COD_SHORT_CODE
          ,A.DT_INI_ATENDIMENTO
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END         
ORDER BY A.SK_ACESSO
;


--ETAPA 4.3 - D3 72H APOS O ACESSO + CR 
DROP TABLE TMP_RET_DIGITAL_USSD3; -->OK   
CREATE TABLE TMP_RET_DIGITAL_USSD3 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS ---------------------------->> D3 72H APOS O ACESSO
SELECT DISTINCT 
        A.SK_ACESSO 
        ,A.SAFRA 
        ,A.NUM_NTC 
        ,A.SK_DATA 
        ,A.COD_PLATAFORMA 
        ,A.DAT_INICIO_ATENDIMENTO
        ,A.DT_INI_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,'USSD' AS DSC_METODO_CONTATO -->OK
        ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
        ,CASE WHEN B.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
        ,'D 3' AS DSC_SAFRA ----------------------------------------------------------------------------------------->> D3 72H APOS O ACESSO          
        ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_USSD_RET_P1 A

LEFT JOIN TMP_SQDAA_USSD_RET_P3D B ----------------------------------------------------------------------------------->> D3 72H APOS O ACESSO 
     ON A.SK_ACESSO = B.SK_ACESSO

GROUP BY  
          A.SK_ACESSO
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.COD_SHORT_CODE
          ,A.DT_INI_ATENDIMENTO
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END        
ORDER BY A.SK_ACESSO
;


--ETAPA 4.4 - D7 7 DIAS APOS O ACESSO + CR 
DROP TABLE TMP_RET_DIGITAL_USSD7;   -->OK
CREATE TABLE TMP_RET_DIGITAL_USSD7 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS ---------------------------->> D7 7 DIAS APOS O ACESSO
SELECT DISTINCT 
          A.SK_ACESSO 
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.DT_INI_ATENDIMENTO
          ,A.COD_SHORT_CODE
          ,'USSD' AS DSC_METODO_CONTATO -->OK
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
          ,'D 7' AS DSC_SAFRA ----------------------------------------------------------------------------------------->> D7 7 DIAS APOS O ACESSO          
          ,SYSDATE                       AS DAT_CRIACAO
FROM      TMP_SQDAA_USSD_RET_P1 A
LEFT JOIN TMP_SQDAA_USSD_RET_P3E B ----------------------------------------------------------------------------------->> D7 7 DIAS APOS O ACESSO 
          ON A.SK_ACESSO = B.SK_ACESSO
GROUP BY  
          A.SK_ACESSO
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.COD_SHORT_CODE
          ,A.DT_INI_ATENDIMENTO
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END  
ORDER BY A.SK_ACESSO
;

--ETAPA 4.5 - M0 ACESSOS DENTRO DO MES + CR 
DROP TABLE TMP_RET_DIGITAL_USSD30;   -->OK
CREATE TABLE TMP_RET_DIGITAL_USSD30 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS ---------------------------->> M0 ACESSOS DENTRO DO MES 
SELECT DISTINCT 
            A.SK_ACESSO 
            ,A.SAFRA 
            ,A.NUM_NTC 
            ,A.SK_DATA 
            ,A.COD_PLATAFORMA 
            ,A.DAT_INICIO_ATENDIMENTO
            ,A.DT_INI_ATENDIMENTO
            ,A.COD_SHORT_CODE
            ,'USSD' AS DSC_METODO_CONTATO -->OK
            ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END AS FLG_ACESSA_LIGA
            ,CASE WHEN B.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END DSC_VISAO_ANALISE
            ,'DM0' AS DSC_SAFRA ----------------------------------------------------------------------------------------->> M0 ACESSOS DENTRO DO MES           
            ,SYSDATE                       AS DAT_CRIACAO
FROM TMP_SQDAA_USSD_RET_P1 A

LEFT JOIN TMP_SQDAA_USSD_RET_P3F B ----------------------------------------------------------------------------------->> M0 ACESSOS DENTRO DO MES  
     ON A.SK_ACESSO = B.SK_ACESSO
GROUP BY  
          A.SK_ACESSO
          ,A.SAFRA 
          ,A.NUM_NTC 
          ,A.SK_DATA 
          ,A.COD_PLATAFORMA 
          ,A.DAT_INICIO_ATENDIMENTO
          ,A.COD_SHORT_CODE
          ,A.DT_INI_ATENDIMENTO
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 1 ELSE 0 END
          ,CASE WHEN B.SK_ACESSO IS NULL THEN 'RETIDO DIGITAL' ELSE 'ACESSOU E LIGOU' END        
ORDER BY A.SK_ACESSO
;

--ETAPA 5  DATA REFERENCIA
DROP TABLE TMP_RET_DIG_USSD_DTREF; 
CREATE TABLE TMP_RET_DIG_USSD_DTREF COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT ------------------------------------------------------------------------ETAPA 6  TABELA AGREGADA
SAFRA ,MAX(DAT_INICIO_ATENDIMENTO) AS DAT_REFERENCIA FROM TMP_SQDAA_USSD_RET_P1 GROUP BY SAFRA;


--ETAPA 6  TABELA FATO
--DELETE BI_FT_RET_DIG_USSD WHERE SAFRA IN (202002,202003);
--INSERT /*+APPEND */ INTO BI_FT_RET_DIG_USSD --------------------------------------------------------------------------ETAPA 7 TABELA FATO
DROP TABLE BI_FT_RET_DIG_USSD;
CREATE TABLE BI_FT_RET_DIG_USSD COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT B.DAT_REFERENCIA ,A.* FROM TMP_RET_DIGITAL_USSD0 A LEFT JOIN TMP_RET_DIG_USSD_DTREF B ON A.SAFRA = B.SAFRA
UNION ALL
SELECT B.DAT_REFERENCIA ,A.* FROM TMP_RET_DIGITAL_USSD1 A LEFT JOIN TMP_RET_DIG_USSD_DTREF B ON A.SAFRA = B.SAFRA
UNION ALL
SELECT B.DAT_REFERENCIA ,A.* FROM TMP_RET_DIGITAL_USSD2 A LEFT JOIN TMP_RET_DIG_USSD_DTREF B ON A.SAFRA = B.SAFRA
UNION ALL
SELECT B.DAT_REFERENCIA ,A.* FROM TMP_RET_DIGITAL_USSD3 A LEFT JOIN TMP_RET_DIG_USSD_DTREF B ON A.SAFRA = B.SAFRA
UNION ALL
SELECT B.DAT_REFERENCIA ,A.* FROM TMP_RET_DIGITAL_USSD7 A LEFT JOIN TMP_RET_DIG_USSD_DTREF B ON A.SAFRA = B.SAFRA
UNION ALL
SELECT B.DAT_REFERENCIA ,A.* FROM TMP_RET_DIGITAL_USSD30 A LEFT JOIN TMP_RET_DIG_USSD_DTREF B ON A.SAFRA = B.SAFRA
;

--ETAPA 7 TABELA AGREGADA
--*************************PRECISA REALIZAR O COMMIT APÓS O INSERT*****************************************************
INSERT /*+APPEND */ INTO AGG_RET_DIG_USSD ------------------------------------------------------------------------ETAPA 8 TABELA AGREGADA
--CREATE TABLE AGG_RET_DIG_USSD COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT       
          SAFRA
          ,DAT_REFERENCIA
          ,COD_SHORT_CODE
          ,DSC_METODO_CONTATO
          ,COD_PLATAFORMA
          ,DSC_SAFRA
          ,DSC_VISAO_ANALISE
          ,COUNT(DISTINCT(NUM_NTC))            AS QT_USU_UNICOS
          ,COUNT(DISTINCT(SK_ACESSO))          AS QT_ACESSO
          ,SYSDATE                             AS DAT_CRIACAO
           
FROM BI_FT_RET_DIG_USSD 
WHERE SAFRA = &SAFRA_YYYYMM
GROUP BY     
          SAFRA
          ,DAT_REFERENCIA
          ,COD_SHORT_CODE
          ,DSC_METODO_CONTATO
          ,COD_PLATAFORMA
          ,DSC_SAFRA
          ,DSC_VISAO_ANALISE

ORDER BY 
          SAFRA
          ,DAT_REFERENCIA
          ,COD_SHORT_CODE
          ,DSC_METODO_CONTATO
          ,COD_PLATAFORMA
          ,DSC_SAFRA
          ,DSC_VISAO_ANALISE;
 COMMIT;     
--SELECT UNIQUE DAT_REFERENCIA ,DSC_SAFRA FROM AGG_RET_DIG_USSD;

SELECT  ------------------------------------------------ CONSULTA 1 -------> UU_USSD_PLATAFORMA
         SAFRA
         ,DAT_REFERENCIA
         ,COD_PLATAFORMA
         ,DSC_SAFRA
         ,DSC_VISAO_ANALISE
         ,DAT_CRIACAO
         ,SUM(QT_USU_UNICOS)AS QT_USU_UNICOS
         ,SUM(QT_ACESSO) AS QT_ACESSO

   FROM U92047747.AGG_RET_DIG_USSD
WHERE SAFRA = &SAFRA_YYYYMM   
GROUP BY SAFRA ,DAT_REFERENCIA ,COD_PLATAFORMA ,DSC_SAFRA ,DSC_VISAO_ANALISE ,DAT_CRIACAO
ORDER BY SAFRA ,DAT_REFERENCIA ,COD_PLATAFORMA ,DSC_SAFRA ,DSC_VISAO_ANALISE ,DAT_CRIACAO;



/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------
				MOTIVOS DO RETIDO NO CANAL USSD - RETIDO NO MESMO DIA

----------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
WITH 
USSD_MOT_RET_P1 AS (

SELECT /*+parallel (32)*/
        B.SAFRA
        ,A.DAT_REFERENCIA
        ,A.COD_PLATAFORMA
        ,C.DW_NOS_MINT
        ,COUNT(DISTINCT(B.SK_ACESSO)) AS QT_ACESSOS_RETIDO
      --,COUNT(DISTINCT(B.NUN_NTC)) AS QT_UU
  
FROM DWH.BI_FP_ATENDIMENTO_MINT A
INNER JOIN U92047747.BI_FT_RET_DIG_USSD B ON TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) = B.SK_ACESSO
LEFT JOIN DWH.BI_FP_NAVEGACAO_MINT C  ON A.COD_ATENDIMENTO = C.COD_ATENDIMENTO AND TRUNC(A.DAT_REFERENCIA)  = TRUNC(C.DAT_REFERENCIA)

WHERE A.COD_SHORT_CODE = 1052 --- SHORT CODE USSD
  AND A.DW_NUM_CANAL_MINT = 2 --> CANAL USSD VER NA TABELA VER TABELA "DWH.BI_DIM_CANAL_MINT"
  AND A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(20200501, 'RRRRMMDD') AND  TO_DATE(20200531, 'RRRRMMDD')
  AND B.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(20200501, 'RRRRMMDD') AND  TO_DATE(20200531, 'RRRRMMDD')
  AND B.DSC_VISAO_ANALISE = 'RETIDO DIGITAL'
  AND B.DSC_SAFRA = 'D 0'
GROUP BY 
         B.SAFRA
        ,A.DAT_REFERENCIA
        ,A.COD_PLATAFORMA
        ,A.COD_ATENDIMENTO
        ,C.DW_NOS_MINT
)
SELECT /*+PARALLEL (32)*/ DISTINCT
    A.SAFRA
    ,A.COD_PLATAFORMA
    ,B.DSC_NOS_MINT
    ,SUM(A.QT_ACESSOS_RETIDO) AS QT_ACESSOS_RETIDO
FROM USSD_MOT_RET_P1 A
INNER JOIN DWH.BI_DIM_NOS_MINT B ON A.DW_NOS_MINT = B.DW_NOS_MINT
GROUP BY A.SAFRA
    ,A.COD_PLATAFORMA
    ,B.DSC_NOS_MINT;
/



