/*
  SPRINT 28 - Abertura da origem dos acessos ao WhatsApp
  OBJETIVO: A ORIGEM DO ACESSO E PARA ONDE ESTÃO MIGRANDO
  
  Importante respondermos algumas perguntas:
•  Clientes que acessam whatsapp acessam também outros canais? Na mesma proporção? Por qual motivo?
•  Clientes que acessam whatsapp antes tinham o comportamento de ligação e agora usam o canal? Deixaram de ligar por causa do whatsapp? Reduzimos quanto do CR?
•  Clientes que não interagiam, agora acessa whatsapp? Se sim, qual o custo disso?
•  Clientes que não ligavam, agora acessam o whatsapp? Se sim, qual o custo evitado?
•	Retenção digital do canal whatsapp (móvel/net/tv) de jan a atual. 


*/
/*
DWH.BI_DIM_CANAL_MINT
DWH.BI_DIM_FUNCIONALIDADE_MINT
DWH.BI_DIM_INPUT_ASSINANTE_MINT
DWH.BI_DIM_MENU_MINT
DWH.BI_DIM_NOS_MINT
DWH.BI_DIM_STATUS_MINT
DWH.BI_DIM_TIPO_ASSINATURA_MINT
DWH.BI_DIM_TIPO_INTERACAO_MINT
DWH.BI_DIM_TIPO_SERVICO_MINT
DWH.BI_FP_ATENDIMENTO_MINT
DWH.BI_FP_NAVEGACAO_MINT
*/


--ETAPA 1 ACESSO WHATSAPP_P1
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P1;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 1 ACESSO WPP
        A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6) AS SAFRA --ok
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') AS SK_DATA --ok
        ,A.COD_PLATAFORMA --ok
        ,A.NUM_NTC --ok
        ,A.DAT_INICIO_ATENDIMENTO AS DT_INI_ATENDIMENTO
        ,TRUNC(A.DAT_INICIO_ATENDIMENTO) AS DAT_INICIO_ATENDIMENTO --ok
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
        ,A.COD_SHORT_CODE
        ,'WhatsApp' AS DSC_METODO_CONTATO       
        ,SYSDATE                       AS DAT_CRIACAO
FROM DWH.BI_FP_ATENDIMENTO_MINT A
LEFT JOIN DWH.BI_DIM_CANAL_MINT B ON A.DW_NUM_CANAL_MINT = B.DW_NUM_CANAL_MINT
WHERE A.COD_SHORT_CODE = 9652 --- SHORT CODE WPP
AND A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND A.COD_PLATAFORMA NOT IN ('-2','-3') --> SOMENTE CLIENTES MÓVEIS

GROUP BY  A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6)
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD')
        ,A.COD_PLATAFORMA
        ,A.NUM_NTC
        ,A.DAT_INICIO_ATENDIMENTO
    ,A.COD_SHORT_CODE
;

--ETAPA 2 ACESSO USSD
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P2;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 1 ACESSO USSD
        A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6) AS SAFRA --ok
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') AS SK_DATA --ok
        ,A.COD_PLATAFORMA --ok
        ,A.NUM_NTC --ok
        ,A.DAT_INICIO_ATENDIMENTO AS DT_INI_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,A.COD_ATENDIMENTO
        ,A.DW_NUM_CANAL_MINT
        ,A.NUM_PROTOCOLO
        ,TRUNC(A.DAT_INICIO_ATENDIMENTO) AS DAT_INICIO_ATENDIMENTO --ok
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
        ,'USSD' AS DSC_METODO_CONTATO
        ,CASE WHEN TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) 
                   < B.SK_ACESSO THEN 1 ELSE 0 END AS FLG_ACESSOU_ANTES           
        ,SYSDATE                       AS DAT_CRIACAO
 
FROM DWH.BI_FP_ATENDIMENTO_MINT A
INNER JOIN TMP_SQDAA_ACESSO_WHATSAPP_P1 B
           ON A.NUM_NTC = B.NUM_NTC
           
WHERE A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND A.COD_SHORT_CODE = 1052 --- SHORT CODE USSD
AND A.COD_PLATAFORMA NOT IN ('-2','-3') -->SOMENTE CLIENTES CLARO
AND A.DW_NUM_CANAL_MINT = 2 --> CANAL USSD VER NA TABELA VER TABELA "DWH.BI_DIM_CANAL_MINT"
AND A.NUM_PROTOCOLO IS NOT NULL --> SOMENTE ACESSOS QUE POSSUEM PROTOCOLOS

GROUP BY  A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6)
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD')
        ,A.COD_PLATAFORMA
        ,A.NUM_NTC
        ,A.DAT_INICIO_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,A.COD_ATENDIMENTO
        ,A.DW_NUM_CANAL_MINT 
        ,A.NUM_PROTOCOLO
        ,CASE WHEN TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) 
                   < B.SK_ACESSO THEN 1 ELSE 0 END     
;



-- ETAPA 3 ACESSO MCM
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P3;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P3 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT  /*+ PARALLEL (32)*/
       LAST_DAY(MC.DAT_INICIO_ATENDIMENTO) AS DAT_REFERENCIA 
       ,TO_NUMBER(TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')) SK_DATA
       ,TO_DATE(TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_INICIO_ATENDIMENTO,'RRRRMMDD HH24MISS') AS DAT_INI_ATENDIMENTO
       ,TO_DATE(TO_CHAR(MC.DAT_FIM_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_FIM_ATENDIMENTO,'RRRRMMDD HH24MISS') AS DAT_FIM_ATENDIMENTO
       ,MC.NUM_NTC
       ,MC.DW_METODO_CONTATO
     --  ,DM.DSC_METODO_CONTATO
       ,TO_CHAR(MC.NUM_NTC ||' '||TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_INICIO_ATENDIMENTO) AS SK_ACESSO
       ,'MCM' AS DSC_METODO_CONTATO
       ,CASE WHEN TO_CHAR(MC.NUM_NTC ||' '||TO_DATE(TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_INICIO_ATENDIMENTO,'RRRRMMDD HH24MISS')) <
             AC.SK_ACESSO THEN 1 ELSE 0 END AS FLG_ACESSOU_ANTES             
       ,SYSDATE AS DAT_CRIACAO
       

      FROM DWH.BI_FP_ASSINANTE_ATEND_FECHADO MC 
INNER JOIN TMP_SQDAA_ACESSO_WHATSAPP_P1 AC
           ON MC.NUM_NTC = AC.NUM_NTC
           
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
          ON MC.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO DM
          ON MC.DW_METODO_CONTATO = DM.DW_METODO_CONTATO
WHERE MC.DW_METODO_CONTATO IN (81,411,451,701,709,791)     -------EXPURDO 681 App Flex 552 Minha Claro Empresa    
  
      AND UPPER(MC.DSC_OBSERVACAO_ATENDIMENTO) LIKE '%MINHACLAROWEB%AUTENTICA%USU%'
      AND MC.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
     -- AND MC.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(20200301, 'RRRRMMDD') AND  TO_DATE(20200331, 'RRRRMMDD')
 ;
  
--ETAPA 4 LIGACOES CR
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P4;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P4 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+ PARALLEL (32)*/ ------------------------------------------------------------------------ETAPA 2 LIGACOES CR
       LAST_DAY(TO_DATE(FT.DT_INICIO_LIGACAO,'YYYY/MM/DD')) AS DAT_REFERENCIA       
       ,FT.DT_INICIO_LIGACAO SK_DATA       
       ,'CMV' AS NM_MARCA
       ,FT.SK_ATENDIMENTO_URA AS COD_CHAMADA -- CALL_ID
       ,TO_CHAR(FT.CD_NUMERO_TELEFONE ||' '||FT.DT_INICIO_LIGACAO ||' '||FT.NR_HORA_INICIO_LIGACAO) AS SK_LIGA
       ,TO_DATE(TO_DATE(FT.DT_INICIO_LIGACAO,'YYYY/MM/DD') ||' ' ||FT.NR_HORA_INICIO_LIGACAO,'DD/MM/RRRR HH24:MI:SS') AS DT_INI_LIGACAO
       ,TO_DATE(TO_DATE(FT.DT_FIM_LIGACAO,'YYYY/MM/DD') ||' ' ||FT.NR_HORA_FIM_LIGACAO,'DD/MM/RRRR HH24:MI:SS') AS DT_FIM_LIGACAO
       ,FT.CD_NUMERO_TELEFONE                           AS NUM_NTC
       ,'CallCenter' AS DSC_METODO_CONTATO 
       ,CASE WHEN TO_CHAR(FT.CD_NUMERO_TELEFONE ||' '||FT.DT_INICIO_LIGACAO ||' '||FT.NR_HORA_INICIO_LIGACAO) <
             AC.SK_ACESSO THEN 1 ELSE 0 END AS FLG_ACESSOU_ANTES
       ,CASE
         WHEN FT.FN_LIGACAO_IDENTIFICADA = 1 THEN
          'SIM'
         ELSE
          'NAO'
       END                                AS FLG_LIG_IDENTIFICADA
       ,STS.COD_SUB_STS_ATU DSC_STS_CLIENTE
       ,CASE
         WHEN FT.FN_CORPORATIVO = 1 THEN
          'SIM'
         ELSE
          'NAO'
       END                               AS FLG_CORPORATIVO
       ,CASE
         WHEN VA.NM_VISAO_ANALISE_BI = 'CONTACT RATE DIRECIONADO AO HUMANO' THEN
          'DIRECIONADO HUMANO'
         ELSE
          'RETIDO URA'
       END                           AS DSC_DIRECIONADO_RETIDO
       ,ATM.NM_TIPO_MOTIVO_BI         AS DSC_MOTIVO_URA
       ,STM.NM_SUB_TIPO_MOTIVO_BI     AS DSC_SUB_MOTIVO_URA
       ,ATL.NM_TIPO_LIGACAO_BI        AS DSC_EXPURGO_URA
       ,PP.DSC_PLANO_PRECO_BI         AS DSC_PLANO_CLIENTE
       ,SYSDATE                       AS DAT_CRIACAO

  FROM INTMKT.FT_ATENDIMENTO_URA FT -- OK
INNER JOIN TMP_SQDAA_ACESSO_WHATSAPP_P1 AC ON AC.NUM_NTC = FT.CD_NUMERO_TELEFONE ------> BASE ACESSO DO WHATSAPP
  LEFT JOIN DWH.BI_DIM_STATUS STS -- OK
    ON STS.STS_DW = FT.SK_STATUS
  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_MOTIVO ATM -- OK
    ON ATM.SK_ATENDIMENTO_TIPO_MOTIVO = FT.SK_ATENDIMENTO_TIPO_MOTIVO

  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_LIGACAO ATL -- OK
    ON ATL.SK_ATENDIMENTO_TIPO_LIGACAO = FT.SK_ATENDIMENTO_TIPO_LIGACAO
  LEFT JOIN DWH.BI_DIM_PLANO_PRECO PP -- OK
    ON PP.DW_PLANO = FT.SK_PLANO
  LEFT JOIN INTMKT.DS_ATENDIMENTO_SUB_TIPO_MOTIVO STM -- OK
   ON STM.SK_ATENDIMENTO_SUB_TIPO_MOTIVO =
       FT.SK_ATENDIMENTO_SUB_TIPO_MOTIVO
  LEFT JOIN INTMKT.DS_VISAO_ANALISE VA -- OK
    ON VA.SK_VISAO_ANALISE = FT.SK_VISAO_ANALISE
  LEFT JOIN intmkt.ds_atendimento_tipo_ligacao ATL 
ON        atl.sk_atendimento_tipo_ligacao = ft.sk_atendimento_tipo_ligacao 

WHERE FT.SK_DATA BETWEEN &DATA_INICIAL AND &DATA_FINAL
---AND       atl.nm_tipo_ligacao_bi = 'Ligações Válidas' -- FILTRO OK (SÃO CLIENTES QUE NÃO TIVERAM ABANDONO)
---AND va.nm_visao_analise_bi = 'Contact Rate Direcionado ao Humano' -- FILTRO OK
;

-- ETAPA 5 FT -ANALISE SOMENTE ACESSA
DROP TABLE BI_FT_WHATSAPP_COMPORT_ACESSO;
CREATE TABLE BI_FT_WHATSAPP_COMPORT_ACESSO COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT  /*+ PARALLEL (32)*/
        AC.SAFRA
        ,AC.COD_PLATAFORMA
        ,AC.NUM_NTC
        ,COUNT(DISTINCT(AC.SK_ACESSO)) AS QT_ACESSO
        ,CASE WHEN US.NUM_NTC IS NULL THEN 0 ELSE 1 END AS FLG_ACESSA_USSD       
        ,CASE WHEN MC.NUM_NTC IS NULL THEN 0 ELSE 1 END AS FLG_ACESSA_MCM
        ,CASE WHEN CC.NUM_NTC IS NULL THEN 0 ELSE 1 END AS FLG_ACESSA_CALL
        ,CASE WHEN US.NUM_NTC IS NULL  
              AND  MC.NUM_NTC IS NULL  
              AND  CC.NUM_NTC IS NULL THEN 1 ELSE 0 END AS FLG_ANALISE
        ,CASE WHEN US.NUM_NTC IS NULL  
              AND  MC.NUM_NTC IS NULL  
              AND  CC.NUM_NTC IS NULL THEN 'SOMENTE ACESSA WHATSAPP' ELSE 'ACESSA OUTROS CANAIS' END AS DSC_ANALISE

 --SELECT *  
     FROM TMP_SQDAA_ACESSO_WHATSAPP_P1 AC --> BASE DE ACESSO WHATSAPP
LEFT JOIN TMP_SQDAA_ACESSO_WHATSAPP_P2 US ON AC.NUM_NTC = US.NUM_NTC --> BASE DE ACESSO USSD
LEFT JOIN TMP_SQDAA_ACESSO_WHATSAPP_P3 MC ON AC.NUM_NTC = MC.NUM_NTC --> BASE DE ACESSO MCM
LEFT JOIN TMP_SQDAA_ACESSO_WHATSAPP_P4 CC ON AC.NUM_NTC = CC.NUM_NTC --> BASE DE ACESSO CALL CENTER

---WHERE ROWNUM < 2001 /*AND AC.COD_PLATAFORMA = 'PREPG'*/

GROUP BY AC.SAFRA
        ,AC.COD_PLATAFORMA
       ,AC.NUM_NTC
       ,CASE WHEN US.NUM_NTC IS NULL THEN 0 ELSE 1 END
       ,CASE WHEN MC.NUM_NTC IS NULL THEN 0 ELSE 1 END
       ,CASE WHEN CC.NUM_NTC IS NULL THEN 0 ELSE 1 END
       ,CASE WHEN US.NUM_NTC IS NULL  
              AND  MC.NUM_NTC IS NULL  
              AND  CC.NUM_NTC IS NULL THEN 1 ELSE 0 END
       ,CASE WHEN US.NUM_NTC IS NULL  
              AND  MC.NUM_NTC IS NULL  
              AND  CC.NUM_NTC IS NULL THEN 'SOMENTE ACESSA WHATSAPP' ELSE 'ACESSOU OUTROS CANAIS' END
ORDER BY NUM_NTC;
;


/*--====================================================================================================================
       FIM DA  ANALISE DOS CLIENTES 

--====================================================================================================================*/







/*
  SPRINT 28 - Abertura da origem dos acessos ao WhatsApp
  OBJETIVO: A ORIGEM DO ACESSO E PARA ONDE ESTÃO MIGRANDO
  

*/

SELECT * FROM TMP_SQDAA_ACESSO_WHATSAPP_P1;

--ETAPA 1 ACESSO WHATSAPP_P1
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P1;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 1 ACESSO WPP
        A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6) AS SAFRA --ok
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') AS SK_DATA --ok
        ,A.COD_PLATAFORMA --ok
        ,A.NUM_NTC --ok
        ,A.DAT_INICIO_ATENDIMENTO AS DT_INI_ATENDIMENTO
        ,TRUNC(A.DAT_INICIO_ATENDIMENTO) AS DAT_INICIO_ATENDIMENTO --ok
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
        ,A.COD_SHORT_CODE
        ,'WhatsApp' AS DSC_METODO_CONTATO       
        ,SYSDATE                       AS DAT_CRIACAO
FROM DWH.BI_FP_ATENDIMENTO_MINT A
LEFT JOIN DWH.BI_DIM_CANAL_MINT B ON A.DW_NUM_CANAL_MINT = B.DW_NUM_CANAL_MINT
WHERE A.COD_SHORT_CODE = 9652 --- SHORT CODE WPP
AND A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND A.COD_PLATAFORMA NOT IN ('-2','-3') --> SOMENTE CLIENTES MÓVEIS

GROUP BY  A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6)
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD')
        ,A.COD_PLATAFORMA
        ,A.NUM_NTC
        ,A.DAT_INICIO_ATENDIMENTO
    ,A.COD_SHORT_CODE
;

--ETAPA 2 ACESSO USSD
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P2;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 1 ACESSO USSD
        A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6) AS SAFRA --ok
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') AS SK_DATA --ok
        ,A.COD_PLATAFORMA --ok
        ,A.NUM_NTC --ok
        ,A.DAT_INICIO_ATENDIMENTO AS DT_INI_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,A.COD_ATENDIMENTO
        ,A.DW_NUM_CANAL_MINT
        ,A.NUM_PROTOCOLO
        ,TRUNC(A.DAT_INICIO_ATENDIMENTO) AS DAT_INICIO_ATENDIMENTO --ok
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
        ,'USSD' AS DSC_METODO_CONTATO
        ,CASE WHEN TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) 
                   < B.SK_ACESSO THEN 1 ELSE 0 END AS FLG_ACESSOU_ANTES           
        ,SYSDATE                       AS DAT_CRIACAO
 
FROM DWH.BI_FP_ATENDIMENTO_MINT A
INNER JOIN TMP_SQDAA_ACESSO_WHATSAPP_P1 B
           ON A.NUM_NTC = B.NUM_NTC
           
WHERE A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND A.COD_SHORT_CODE = 1052 --- SHORT CODE USSD
AND A.COD_PLATAFORMA NOT IN ('-2','-3') -->SOMENTE CLIENTES CLARO
AND A.DW_NUM_CANAL_MINT = 2 --> CANAL USSD VER NA TABELA VER TABELA "DWH.BI_DIM_CANAL_MINT"
AND A.NUM_PROTOCOLO IS NOT NULL --> SOMENTE ACESSOS QUE POSSUEM PROTOCOLOS

GROUP BY  A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6)
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD')
        ,A.COD_PLATAFORMA
        ,A.NUM_NTC
        ,A.DAT_INICIO_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,A.COD_ATENDIMENTO
        ,A.DW_NUM_CANAL_MINT 
        ,A.NUM_PROTOCOLO
        ,CASE WHEN TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) 
                   < B.SK_ACESSO THEN 1 ELSE 0 END     
;



-- ETAPA 3 ACESSO MCM
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P3;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P3 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS

SELECT  /*+ PARALLEL (32)*/
       LAST_DAY(DAT_INICIO_ATENDIMENTO) AS DAT_REFERENCIA 
       ,TO_NUMBER(TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')) SK_DATA
       ,TO_DATE(TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_INICIO_ATENDIMENTO,'RRRRMMDD HH24MISS') AS DAT_INI_ATENDIMENTO
       ,TO_DATE(TO_CHAR(MC.DAT_FIM_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_FIM_ATENDIMENTO,'RRRRMMDD HH24MISS') AS DAT_FIM_ATENDIMENTO
       ,MC.NUM_NTC
       ,MC.DW_METODO_CONTATO
       ,DM.DSC_METODO_CONTATO
       ,TO_CHAR(MC.NUM_NTC ||' '||TO_DATE(TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_INICIO_ATENDIMENTO,'RRRRMMDD HH24MISS')) AS SK_ACESSO
       ,'MCM' AS DSC_METODO_CONTATO
       ,CASE WHEN TO_CHAR(MC.NUM_NTC ||' '||TO_DATE(TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_INICIO_ATENDIMENTO,'RRRRMMDD HH24MISS')) <
             B.SK_ACESSO THEN 1 ELSE 0 END AS FLG_ACESSOU_ANTES             
       ,SYSDATE AS DAT_CRIACAO
       

      FROM DWH.BI_FP_ASSINANTE_ATEND_FECHADO MC 
INNER JOIN TMP_SQDAA_ACESSO_WHATSAPP_P1 AC
           ON MC.NUM_NTC = AC.NUM_NTC
           
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
          ON MC.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO DM
          ON MC.DW_METODO_CONTATO = DM.DW_METODO_CONTATO
WHERE MC.DW_METODO_CONTATO IN (81,411,451,701,709,791)     -------EXPURDO 681 App Flex 552 Minha Claro Empresa    
  
      AND UPPER(MC.DSC_OBSERVACAO_ATENDIMENTO) LIKE '%MINHACLAROWEB%AUTENTICA%USU%'
      AND MC.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(20200301, 'RRRRMMDD') AND  TO_DATE(20200331, 'RRRRMMDD')
--ETAPA 2 LIGACOES CR
DROP TABLE TMP_SQDAA_WPP_RET_P2;
CREATE TABLE TMP_SQDAA_WPP_RET_P2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+ PARALLEL (32)*/ ------------------------------------------------------------------------ETAPA 2 LIGACOES CR
       LAST_DAY(TO_DATE(FT.DT_INICIO_LIGACAO,'YYYY/MM/DD')) AS DAT_REFERENCIA       
       ,FT.DT_INICIO_LIGACAO SK_DATA       
       ,'CMV' AS NM_MARCA
       ,FT.SK_ATENDIMENTO_URA AS COD_CHAMADA -- CALL_ID
       ,TO_CHAR(FT.CD_NUMERO_TELEFONE ||' '||FT.DT_INICIO_LIGACAO ||' '||FT.NR_HORA_INICIO_LIGACAO) AS SK_LIGA
       ,TO_DATE(TO_DATE(FT.DT_INICIO_LIGACAO,'YYYY/MM/DD') ||' ' ||FT.NR_HORA_INICIO_LIGACAO,'DD/MM/RRRR HH24:MI:SS') AS DT_INI_LIGACAO
       ,TO_DATE(TO_DATE(FT.DT_FIM_LIGACAO,'YYYY/MM/DD') ||' ' ||FT.NR_HORA_FIM_LIGACAO,'DD/MM/RRRR HH24:MI:SS') AS DT_FIM_LIGACAO
       ,FT.CD_NUMERO_TELEFONE                           AS NUM_NTC
       ,CASE
         WHEN FT.FN_LIGACAO_IDENTIFICADA = 1 THEN
          'SIM'
         ELSE
          'NAO'
       END                                AS FLG_LIG_IDENTIFICADA
       ,STS.COD_SUB_STS_ATU DSC_STS_CLIENTE
       ,CASE
         WHEN FT.FN_CORPORATIVO = 1 THEN
          'SIM'
         ELSE
          'NAO'
       END                               AS FLG_CORPORATIVO
       ,CASE
         WHEN VA.NM_VISAO_ANALISE_BI = 'CONTACT RATE DIRECIONADO AO HUMANO' THEN
          'DIRECIONADO HUMANO'
         ELSE
          'RETIDO URA'
       END                           AS DSC_DIRECIONADO_RETIDO
       ,ATM.NM_TIPO_MOTIVO_BI         AS DSC_MOTIVO_URA
       ,STM.NM_SUB_TIPO_MOTIVO_BI     AS DSC_SUB_MOTIVO_URA
       ,ATL.NM_TIPO_LIGACAO_BI        AS DSC_EXPURGO_URA
       ,PP.DSC_PLANO_PRECO_BI         AS DSC_PLANO_CLIENTE
       ,SYSDATE                       AS DAT_CRIACAO

  FROM INTMKT.FT_ATENDIMENTO_URA FT -- OK
  LEFT JOIN DWH.BI_DIM_STATUS STS -- OK
    ON STS.STS_DW = FT.SK_STATUS
  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_MOTIVO ATM -- OK
    ON ATM.SK_ATENDIMENTO_TIPO_MOTIVO = FT.SK_ATENDIMENTO_TIPO_MOTIVO

  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_LIGACAO ATL -- OK
    ON ATL.SK_ATENDIMENTO_TIPO_LIGACAO = FT.SK_ATENDIMENTO_TIPO_LIGACAO
  LEFT JOIN DWH.BI_DIM_PLANO_PRECO PP -- OK
    ON PP.DW_PLANO = FT.SK_PLANO
  LEFT JOIN INTMKT.DS_ATENDIMENTO_SUB_TIPO_MOTIVO STM -- OK
   ON STM.SK_ATENDIMENTO_SUB_TIPO_MOTIVO =
       FT.SK_ATENDIMENTO_SUB_TIPO_MOTIVO
  LEFT JOIN INTMKT.DS_VISAO_ANALISE VA -- OK
    ON VA.SK_VISAO_ANALISE = FT.SK_VISAO_ANALISE
  LEFT JOIN intmkt.ds_atendimento_tipo_ligacao ATL 
ON        atl.sk_atendimento_tipo_ligacao = ft.sk_atendimento_tipo_ligacao 

WHERE FT.SK_DATA BETWEEN &DATA_INICIAL AND &DATA_FINAL
---AND       atl.nm_tipo_ligacao_bi = 'Ligações Válidas' -- FILTRO OK (SÃO CLIENTES QUE NÃO TIVERAM ABANDONO)
---AND va.nm_visao_analise_bi = 'Contact Rate Direcionado ao Humano' -- FILTRO OK
;

/*--====================================================================================================================
       ANALISE

--====================================================================================================================*/
SELECT  
       A.DAT_REFERENCIA
       ,A.SAFRA
       ,A.SK_DATA
       ,A.COD_PLATAFORMA
       ,A.NUM_NTC
       ,A.DT_INI_ATENDIMENTO
       ,A.DAT_INICIO_ATENDIMENTO
       ,A.SK_ACESSO
       ,A.COD_SHORT_CODE
       ,A.DAT_CRIACAO
       ,MAX(CASE WHEN B.NUM_NTC IS NULL THEN '-3'
             WHEN FLG_ACESSOU_ANTES = 1 THEN B.SK_ACESSO ELSE '-3' END) AS SK_ACESSO_USSD
                    
              
     FROM TMP_SQDAA_ACESSO_WHATSAPP_P1 A 
LEFT JOIN TMP_SQDAA_ACESSO_WHATSAPP_P2 B 
          ON A.NUM_NTC = B.NUM_NTC
WHERE     
          A.NUM_NTC = 98985276143 
GROUP BY A.DAT_REFERENCIA
       ,A.SAFRA
       ,A.SK_DATA
       ,A.COD_PLATAFORMA
       ,A.NUM_NTC
       ,A.DT_INI_ATENDIMENTO
       ,A.DAT_INICIO_ATENDIMENTO
       ,A.SK_ACESSO
       ,A.COD_SHORT_CODE
       ,A.DAT_CRIACAO
       ,CASE WHEN B.NUM_NTC IS NULL THEN '-3'
             WHEN FLG_ACESSOU_ANTES = 1 THEN B.SK_ACESSO ELSE '-3' END
ORDER BY A.SK_ACESSO;

SELECT * FROM TMP_SQDAA_ACESSO_WHATSAPP_P2 A WHERE A.NUM_NTC = 98985276143;




/*--====================================================================================================================================

				OLD MOVIMENTAÇÕES

*/

/*
  SPRINT 28 - Abertura da origem dos acessos ao WhatsApp
  OBJETIVO: A ORIGEM DO ACESSO E PARA ONDE ESTÃO MIGRANDO
  
  Importante respondermos algumas perguntas:
•  Clientes que acessam whatsapp acessam também outros canais? Na mesma proporção? Por qual motivo?
•  Clientes que acessam whatsapp antes tinham o comportamento de ligação e agora usam o canal? Deixaram de ligar por causa do whatsapp? Reduzimos quanto do CR?
•  Clientes que não interagiam, agora acessa whatsapp? Se sim, qual o custo disso?
•  Clientes que não ligavam, agora acessam o whatsapp? Se sim, qual o custo evitado?
•	Retenção digital do canal whatsapp (móvel/net/tv) de jan a atual. 


*/

/*---------------------------------------------------------------------------------------------------------------------------------------------------
  ANALISE ABAIXO É SOBRE:
  Clientes que acessam whatsapp acessam também outros canais? Na mesma proporção? Por qual motivo?
---------------------------------------------------------------------------------------------------------------------------------------------------*/



--ETAPA 1 ACESSO WHATSAPP_P1
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P1;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 1 ACESSO WPP
        A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6) AS SAFRA --ok
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') AS SK_DATA --ok
        ,A.COD_PLATAFORMA --ok
        ,A.NUM_NTC --ok
        ,A.DAT_INICIO_ATENDIMENTO AS DT_INI_ATENDIMENTO
        ,TRUNC(A.DAT_INICIO_ATENDIMENTO) AS DAT_INICIO_ATENDIMENTO --ok
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
        ,A.COD_SHORT_CODE
        ,'WhatsApp' AS DSC_METODO_CONTATO       
        ,SYSDATE                       AS DAT_CRIACAO
FROM DWH.BI_FP_ATENDIMENTO_MINT A
LEFT JOIN DWH.BI_DIM_CANAL_MINT B ON A.DW_NUM_CANAL_MINT = B.DW_NUM_CANAL_MINT
WHERE A.COD_SHORT_CODE = 9652 --- SHORT CODE WPP
AND A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND A.COD_PLATAFORMA NOT IN ('-2','-3') --> SOMENTE CLIENTES MÓVEIS

GROUP BY  A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6)
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD')
        ,A.COD_PLATAFORMA
        ,A.NUM_NTC
        ,A.DAT_INICIO_ATENDIMENTO
    ,A.COD_SHORT_CODE
;

--ETAPA 2 ACESSO USSD
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P2;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 1 ACESSO USSD
        A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6) AS SAFRA --ok
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') AS SK_DATA --ok
        ,A.COD_PLATAFORMA --ok
        ,A.NUM_NTC --ok
        ,A.DAT_INICIO_ATENDIMENTO AS DT_INI_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,A.COD_ATENDIMENTO
        ,A.DW_NUM_CANAL_MINT
        ,A.NUM_PROTOCOLO
        ,TRUNC(A.DAT_INICIO_ATENDIMENTO) AS DAT_INICIO_ATENDIMENTO --ok
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
        ,'USSD' AS DSC_METODO_CONTATO
        ,CASE WHEN TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) 
                   < B.SK_ACESSO THEN 1 ELSE 0 END AS FLG_ACESSOU_ANTES           
        ,SYSDATE                       AS DAT_CRIACAO
 
FROM DWH.BI_FP_ATENDIMENTO_MINT A
INNER JOIN TMP_SQDAA_ACESSO_WHATSAPP_P1 B
           ON A.NUM_NTC = B.NUM_NTC
           
WHERE A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND A.COD_SHORT_CODE = 1052 --- SHORT CODE USSD
AND A.COD_PLATAFORMA NOT IN ('-2','-3') -->SOMENTE CLIENTES CLARO
AND A.DW_NUM_CANAL_MINT = 2 --> CANAL USSD VER NA TABELA VER TABELA "DWH.BI_DIM_CANAL_MINT"
AND A.NUM_PROTOCOLO IS NOT NULL --> SOMENTE ACESSOS QUE POSSUEM PROTOCOLOS

GROUP BY  A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6)
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD')
        ,A.COD_PLATAFORMA
        ,A.NUM_NTC
        ,A.DAT_INICIO_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,A.COD_ATENDIMENTO
        ,A.DW_NUM_CANAL_MINT 
        ,A.NUM_PROTOCOLO
        ,CASE WHEN TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) 
                   < B.SK_ACESSO THEN 1 ELSE 0 END     
;



-- ETAPA 3 ACESSO MCM
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P3;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P3 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT  /*+ PARALLEL (32)*/
       LAST_DAY(MC.DAT_INICIO_ATENDIMENTO) AS DAT_REFERENCIA 
       ,TO_NUMBER(TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')) SK_DATA
       ,TO_DATE(TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_INICIO_ATENDIMENTO,'RRRRMMDD HH24MISS') AS DAT_INI_ATENDIMENTO
       ,TO_DATE(TO_CHAR(MC.DAT_FIM_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_FIM_ATENDIMENTO,'RRRRMMDD HH24MISS') AS DAT_FIM_ATENDIMENTO
       ,MC.NUM_NTC
       ,MC.DW_METODO_CONTATO
     --  ,DM.DSC_METODO_CONTATO
       ,TO_CHAR(MC.NUM_NTC ||' '||TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_INICIO_ATENDIMENTO) AS SK_ACESSO
       ,'MCM' AS DSC_METODO_CONTATO
       ,CASE WHEN TO_CHAR(MC.NUM_NTC ||' '||TO_DATE(TO_CHAR(MC.DAT_INICIO_ATENDIMENTO, 'RRRRMMDD')||' '||MC.HOR_INICIO_ATENDIMENTO,'RRRRMMDD HH24MISS')) <
             AC.SK_ACESSO THEN 1 ELSE 0 END AS FLG_ACESSOU_ANTES             
       ,SYSDATE AS DAT_CRIACAO
       

      FROM DWH.BI_FP_ASSINANTE_ATEND_FECHADO MC 
INNER JOIN TMP_SQDAA_ACESSO_WHATSAPP_P1 AC
           ON MC.NUM_NTC = AC.NUM_NTC
           
LEFT JOIN BI_DIM_MOTIVO_ATENDIMENTO M
          ON MC.DW_MOTIVO_ATENDIMENTO = M.DW_MOTIVO_ATENDIMENTO
LEFT JOIN BI_DIM_METODO_CONTATO DM
          ON MC.DW_METODO_CONTATO = DM.DW_METODO_CONTATO
WHERE MC.DW_METODO_CONTATO IN (81,411,451,701,709,791)     -------EXPURDO 681 App Flex 552 Minha Claro Empresa    
  
      AND UPPER(MC.DSC_OBSERVACAO_ATENDIMENTO) LIKE '%MINHACLAROWEB%AUTENTICA%USU%'
      AND MC.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
     -- AND MC.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(20200301, 'RRRRMMDD') AND  TO_DATE(20200331, 'RRRRMMDD')
 ;
  
--ETAPA 4 LIGACOES CR
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P4;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P4 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT /*+ PARALLEL (32)*/ ------------------------------------------------------------------------ETAPA 2 LIGACOES CR
       LAST_DAY(TO_DATE(FT.DT_INICIO_LIGACAO,'YYYY/MM/DD')) AS DAT_REFERENCIA       
       ,FT.DT_INICIO_LIGACAO SK_DATA       
       ,'CMV' AS NM_MARCA
       ,FT.SK_ATENDIMENTO_URA AS COD_CHAMADA -- CALL_ID
       ,TO_CHAR(FT.CD_NUMERO_TELEFONE ||' '||FT.DT_INICIO_LIGACAO ||' '||FT.NR_HORA_INICIO_LIGACAO) AS SK_LIGA
       ,TO_DATE(TO_DATE(FT.DT_INICIO_LIGACAO,'YYYY/MM/DD') ||' ' ||FT.NR_HORA_INICIO_LIGACAO,'DD/MM/RRRR HH24:MI:SS') AS DT_INI_LIGACAO
       ,TO_DATE(TO_DATE(FT.DT_FIM_LIGACAO,'YYYY/MM/DD') ||' ' ||FT.NR_HORA_FIM_LIGACAO,'DD/MM/RRRR HH24:MI:SS') AS DT_FIM_LIGACAO
       ,FT.CD_NUMERO_TELEFONE                           AS NUM_NTC
       ,'CallCenter' AS DSC_METODO_CONTATO 
       ,CASE WHEN TO_CHAR(FT.CD_NUMERO_TELEFONE ||' '||FT.DT_INICIO_LIGACAO ||' '||FT.NR_HORA_INICIO_LIGACAO) <
             AC.SK_ACESSO THEN 1 ELSE 0 END AS FLG_ACESSOU_ANTES
       ,CASE
         WHEN FT.FN_LIGACAO_IDENTIFICADA = 1 THEN
          'SIM'
         ELSE
          'NAO'
       END                                AS FLG_LIG_IDENTIFICADA
       ,STS.COD_SUB_STS_ATU DSC_STS_CLIENTE
       ,CASE
         WHEN FT.FN_CORPORATIVO = 1 THEN
          'SIM'
         ELSE
          'NAO'
       END                               AS FLG_CORPORATIVO
       ,CASE
         WHEN VA.NM_VISAO_ANALISE_BI = 'CONTACT RATE DIRECIONADO AO HUMANO' THEN
          'DIRECIONADO HUMANO'
         ELSE
          'RETIDO URA'
       END                           AS DSC_DIRECIONADO_RETIDO
       ,ATM.NM_TIPO_MOTIVO_BI         AS DSC_MOTIVO_URA
       ,STM.NM_SUB_TIPO_MOTIVO_BI     AS DSC_SUB_MOTIVO_URA
       ,ATL.NM_TIPO_LIGACAO_BI        AS DSC_EXPURGO_URA
       ,PP.DSC_PLANO_PRECO_BI         AS DSC_PLANO_CLIENTE
       ,SYSDATE                       AS DAT_CRIACAO

  FROM INTMKT.FT_ATENDIMENTO_URA FT -- OK
INNER JOIN TMP_SQDAA_ACESSO_WHATSAPP_P1 AC ON AC.NUM_NTC = FT.CD_NUMERO_TELEFONE ------> BASE ACESSO DO WHATSAPP
  LEFT JOIN DWH.BI_DIM_STATUS STS -- OK
    ON STS.STS_DW = FT.SK_STATUS
  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_MOTIVO ATM -- OK
    ON ATM.SK_ATENDIMENTO_TIPO_MOTIVO = FT.SK_ATENDIMENTO_TIPO_MOTIVO

  LEFT JOIN INTMKT.DS_ATENDIMENTO_TIPO_LIGACAO ATL -- OK
    ON ATL.SK_ATENDIMENTO_TIPO_LIGACAO = FT.SK_ATENDIMENTO_TIPO_LIGACAO
  LEFT JOIN DWH.BI_DIM_PLANO_PRECO PP -- OK
    ON PP.DW_PLANO = FT.SK_PLANO
  LEFT JOIN INTMKT.DS_ATENDIMENTO_SUB_TIPO_MOTIVO STM -- OK
   ON STM.SK_ATENDIMENTO_SUB_TIPO_MOTIVO =
       FT.SK_ATENDIMENTO_SUB_TIPO_MOTIVO
  LEFT JOIN INTMKT.DS_VISAO_ANALISE VA -- OK
    ON VA.SK_VISAO_ANALISE = FT.SK_VISAO_ANALISE
  LEFT JOIN intmkt.ds_atendimento_tipo_ligacao ATL 
ON        atl.sk_atendimento_tipo_ligacao = ft.sk_atendimento_tipo_ligacao 

WHERE FT.SK_DATA BETWEEN &DATA_INICIAL AND &DATA_FINAL
---AND       atl.nm_tipo_ligacao_bi = 'Ligações Válidas' -- FILTRO OK (SÃO CLIENTES QUE NÃO TIVERAM ABANDONO)
---AND va.nm_visao_analise_bi = 'Contact Rate Direcionado ao Humano' -- FILTRO OK
;

-- ETAPA 5 AGRUPAR AS TABELAS 
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_P5;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_P5 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT NUM_NTC ,DSC_METODO_CONTATO FROM TMP_SQDAA_ACESSO_WHATSAPP_P2
UNION ALL 
SELECT DISTINCT NUM_NTC ,DSC_METODO_CONTATO FROM TMP_SQDAA_ACESSO_WHATSAPP_P3
UNION ALL 
SELECT DISTINCT NUM_NTC ,DSC_METODO_CONTATO FROM TMP_SQDAA_ACESSO_WHATSAPP_P4
;


-- ETAPA 6 FT -ANALISE SOMENTE ACESSA
DROP TABLE BI_FT_WHATSAPP_COMPORT_ACESSO;
CREATE TABLE BI_FT_WHATSAPP_COMPORT_ACESSO COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT  /*+ PARALLEL (32)*/
        AC.SAFRA
        ,'CMV' AS NM_MARCA
        ,'WHATSAPP' AS DSC_METODO_CONTATO
        ,AC.COD_SHORT_CODE
        ,AC.COD_PLATAFORMA
        ,AC.NUM_NTC
        ,COUNT(DISTINCT(AC.SK_ACESSO)) AS QT_ACESSO
        ,CASE WHEN CN.NUM_NTC IS NULL THEN 0 ELSE 1 END AS FLG_ACESSOU_CANAIS       
        ,CASE WHEN CN.NUM_NTC IS NULL THEN 'SOMENTE ACESSOU WHASTAPP' ELSE 'ACESSOU OUTROS CANAIS' END AS DSC_ACESSOU_CANAIS
        ,CASE WHEN CN.DSC_METODO_CONTATO = 'CallCenter' THEN 1 ELSE 0 END AS FLG_LIGOU  
        ,CASE WHEN CN.DSC_METODO_CONTATO = 'MCM'  THEN 1 ELSE 0 END AS FLG_MCM
        ,CASE WHEN CN.DSC_METODO_CONTATO = 'USSD'  THEN 1 ELSE 0 END AS FLG_USSD      
        /*,CASE WHEN CN.DSC_METODO_CONTATO IN('CallCenter','MCM','USSD') THEN 1 ELSE 0 END AS DSC_ANALISE     */
     FROM TMP_SQDAA_ACESSO_WHATSAPP_P1 AC --> BASE DE ACESSO WHATSAPP
LEFT JOIN TMP_SQDAA_ACESSO_WHATSAPP_P5 CN ON CN.NUM_NTC = AC.NUM_NTC --> agregado TODOS os CANAIS = USSD + MCM + CALL CENTER

GROUP BY AC.SAFRA
        ,AC.COD_PLATAFORMA
        ,AC.NUM_NTC
       ,AC.COD_SHORT_CODE
       ,AC.COD_PLATAFORMA
       ,CASE WHEN CN.NUM_NTC IS NULL THEN 0 ELSE 1 END       
       ,CASE WHEN CN.NUM_NTC IS NULL THEN 'SOMENTE ACESSOU WHASTAPP' ELSE 'ACESSOU OUTROS CANAIS' END 
       ,CASE WHEN CN.DSC_METODO_CONTATO = 'CallCenter' THEN 1 ELSE 0 END  
       ,CASE WHEN CN.DSC_METODO_CONTATO = 'MCM'  THEN 1 ELSE 0 END
       ,CASE WHEN CN.DSC_METODO_CONTATO = 'USSD'  THEN 1 ELSE 0 END
      /* ,CASE WHEN CN.DSC_METODO_CONTATO IN('CallCenter','MCM','USSD') THEN 1 ELSE 0 END    */
; 

SELECT  
      AC.SAFRA
      ,AC.COD_PLATAFORMA
      ,AC.COD_SHORT_CODE
      ,AC.DSC_METODO_CONTATO
      ,AC.COD_PLATAFORMA
      ,COUNT(NUM_NTC) AS QT_USU_UNICOS
      ,SUM(QT_ACESSO) AS QT_ACESSO
      ,AC.DSC_ACESSOU_CANAIS
      ,SUM(AC.FLG_ACESSOU_CANAIS) AS QT_FLG_ACESSOU_CANAIS
      ,SUM(AC.FLG_LIGOU) AS QT_LIGOU
      ,SUM(AC.FLG_MCM) AS QT_MCM
      ,SUM(AC.FLG_USSD) AS QT_USSD
--select *    
FROM BI_FT_WHATSAPP_COMPORT_ACESSO AC
GROUP BY AC.SAFRA
      ,AC.COD_PLATAFORMA
      ,AC.COD_SHORT_CODE
      ,AC.COD_PLATAFORMA
      ,AC.DSC_METODO_CONTATO
      ,AC.DSC_ACESSOU_CANAIS
;
--AC.NUM_NTC = 11930071948 --> CLIENTE ACESSOU WHATSAPP EM ABR/2020 E LIGOU


/*--====================================================================================================================
  ANALISE ABAIXO É SOBRE:
  Clientes que acessam whatsapp antes tinham o comportamento de ligação e agora usam o canal? Deixaram de ligar por causa do whatsapp? Reduzimos quanto do CR?
--====================================================================================================================*/

--ETAPA 7 ACESSO WHATSAPP_P1
DROP TABLE TMP_SQDAA_ACESSO_WHATSAPP_UU;
CREATE TABLE TMP_SQDAA_ACESSO_WHATSAPP_UU COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT /*+parallel (32)*/ ------------------------------------------------------------------------ETAPA 1 ACESSO WPP
        MAX(A.DAT_INICIO_ATENDIMENTO) AS DT_REFERENCIA
        ,A.COD_PLATAFORMA --ok
        ,A.NUM_NTC --ok
        ,MIN(A.DAT_INICIO_ATENDIMENTO) AS DT_PRI_ATENDIMENTO
        ,A.COD_SHORT_CODE
        ,'WhatsApp' AS DSC_METODO_CONTATO       
        ,SYSDATE                       AS DAT_CRIACAO
FROM DWH.BI_FP_ATENDIMENTO_MINT A
LEFT JOIN DWH.BI_DIM_CANAL_MINT B ON A.DW_NUM_CANAL_MINT = B.DW_NUM_CANAL_MINT
WHERE A.COD_SHORT_CODE = 9652 --- SHORT CODE WPP
AND A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND A.COD_PLATAFORMA NOT IN ('-2','-3') --> SOMENTE CLIENTES MÓVEIS

GROUP BY  A.COD_PLATAFORMA
         ,A.NUM_NTC --ok
         ,A.COD_SHORT_CODE
;




--MOTIVOS WHATSAPP

SELECT UNIQUE DAT_REFERENCIA  FROM BI_FT_RET_DIG_WHATSAPP;
1  30/04/2020
2	31/03/2020
3	30/01/2020
4	30/12/2019
5	29/02/2020

DROP TABLE TMP_SQDAA_WPP_MOT_P1;
CREATE TABLE TMP_SQDAA_WPP_MOT_P1 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT 
        A.DAT_REFERENCIA
        ,SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6) AS SAFRA --ok
        ,TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') AS SK_DATA --ok
        ,A.COD_PLATAFORMA --ok
        ,A.NUM_NTC --ok
        ,A.DAT_INICIO_ATENDIMENTO AS DT_INI_ATENDIMENTO
        ,TRUNC(A.DAT_INICIO_ATENDIMENTO) AS DAT_INICIO_ATENDIMENTO --ok
        ,TO_CHAR(A.NUM_NTC ||' '||TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') ||' '||REPLACE(SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO,'dd/mm/yyyy hh24:mi:ss'),12,8),':','')) AS SK_ACESSO 
       ,C.DW_MENU_MINT
       ,C.DSC_MENU_MINT
     FROM DWH.BI_FP_ATENDIMENTO_MINT A
LEFT JOIN DWH.BI_DIM_CANAL_MINT B ON A.DW_NUM_CANAL_MINT = B.DW_NUM_CANAL_MINT
LEFT JOIN DWH.BI_DIM_MENU_MINT C  ON A.DW_NUM_CANAL_MINT = C.DW_NUM_CANAL_MINT

WHERE A.COD_SHORT_CODE = 9652 --- SHORT CODE WPP
AND A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND A.COD_PLATAFORMA NOT IN ('-1','-2','-3')--> SOMENTE CLIENTES CLARO QUE HÁ NTC COM PRODUTO VIGENTE
AND C.NUM_OPCAO_MENU_MINT NOT IN (0,-1,-2,-3) --> SOMENTE NAVEGAÇÃO DO MENU ONDE NÃO HÁ VOLTAR E NAO APLICAVEL
AND C.DSC_MENU_MINT IS NOT NULL --> RETIRANDO NAVEGAÇÃO ONDE A DESCRIÇÃO DA FUNCIONALIDADE
;






SELECT * FROM DWH.BI_DIM_MENU_MINT;

WITH 
TMP_SQD_AA_WTSAPP_01 AS

(SELECT /*+parallel (32)*/
        A.DAT_REFERENCIA,
        A.COD_PLATAFORMA,
        A.COD_ATENDIMENTO

FROM DWH.BI_FP_ATENDIMENTO_MINT A
LEFT JOIN DWH.BI_DIM_CANAL_MINT B ON A.DW_NUM_CANAL_MINT = B.DW_NUM_CANAL_MINT
WHERE A.COD_SHORT_CODE = 9652 --- SHORT CODE DO WHATSAPP
--WHERE A.COD_SHORT_CODE = 1052 --- SHORT CODE DO USSD
AND A.DAT_REFERENCIA BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')),

TMP_SQD_AA_WTSAPP_02 AS

(SELECT  /*+PARALLEL (32)*/
        A.DAT_REFERENCIA
       ,A.COD_PLATAFORMA
       ,C.DSC_NOS_MINT
       ,D.PARA AS DSC_PARA_MINT

FROM TMP_SQD_AA_WTSAPP_01 A
LEFT JOIN DWH.BI_FP_NAVEGACAO_MINT B ON A.COD_ATENDIMENTO = B.COD_ATENDIMENTO
                                    AND A.DAT_REFERENCIA  = B.DAT_REFERENCIA
LEFT JOIN DWH.BI_DIM_NOS_MINT C ON B.DW_NOS_MINT = C.DW_NOS_MINT
LEFT JOIN INTMKT.DE_PARA_MINT D ON C.DSC_NOS_MINT = D.DE
                                                                      
WHERE B.DW_NUM_CANAL_MINT = 2)

SELECT * FROM TMP_SQD_AA_WTSAPP_02



--- MODELO 2
DROP TABLE TMP_SQDAA_WPP_MOT_P2;
CREATE TABLE TMP_SQDAA_WPP_MOT_P2 COMPRESS FOR QUERY HIGH PARALLEL 256 NOLOGGING AS
SELECT DISTINCT
       SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6) AS SAFRA --ok              
       ,C.DW_MENU_MINT
       ,C.DSC_MENU_MINT
       ,COUNT(DISTINCT(A.NUM_NTC)) AS QT_USUÁRIOS
       ,COUNT(*) AS QT_TRANSACOES
     FROM DWH.BI_FP_ATENDIMENTO_MINT A
INNER JOIN U92047747.BI_FT_RET_DIG_WHATSAPP D ON A.NUM_NTC = D.NUM_NTC AND TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD') = D.SK_DATA
LEFT JOIN DWH.BI_DIM_CANAL_MINT B ON A.DW_NUM_CANAL_MINT = B.DW_NUM_CANAL_MINT
LEFT JOIN DWH.BI_DIM_MENU_MINT C  ON A.DW_NUM_CANAL_MINT = C.DW_NUM_CANAL_MINT

WHERE A.COD_SHORT_CODE = 9652 --- SHORT CODE WPP
AND A.DAT_INICIO_ATENDIMENTO BETWEEN TO_DATE(&DATA_INICIAL, 'RRRRMMDD') AND  TO_DATE(&DATA_FINAL, 'RRRRMMDD')
AND A.COD_PLATAFORMA NOT IN ('-1','-2','-3')--> SOMENTE CLIENTES CLARO QUE HÁ NTC COM PRODUTO VIGENTE
AND C.NUM_OPCAO_MENU_MINT NOT IN (0,-1,-2,-3) --> SOMENTE NAVEGAÇÃO DO MENU ONDE NÃO HÁ VOLTAR E NAO APLICAVEL
AND C.DSC_MENU_MINT IS NOT NULL --> RETIRANDO NAVEGAÇÃO ONDE A DESCRIÇÃO DA FUNCIONALIDADE
AND D.DSC_VISAO_ANALISE = 'RETIDO DIGITAL'

GROUP BY SUBSTR(TO_CHAR(A.DAT_INICIO_ATENDIMENTO, 'YYYYMMDD'),1,6)              
       ,C.DW_MENU_MINT
       ,C.DSC_MENU_MINT

;

